<h1><strong><span style="text-decoration: underline;">Welcome to ABC College Planning</span></strong><br /></h1>
<p>ABC College Planning provides college bound students with  financial strategies, guidance in selecting the right school, and peace  of mind in knowing that every aspect of merit and need based aid is  being addressed with the highest standard of expertise.</p>
<p>These services have been strategically selected by financial aid  officers, financial aid directors, admissions officers, tutors,  accountants and the like, and are now available online through this web  site to benefit those who may not have direct access to specifically  qualified counselor.</p>
<p>At ABC College Planning we are committed to supporting you throughout  your endeavor by being&nbsp;available, not only through our website, but  also, by providing "one on one" support as well.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<em><span style="text-decoration: underline;"><strong> Services</strong></span></em></p>
<p>* Middle School and High School Planning<br />* PSAT/SAT/ACT Unlimited Tutoring and Practice Tests<br />* Admission Essay Editing&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />* Career/College Assesment and Analysis &nbsp;&nbsp; <br />* Financial Aid and Student Loan Info.<br />* Scholarship Search<br />* Educational Workshops</p>
<p>
<script type="text/javascript"><!--
<br /><br />  var _gaq = _gaq || [];<br />  _gaq.push(['_setAccount', 'UA-27902258-1']);<br />  _gaq.push(['_trackPageview']);<br /><br />  (function() {<br />    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;<br />    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';<br />    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);<br />  })();<br /><br />
// --></script>
</p>
<p>&nbsp;</p>