<p>CES is an Affiliate of Planet Tuition. Our College Planning Process is designed to provide&nbsp;families a better result and reducing the cost of college. We complement the high school guidance counselor, support the students and simplify life for the family saving time and money.</p>
<p>&nbsp;</p>
<p><img src="http://collegeeducationsolutions.collegiate-advisor.com/advisor_files/56/ces-process.jpg" alt="CES Process" /></p>
<p>&nbsp;</p>
<p>&nbsp;</p>