<p><strong>Toll Free:</strong>&nbsp;&nbsp;&nbsp;&nbsp; 1-866-508-0065</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><span style="text-decoration: underline;"><strong>Missouri, Columbia&nbsp; (Home Office)<br /></strong></span></p>
<address>111 E Broadway, Ste. 120<br /></address> <address>Columbia, MO 65203</address><address>(entrance faces 2nd street)</address><address><br /></address><address><a href="http://maps.yahoo.com/#mvt=m&amp;lat=38.951783&amp;lon=-92.336046&amp;zoom=17&amp;q1=111%20E%20Broadway,%20Ste%20120,%20Columbia,%20MO,%2065203" target="_blank"><span style="text-decoration: underline;"><strong>MAP</strong></span></a><br /></address>
<p><em><br /></em></p>
<div style="width: 35%; margin-left: 10px; line-height: 130px; background-image: url(http://photos-h.ak.fbcdn.net/hphotos-ak-snc1/hs244.snc1/9125_782832670050_15913739_44224791_6529326_n.jpg);">
<p style="margin-left:10px;"><a class="lftCat" href="http://photos-g.ak.fbcdn.net/hphotos-ak-snc1/hs264.snc1/9125_782830115170_15913739_44224734_977518_n.jpg">.</a></p>
</div>
<p>&nbsp;</p>
<p><strong><span style="text-decoration: underline;">Missouri, St. Louis - Chesterfield</span><br /></strong></p>
<address> 100 Chesterfield Business Parkway</address><address>2nd Floor</address><address>St. Louis, Missouri 63005</address><address><br /></address><address><a href="http://maps.yahoo.com/#mvt=m&amp;lat=38.667783&amp;lon=-90.619392&amp;zoom=17&amp;q1=100%20Chesterfield%20Business%20Parkway,%20St.%20Louis,%20Missouri%2063005%20United%20States" target="_blank"><span style="text-decoration: underline;"><strong>MAP</strong></span></a><br /></address><address><img src="file:///C:/Users/Stevie-Jo/Desktop/Education%20Outlook,%20LLC/Images/office%20stl.jpg" alt="" /></address>
<p><img src="file:///C:/Users/Stevie-Jo/Desktop/Education%20Outlook,%20LLC/Images/ccps.gif" alt="" /><img src="file:///C:/Users/Stevie-Jo/Desktop/Education%20Outlook,%20LLC/Images/ccps.gif" alt="" /></p>
<div style="width: 32%; margin-left: 10px; line-height: 150px; background-image: url(http://www.regus.com/assets/global/images/centers/0707_01.jpg);">
<p style="margin-left:10px;"><a class="lftCat" href="http://www.regus.com/assets/global/images/centers/0707_01.jpg">.</a></p>
</div>