<div id="sub_menu">

	<ul>

		<li><a href="<?php echo SITE_URL; ?>/member/tax/">Tax Overview</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/tax/opportunity">American Opportunity Tax Credit</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/tax/lifetime_learning">Lifetime Learning Tax Credit</a></li><br>
		<li class="last"><a href="<?php echo SITE_URL; ?>/member/tax/tuition_fees">Tuition and Fees Tax Deduction</a></li>

	</ul>

</div>