<div id="member_tax_hope">

	<h1>The American Opportunity Tax Credit</h1>


<p>As of January 2013, The American Opportunity Tax Credit has been extended through 2017. The advantage to parents is quite profound.   Below is an overview of the parameters.</p>

<p><strong>Maximum credit</strong></p>  
<p>Up to a maximum of $2,500 per each eligible student</p>

<p><strong>Limit on modified adjusted gross income (MAGI)</strong></p>  
<p>$180,000 if married filing jointly; $90,000 if single, head of household, or qualifying widow(er)</p>

<p><strong>Time Period of Eligibility</strong></p>  
<p>Available if the student had not completed the first 4 years of college education before the tax year in question </p>

<p><strong>Term of Eligibility</strong></p> 
<p>4 years per student</p>

<p><strong>Term of when the payments were made</strong></p> 
<p>The tax year in question and 3 months into the next tax year.</p>

<p><strong>Type of program required</strong></p>  
<p>Student must be pursuing a program leading to a degree or other recognized education credential</p>

<p><strong>Required Enrollment</strong></p> 
<p>Student must be enrolled at least half time for at least one academic period that begins during the tax year</p>

<p><strong>Qualified expenses</strong></p>  
<p>Tuition, required enrollment fees, and materials that the student needs for a course of study whether or not the materials are bought  at the educational institution as a condition of enrollment or attendance</p>

<p><strong>Felony drug conviction </strong></p> 
<p>As of the end of the prior calendar year, the student had not been convicted of a felony for possessing or distributing a controlled substance</p>











	<!--<p>The American Opportunity Tax Credit has for the years of 2009 and 2010 replaced the Hope Tax Credit.  The American Opportunity Tax Credit is part of the 2009 Stimulus Package.  The advantage to parents is quite profound.</p>

	<ol>

		<li>As opposed to the Hope Tax Credit the American Opportunity Tax Credit is valid for the first four years of post-secondary education.</li>
		<li>This credit can be used for any and all post-secondary education expense, including tuition, fees, and all other course related expenses.</li>
		<li>The credit is good for up to 100% of the first $2,000 per student, and then 25% of the subsequent $2,000.  Thus as a whole the full credit is $2,500 for a taxpayer who pays a minimum of $4,000 in qualified expenses.</li>
		<li>The income limitation for this credit is $80,000 or $160,000 for married couples filing a joint return.  Thereafter the credit decreases in relation to the amount of annual income.</li>
		<li>40% of the tax is refundable, thus if a family has not tax liability the family will still receive up to $1000 cash back.</li>
		<li>One must determine which is most beneficial to the taxpayer, the American Opportunity Tax Credit, The Lifetime Learning Credit or the standard tuition and fees deduction.  Multiple claims are not allowed in any given tax year.</li>

	</ol>-->

	<h6>Download</h6>

	<p><a href="<?php echo SITE_URL; ?>/member/private_file/2012_8863">Form 8863</a> - to file for your taxes, you will need adobe acrobat and can fill the form out online and print.</p>
	<p><a href="<?php echo SITE_URL; ?>/member/private_file/2012_970">Publication 970</a> - the IRS publication explaining the tax code in adobe acrobat format.</p>

</div>