<h1>Praises for Scholarship Seeker's Toolbox</h1>
<p>The Scholarship Seekers Toolbox was developed by Ben Kaplan, America's Scholarship Coach.  Ben Kaplan supports incorporating an admission, academic, and financial approach towards helping thousands of parents and students to find affordable ways to attend the college of their choice and substantially reduce the college debt burden being placed upon many students and families today.  Please read the noteworthy praise for the scholarship system pioneered by Ben Kaplan, supported and implemented by Wisconsin College Planning, LLC providing many families with proven strategies to obtain thousands of dollars of free money for future students and families.</p>
<table border="0" cellpadding="0" width="570">
<tbody>
<tr valign="top">
<td style="width: 275px;">
<p>"Anyone seeking higher education in America, young and old, should entertain Ben Kaplan's advice, not only for financial reasons, but to also share in the greater lesson he has to offer -- anything is possible if you put your mind to it"</p>
<p style="text-align: right;"><strong>- US Senator John F. Kerry (D-MA)</strong></p>
<p>"I hope that students and educators alike will take inspiration fromt he work of Ben and his friends... I look forward to witnessing the results!"</p>
<p style="text-align: right;"><strong>- US Senator Mark O. Hatfield (R-OR)</strong></p>
<p>"What Dr. Ruth does for the human libido, Ben aims to do for the tuition subsidy."</p>
<p style="text-align: right;"><strong>- The Boston Globe</strong></p>
<p>"If winning scholarships were a sport, Ben Kaplan would surely be in the Hall of Fame... Ben made it happen, and he shows how anyone in pursuit of college cash can make it happen to."</p>
<p style="text-align: right;"><strong>- Stedman Graham, Author<br />You Can Make It Happen</strong></p>
<p>"A terrific example of a proactive person choosing to make it happen... What a great difference he's making!"</p>
<p style="text-align: right;"><strong>- Sean Covey, Author<br />The 7 Habits of Highly Effective Teens</strong></p>
</td>
<td style="padding: 10px;">
<p>"Ben shows step-by-step how to take advantage of hundreds of millions of dollars in scholarships that are out there waiting for you... fantastic"</p>
<p style="text-align: right;"><strong>- Oprah Winfrey</strong></p>
<p>"Ben speaks with an energy and confidence that might remind an older generation of Dale Carnegie."</p>
<p style="text-align: right;"><strong>- Seattle Post-Intelligencer</strong></p>
<p>"If you want to win scholarship money, then go with a winner... Ben speaks directly to students in their language, with practical tips and interesting insights into the 'winning attitude'."</p>
<p style="text-align: right;"><strong>- Rocco Marano, Director of Student Activities - National Association of Secondary School Principals</strong></p>
<p>"As one well-worn Chinese proverb goes, 'to know the road ahead, ask those coming back.' In the case of paying for college, we'd want to ask Ben Kaplan."</p>
<p style="text-align: right;"><strong>- The Washington Post</strong></p>
<p>"Ben is in his twenties, out of Harvard, with a great education and not a dime in debt... How do you beat that?"</p>
<p style="text-align: right;"><strong>- Shepard Smith, Author<br />Fox News Channel<br /></strong></p>
</td>
</tr>
</tbody>
</table>