<h1>Scholarship Seeker's Toolbox</h1>
<table border="0" width="500">
<tbody>
<tr>
<td><strong>Action Steps</strong></td>
<td style="text-align: center"><strong>Action Step Description</strong></td>
</tr>
<tr>
<td>Action Step # 1</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step1">Identify Your Unique Scholarship Profile</a></td>
</tr>
<tr>
<td>Action Step # 2</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step2">Conduct a Personal Inventory of Your Credentials</a></td>
</tr>
<tr>
<td>Action Step # 3</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step3">Harvest School Resources</a></td>
</tr>
<tr>
<td>Action Step # 4</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step4">Search Internet Scholarship Databases</a></td>
</tr>
<tr>
<td>Action Step # 5</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step5">Seek Out Government Funding Sources</a></td>
</tr>
<tr>
<td>Action Step # 6</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step6">Explore Personal, family and Community Leads</a></td>
</tr>
<tr>
<td>Action Step # 7</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step7">Track Down Awards From Individual Colleges</a></td>
</tr>
<tr>
<td>Action Step # 8</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step8">Create a Priority Scholarship Calendar</a></td>
</tr>
<tr>
<td>Action Step # 9</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step9">Brainstorm Your Application Themes</a></td>
</tr>
<tr>
<td>Action Step # 10</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step10">Enhance Your Record in Key Areas</a></td>
</tr>
<tr>
<td>Action Step # 11</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step11">Scope Out Hidden Judging Criteria</a></td>
</tr>
<tr>
<td>Action Step # 12</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step12">Craft an Essay Rough Draft</a></td>
</tr>
<tr>
<td>Action Step # 13</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step13">Revise Your Essay Draft</a></td>
</tr>
<tr>
<td>Action Step # 14</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step14">Format Your Activities and Honors</a></td>
</tr>
<tr>
<td>Action Step # 15</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step15">Develop Quality Recommendation Letters</a></td>
</tr>
<tr>
<td>Action Step # 16</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step16">Ace the Scholarship Interview</a></td>
</tr>
<tr>
<td>Action Step # 17</td>
<td style="text-align: center"><a href="http://wisconsincollegeplanning.collegiate-advisor.com/member/private_file/advisors/20/action-step17">Earn Free Tuition Credits</a></td>
</tr>
</tbody>
</table>