<h1>Scholarship Seeker's Toolbox</h1>
<table border="0" width="500">
<tbody>
<tr>
<td><strong>Action Steps</strong></td>
<td></td>
</tr>
<tr>
<td>Action Step # 1</td>
<td style="text-align: center;">Identify Your Unique Scholarship Profile</td>
</tr>
<tr>
<td>Action Step # 2</td>
<td style="text-align: center;">Conduct a Personal Inventory of Your Credentials</td>
</tr>
<tr>
<td>Action Step # 3</td>
<td style="text-align: center;">Harvest School Resources</td>
</tr>
<tr>
<td>Action Step # 4</td>
<td style="text-align: center;">Search Internet Scholarship Databases</td>
</tr>
<tr>
<td>Action Step # 5</td>
<td style="text-align: center;">Seek Out Government Funding Sources</td>
</tr>
<tr>
<td>Action Step # 6</td>
<td style="text-align: center;">Explore Personal, family and Community Leads</td>
</tr>
<tr>
<td>Action Step # 7</td>
<td style="text-align: center;">Track Down Awards From Individual Colleges</td>
</tr>
<tr>
<td>Action Step # 8</td>
<td style="text-align: center;">Create a Priority Scholarship Calendar</td>
</tr>
<tr>
<td>Action Step # 9</td>
<td style="text-align: center;">Brainstorm Your Application Themes</td>
</tr>
<tr>
<td>Action Step # 10</td>
<td style="text-align: center;">Enhance Your Record in Key Areas</td>
</tr>
<tr>
<td>Action Step # 11</td>
<td style="text-align: center;">Scope Out Hidden Judging Criteria</td>
</tr>
<tr>
<td>Action Step # 12</td>
<td style="text-align: center;">Craft an Essay Rough Draft</td>
</tr>
<tr>
<td>Action Step # 13</td>
<td style="text-align: center;">Revise Your Essay Draft</td>
</tr>
<tr>
<td>Action Step # 14</td>
<td style="text-align: center;">Format Your Activities and Honors</td>
</tr>
<tr>
<td>Action Step # 15</td>
<td style="text-align: center;">Develop Quality Recommendation Letters</td>
</tr>
<tr>
<td>Action Step # 16</td>
<td style="text-align: center;">Ace the Scholarship Interview</td>
</tr>
<tr>
<td>Action Step # 17</td>
<td style="text-align: center;">
<p>Earn Free Tuition Credits</p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>Implementing the use of private scholarships can be very successful when incorporated with a balanced approach using the academic, admission, and financial tenants. Implementing only one approach will obtain you marginal results. Implementing the three different tenants will give you a plan and will help get your student into the college of their choice with a substantial lowered price tag.</p>