<h1>Resources 	 	&nbsp;&nbsp;</h1>
<p>College Funding Coaches is dedicated to assisting families in the complicated and often confusing process of determining how they will pay for college&hellip;without incurring unnecessary debt or postponing retirement.</p>
<p>
<table border="0">
<thead>
<tr>
<th colspan="2">College Admissions &amp; Testing</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="http://www.act.org/" target="_blank">ACT Website</a></td>
<td><a href="http://www.collegeboard.com/" target="_blank">College Board Online</a></td>
</tr>
<tr>
<th colspan="2">College Information</th>
</tr>
<tr>
<td><a href="http://www.collegebound.net/studentrewards/" target="_blank">Collegebound Network</a></td>
<td><a href="http://www.collegelink.com/" target="_blank">College Link</a></td>
</tr>
<tr>
<td><a href="http://www.newsdirectory.com/college.php" target="_blank">College locator</a></td>
<td><a href="http://www.powerprep.com/" target="_blank">College Power Prep</a></td>
</tr>
<tr>
<td><a href="http://www.college-solutions.com/" target="_blank">College Solutions</a></td>
<td><a href="http://www.campustours.com/" target="_blank">Campus Tours</a></td>
</tr>
<tr>
<td><a href="http://www.mycollegeguide.com/" target="_blank">My College Guide</a></td>
<td><a href="http://www.collegequest.com/" target="_blank">Peterson's College Quest</a></td>
</tr>
<tr>
<td><a href="http://www.princetonreview.com/home.asp" target="_blank">The Princeton Review</a></td>
<td>&nbsp;</td>
</tr>
<tr>
<th colspan="2">Financial Aid</th>
</tr>
<tr>
<td><a href="http://apps.collegeboard.com/cbsearch_ss/welcome.jsp" target="_blank">College Board Financial Aid Search</a></td>
<td><a href="http://www.wachovia.com/personal/page/0,,325_496,00.html" target="_blank">Educaid</a></td>
</tr>
<tr>
<td><a href="http://www.edfund.org/" target="_blank">Ed Fund</a></td>
<td><a href="http://ccsd.net/CPD/guidance/guidance.html" target="_blank">CCSD Guidance and Counseling</a></td>
</tr>
<tr>
<td><a href="http://www.fafsa.ed.gov/" target="_blank">FAFSA on the Web</a></td>
<td><a href="http://www.fastweb.com/" target="_blank">FastWeb</a></td>
</tr>
<tr>
<td><a href="http://www.finaid.org/" target="_blank">FINAID (Financial Aid Info Page)</a></td>
<td><a href="http://www.kaplan.com/" target="_blank">Kaplan Inc.</a></td>
</tr>
<tr>
<td><a href="http://nvcis.intocareers.org/" target="_blank">Nevada Career Information System</a></td>
<td><a href="http://www.princetonreview.com/college/default.asp" target="_blank">Princeton Review Financial Aid</a></td>
</tr>
<tr>
<td><a href="http://www.salliemae.com/" target="_blank">Sallie Mae</a></td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
</p>
<p>&nbsp;</p>