<div id="about">

	<h1>Pro EFC&reg; DATA FORM  </h1>
	
	<p>Upon completion of the Pro  EFC&reg;   DATA FORM we can quickly get back to you as to not only your EFC, (for definition see below), but also what specific grants and scholarships are available at the college(s) that the student is considering.  It is important that you enter the student's education statistics so that we can respond with an accurate grant and scholarship analysis.</p>
	<p>To complete the Pro  EFC&reg;   DATA you will need to have handy or know the following:</p>
	<ol>
		<li>Information for your most recent tax return</li>
		<li>W2 information</li>
		<li>Financial Information</li>
		<li>The students ACT or SAT score(s), Class Ranking and GPA</li>
	</ol>
	
	<p>To get started on the Pro EFC&reg;   DATA <a href="https://www.collegiatefundingsolutions.com/dataform_setup.php?ref=collegiate-advisors-<?php echo SUBDOMAIN; ?>" target="_blank">CLICK HERE</a> or for more information continue reading.</p>
	
	<p>The information that you supply in the Pro EFC&reg;   DATA FORM allows us to calculate your Expected Family Contribution.  The financial aid formula is actually quite simple, it is:</p>

	<blockquote>
		&nbsp;&nbsp;&nbsp;ECOA	(Estimated Cost of Attendance)<br />
		-	EFC	(Expected Family Contribution)<br />
		<hr />
		=	Need
	</blockquote>
	<br />
	
	<h3>ECOA</h3>
	<p>The ECOA includes tuition and fees, room and board, books and supplies, personal expenses and travel.  The ECOA can vary widely from school to school and from student to student based on individual circumstances.</p>

	<h3>EFC</h3>
	<p>The EFC is the amount of money that the family is expected to contribute toward the cost of college before receiving grants or loans from or through the government.  The formula for determining this amount takes into account a family's (i.e., parents and student) income, assets and other relevant variables. The information used to determine the EFC is typically submitted on the FAFSA (Free Application for Federal Student Aid) form.</p>

	<h3>Need</h3>
	<p>By subtracting your EFC from the ECOA at the school you are considering determines if you have what is called Need.  If you have Need you are a candidate for financial aid.</p>

	<p>Depending on whether or not you are a candidate for financial aid provides the starting point for developing an effective college savings/funding plan and identifying and implementing strategies to help reduce the burden of college costs.</p>
	
	<p>To get started on the Pro EFC&reg; DATA, <a href="https://www.collegiatefundingsolutions.com/dataform_setup.php?ref=collegiate-advisors-<?php echo SUBDOMAIN; ?>" target="_blank">CLICK HERE</a></p>

	
	<?php echo $GLOBALS['advisor']->get( 'full_about' ); ?>	
	
</div>