<p>To us, proper college planning answers three (3) questions:</p>
<p>1)&nbsp; What should my student major in to prepare them for the career they desire?</p>
<p>2)&nbsp; What school does my student <em>fit</em> at the best?</p>
<p>3)&nbsp; How can we, the parents, pay the least amount out of pocket for college expenses?</p>
<p>Michael Cutbirth, the principal consultant at Premier College Planning, is a Certified College Planning Specialist, CERTIFIED FINANCIAL PLANNER (TM) professional, and has almost 10 years of personal and professional experience in the college planning and funding marketplace.&nbsp; Feel free to explore our site and contact us to sign up for our College Planning e-newsletter.</p>