<div id="<?php echo $page; ?>">

	<script type="text/javascript" src="<?php echo SITE_URL . '/js/tiny_mce/tiny_mce_gzip.js'; ?>"></script>

	<script type="text/javascript">
	
		tinyMCE_GZ.init({
			plugins: "table",
			themes: "advanced",
			languages: "en",
			disk_cache: true,
			debug: false
		});
		
	</script>

	<script type="text/javascript">
	
		tinyMCE.init({
			mode: "exact",
			elements: "page_content",
			theme: "advanced",
			skin: "o2k7",
			skin_variant: "black",
			plugins: "table",
			
			theme_advanced_buttons1: "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,|,link,unlink,|,bullist,numlist,|,blockquote,|,undo",
			theme_advanced_buttons2: "tablecontrols,|,code",
			theme_advanced_buttons3: ""
			
		});
	
	</script>
	
	<style>

		#page_content
		{
			width: 500px;
			height: 400px;
		}
	
	</style>

	<h1>Add Editable Page</h1>

	<?php echo $form->output(); ?>
	
</div>