<li>Take the SAT I or SAT II</li>
<li>Remember to get a certificate of mailing at the Post Office for all your applications</li>
<li>Make copies of everything you mail to everyone! That includes all applications, financial aid info., etc.</li>
<li>Most Early Action and Early Decision deadlines are this month</li>
<li>Think about recommendation letters, and let your teachers and your counselor know what activities, etc., you have been involved in</li>
<li>Watch for deadlines!</li>