{workshop_registration}

{registrant_information}

	{first_name}
	{last_name}
	<br />
	
	{guests}
	<br />
	
	{phone_number}
	{email_address}
	<br />
	
	{grades}
		<table class="childrens_grades">
			<tbody>
				<tr>
					<td>{grade1}</td>
					<td>{grade5}</td>
					<td>{grade9}</td>
				</tr>
				<tr>
					<td>{grade2}</td>
					<td>{grade6}</td>
					<td>{grade10}</td>
				</tr>
				<tr>
					<td>{grade3}</td>
					<td>{grade7}</td>
					<td>{grade11}</td>
				</tr>
				<tr>
					<td>{grade4}</td>
					<td>{grade8}</td>
					<td>{grade12}</td>
				</tr>
				<tr>
					<td colspan="3"><br /></td>
				</tr>
				<tr>
					<td>College:</td>
					<td>{grade13}</td>
					<td>{grade14}</td>
				</tr>
				<tr>
					<td></td>
					<td>{grade15}</td>
					<td>{grade16}</td>
				</tr>
			</tbody>
		</table>
	{grades}
	<br />
	
	{register}

{registrant_information}