<p><br></p><p><br></p><p><b>Holistic Education&nbsp;Funding&nbsp;</b></p>
<p><br></p>
<p>At Collegiate Advising Group, we help families fund their college education and build strategies to reduce the cost of college and get students into their school of choice.&nbsp;&nbsp;</p>
<p><br></p>
<p><i><b>We can help you pay for college without massive debt...</b></i></p>
<p><br></p>
<p>Current clients can <a href="../../../login" mce_href="../../../login">login to this site</a> for valuable resources on education funding, planning strategies to reduce college costs, ACT/SAT preparation courses and a host of other services geared to prepare students during high school and to support them through their college years.</p>
<p><a href="../../../login" mce_href="../../../login"><br></a></p>
<p><a href="../../../user_signup" mce_href="../../../user_signup"><b></b></a></p>
<p><!--<span class="end-tag"--></p>
<p><b></b></p>
<p><i><b><a href="../../../user_signup" mce_href="../../../user_signup">Ready to sign-up?</a></b></i></p>
<p><br></p>
<p><b></b></p>
<p><a href="../../../services" mce_href="../../../services">If you would like to learn more about our services</a> and how we can help make college an affordable reality for you, please don't hesitate to contact us at <a href="mailto:info@collegiateadvisinggroup.com" mce_href="mailto:info@collegiateadvisinggroup.com">info@collegiateadvisinggroup.com</a>, or by contacting us locally in Michigan at <b>(248) 391-8399</b> or, toll free at <b>(800) 258-0810</b>.</p>
<p><br></p>
<p><i><b>No matter where you're located in the United States...we can help you!!!</b></i></p>
<p><br></p>
<p><i><b><a href="../../../user_signup" mce_href="../../../user_signup">Click here to sign-up now!<br></a></b></i></p>
<p><br></p>
<p><u><b>WARNING!!!</b></u></p>
<p><br></p>
<p>The U.S. credit problems are now putting student loan companies out of business.&nbsp; Both Student and Parent Loans for Education may be impossible to get!</p>
<p><b><br></b></p>
<p><b>How will YOU pay for college?</b></p>
<p><br></p>
<p>If you're looking for ways to <i><b>fund college when student loan companies say NO</b></i>...please contact us at <a href="mailto:info@collegiateadvisinggroup.com" mce_href="mailto:info@collegiateadvisinggroup.com">info@collegiateadvisinggroup.com</a>.</p>
<p><i><b><br></b></i></p>
<p><i><b>We'll show you how to avoid this credit crisis using time-tested cash flow planning strategies.</b></i></p>