<div id="admin_news_view">

	<h1>View News</h1>

	<ul class="commands">
	 
		<li><a href="<?php echo SITE_URL . '/admin/news/edit/' . $news->get( 'id' ); ?>">Edit News</a></li>     
		
	</ul>

	<table cellspacing="0" class="information_table">
		<tr>
			<td>News ID:</td>
			<td><?php echo $news->get( 'id' ); ?></td>
		</tr>
		<tr>
			<td>Date:</td>
			<td><?php echo date( 'F j, Y', $news->get( 'date' ) ); ?></td>
		</tr>
		<tr>
			<td>News:</td>
			<td><?php echo $news->get( 'news' ); ?></td>
		</tr>
		<tr>
			<td>Link:</td>
			<td><a href="<?php echo $news->get( 'link' ); ?>"><?php echo $news->get( 'link' ); ?></a></td>
		</tr>
		<tr>
			<td>Link Description:</td>
			<td><?php echo $news->get( 'link_description' ); ?></td>
		</tr>
	</table>

</div>
