<div id="privacy_policy">

	<h1>Privacy Policy</h1>
	
	<p>PRIVACY POLICY DISCLOSURE<br />
	(PROTECTION OF THE PRIVACY OF PERSONAL, NON-PUBLIC INFORMATION)</p>
	
	<p>THIS POLICY COVERS THE ACTIVITIES OF:<br />
	<?php echo strtoupper( $GLOBALS['advisor']->get( 'business_name' ) ); ?>,</p>
	
	<p><em>Respecting and protecting customer privacy is vital to our business. By explaining our Privacy Policy to you, we trust that you will better understand how we keep customer information private and secure while using it to serve you better. Keeping customer information secure is our top priority, and we are disclosing our policies to help you understand how we handle the personal information about you that we collect and disclose. This notice explains how you can limit the disclosing of personal information about you. The provisions of this notice will apply to former customers as well as current customers unless we state otherwise.</em></p>
	
	<h6>The Privacy Policy explains the Following:</h6>
	
	<ul>
		<li>Protecting the confidentiality of our customer information.</li>
		<li>Who is covered by the Privacy Policy.</li>
		<li>How we gather information.</li>
		<li>The types of information we share, why, and with whom.</li>
		<li>Opting Out - how to instruct us not to share certain information about you or not to contact you.</li>
	</ul>
	
	<h3>Protecting the Confidentiality of Customer Information:</h3>
	
	<p>We take our responsibility to protect the privacy and confidentiality of customer information very seriously. We maintain physical, electronic, and procedural safeguards that comply with federal standards to store and secure information about you from unauthorized access, alteration and destruction. Our control policies, for example, authorize access to customer information only by individuals who need access to do their work. From time to time, we enter into agreements with other companies to provide services to us or make products and services available to you. Under these agreements, the companies may receive information about you but they must safeguard this information, and they may not use it for any other purposes. It is important that you review each company's Privacy Policy to learn their specific policies and procedures as they may differ from our policies.</p>
	
	<h3>Who is Covered by the Privacy Policy:</h3>
	
	<p>We provide our Privacy Policy to customers when they conduct business with our company. If we change our privacy policies to permit us to share additional information we have about you, as described below, or to permit disclosures to additional types of parties, you will be notified in advance. This Privacy Policy applies to consumers who are current customers or former customers.</p>
	
	<h3>How We Gather Information:</h3>
	
	<p>As part of providing you with financial products or services, we may obtain information about you from the following sources:</p>
	
	<p>Applications, forms and other information that you provide us, whether in writing, in person, by telephone, electronically, or by any other means. This information may include your name, address, employment information, income, and credit references:</p> 
	
	<p>Your financial and family information. Due to the nature of our services, we may need to ask you for information about your family, financial situation and other sensitive data. We may collect this information through our own forms or through documentation you provide, such as tax returns, bank and investment statements, and credit report information. In the process of determining the services that we provide, we may make an inquiry for your credit report;</p>
	
	<p>Your transactions with us, our affiliates or others. This information may include your account balances, payment history and account usage;</p>
	
	<p>Consumer reporting agencies. This information may include account information and information about your credit worthiness;</p>
	
	<p>Public sources. This information may include real estate records, employment records, telephone numbers, etc. By providing non public personal information about your spouse, children or any other person relevant to the servicing of your account, you warrant to us that you have that person's express permission to do so and have shared our privacy policy with the person whose information you are about to disclose.</p>

	<h3>Information We Share:</h3>
	
	<p>We may disclosure information we have about you as permitted by law. We are required to or we may provide information about you to third-parties without your consent, as permitted by law, such as:</p>
	
	<ul>
		<li>Institutions of higher education and any other government or private entity involved in the filing for financial aid, admissions or other document related to higher education.</li>
		<li>To student loan lenders, guarantors and servicers for the pre-qualification, maintenance and service to your account.</li>
		<li>To members of your family, including your children, in perpetuity, any information in which such member has a bona fide interest. This would include all financial aid filings submitted and activities performed on behalf of the family member requesting the information.</li>
		<li>To regulatory authorities and law enforcement officials.</li>
		<li>To protect against or prevent actual or potential fraud, unauthorized transactions, claims, or other liability.</li>
		<li>To report account activity to credit bureaus.</li>
		<li>To consumer reporting agencies.</li>
		<li>To respond to a subpoena or court order, judicial process or regulatory authorities.</li>
		<li>In connection with a proposed or actual sale, merger, or transfer of all or a portion of a business or an operating unit, etc.</li>
	</ul>
	
	<p>In addition, we may provide information about you to our service providers to help us process your applications or service your accounts. Our service providers may include billing service providers, mail and telephone service companies, lenders, investors, etc.</p>
	
	<p>We may also provide information about you to our service providers to help us perform marketing services. This information provided to these service providers may include the categories of information described above under "How We Gather Information" limited to only that which we deem appropriate for these service providers to carry out their functions.</p>
	
	<p>We do not provide non public information about you to any company whose products and services are being marketed unless you authorize us to do so. These companies are not allowed to use this information for purposes beyond your specific authorization.</p>
	
	<h3>Opting Out</h3>
	
	<p>We also may share information about you within our corporate family of offices. We may share all of the categories of information we gather about you, including identification information (such as your name and address), credit reports (such as your credit history), application information (such as your income or credit references), your account transactions and experiences with us (such as your payment history), and information from other third parties (such as your employment history).</p>
	
	<p>By sharing this information we can better understand your financial needs. We can then send you notification of new products and special promotional offers that you may not otherwise know about. For example, if you originally obtained a mortgage from us, we would know that you are a homeowner and may be interested in hearing how a home equity loan may be a better option than an auto loan to finance the purchase of a new car. You may prohibit the sharing of application and third-party credit-related information within our company or any third-party company at any time. If you would like to limit disclosures of personal information about you as described in this notice, please contact us in writing at the following address or you may call us for specific information:</p>
	
	<p>Privacy Officer<br />
		<?php 
		
			echo $GLOBALS['advisor']->get( 'business_name' ) . '<br />';
			echo $GLOBALS['advisor']->get( 'address' ) . '<br />';
			echo $GLOBALS['advisor']->get( 'city' ) . ', ' . $GLOBALS['advisor']->get( 'state' ) . ' ' . $GLOBALS['advisor']->get( 'zip' ) . '<br />';
			echo $GLOBALS['advisor']->get( 'contact_email_address' );
		
		?>
	</p>
	
	<p><em><strong>Note for Family Accounts:</strong> Your opt-out choices will also apply to other individuals who are joint account holders; this will also apply to your children. This will only apply to your activities with the companies listed above.</em></p>
	
	<p><em>Please Note: Restricting the sharing of private non public information may restrict our ability to provide certain services to you. This may result in documents being filed late or not at all. Please understand that any losses you or your family receive as the result of limitations placed upon the sharing of your private non public information are not the responsibility of <?php echo $GLOBALS['advisor']->get( 'business_name' ); ?>. Such restrictions may invalidate guarantees of service, performance or warranty, expressed or implied.</em></p>
	
</div>