<h1>Newsletter Sign-Up</h1>
<p>Sign up for our newsletter by filling out the form.</p>
<style>
.signupframe {
  background: #ffffff;
  color: #226699;
  font-family: Arial, Helvetica, sans-serif;
}
table, tr, td, th, tbody { border: none; }
</style>
<form method="post" action="http://app.icontact.com/icp/signup.php" name="icpsignup" accept-charset="UTF-8" onsubmit="return verifyRequired();" >
<input type="hidden" name="redirect" value="http://www.icontact.com/www/signup/thanks.html" />
<input type="hidden" name="errorredirect" value="http://www.icontact.com/www/signup/error.html" />
<script type="text/javascript">
function verifyRequired() {
  if (document.icpsignup["fields_email"].value == "") {
    document.icpsignup["fields_email"].focus();
    alert("The Email field is required.");
    return false;
  }
  if (document.icpsignup["fields_fname"].value == "") {
    document.icpsignup["fields_fname"].focus();
    alert("The First Name field is required.");
    return false;
  }
  if (document.icpsignup["fields_lname"].value == "") {
    document.icpsignup["fields_lname"].focus();
    alert("The Last Name field is required.");
    return false;
  }
  if (document.icpsignup["fields_zip"].value == "") {
    document.icpsignup["fields_zip"].focus();
    alert("The Zip field is required.");
    return false;
  }


return true;
}
</script>
<div id="SignUp">
<table width="260" class="signupframe" border="0" cellspacing="0" cellpadding="5">
    <tr>
      <td valign=top align=right>
        *Email
      </td>
      <td align=left>
        <input type=text name="fields_email" />
      </td>
    </tr>
      <td valign=top align=right>
        *First Name
      </td>
      <td align=left>
        <input type=text name="fields_fname" />
      </td>
    </tr>
      <td valign=top align=right>
       *Last Name
      </td>
      <td align=left>
        <input type=text name="fields_lname" />
      </td>
    </tr>
      <td valign=top align=right>
        *Zip
      </td>
      <td align=left>
        <input type="text" name="fields_zip" />
      </td>
    </tr>
    <input type="hidden" name="listid" value="68385" />
    <input type="hidden" name="specialid:68385" value="EIIN" />

    <input type="hidden" name="clientid" value="270015" />
    <input type="hidden" name="formid" value="5223" />
    <input type="hidden" name="reallistid" value="1" />
    <input type="hidden" name="doubleopt" value="0" />
    <tr>
      <td>&nbsp;</td>
      <td>* = Required Field</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" name="Submit" value="Submit" /></td>
    </tr>
    </table>
</div>
</form>