<html>
	<head>

        <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL . Legato_Compressor::get( 'CSS_Common' ); ?>" />
        
	</head>
	<body>
		<div id="print">
			<h1>Workshop Registrants (<?php echo $num_registrants; ?>)</h1>

			<?php

				if ( count( $registrants ) == 0 )
				{

					echo '<p>No registrants have signed up for this workshop yet.</p>';

				}
				else
				{

					?>

					<table cellspacing="0">

						<tr>
							<th>Name</th>
							<th>Email Address</th>
							<th>Phone Number</th>
							<th>Guests</th>
							<th>Grades</th>
						</tr>

						<?php

							// Loop through each workshop.
							$i = 0;
							foreach ( $registrants as $registrant_id => $registrant )
							{

								// Which row type?
								if ( $i == 0 )
									echo '<tr class="row1" id="registrant'. $registrant_id .'">';
								else
									echo '<tr class="row2" id="registrant'. $registrant_id .'">';

								?>

								<td><?php echo $registrant->get( 'first_name' ) . ' ' . $registrant->get( 'last_name' ); ?></td>
								<td><?php echo $registrant->get( 'email_address' ); ?></td>
								<td><?php echo $registrant->get( 'phone_number' ); ?></td>
								<td>
								
									<?php
									
										$guests = $registrant->get( 'guests' );
										if ( !is_array( $guests ) ) $guests = array( $guests );
										
			                            $n = 0;
						  				foreach( $guests as $guest )
						  				{
						  					
											if ( $n != 0 ) echo '<br />';
											echo $guest;
											
											$n++;
											
						  				}
						  				
									?>
									
								</td>
								<td>
								
									<?php
									
						  				$grades = $registrant->get( 'grades' );
						  				if ( !is_array( $grades ) ) $grades = array( $grades );
						  				
										$n = 0;
						  				foreach( $grades as $grade )
						  				{
						  					
											if      ( $grade == 'grade1' ) echo 'Grade 1 <br />';
											else if ( $grade == 'grade2' ) echo 'Grade 2 <br />';
											else if ( $grade == 'grade3' ) echo 'Grade 3 <br />';
											else if ( $grade == 'grade4' ) echo 'Grade 4 <br />';
											else if ( $grade == 'grade5' ) echo 'Grade 5 <br />';
											else if ( $grade == 'grade6' ) echo 'Grade 6 <br />';
											else if ( $grade == 'grade7' ) echo 'Grade 7 <br />';
											else if ( $grade == 'grade8' ) echo 'Grade 8 <br />';
											else if ( $grade == 'grade9' ) echo 'Grade 9 <br />';
											else if ( $grade == 'grade10' ) echo 'Grade 10 <br />';
											else if ( $grade == 'grade11' ) echo 'Grade 11 <br />';
											else if ( $grade == 'grade12' ) echo 'Grade 12 <br />';
											else if ( $grade == 'grade13' ) echo 'Freshman in College <br />';
											else if ( $grade == 'grade14' ) echo 'Sophomore in College <br />';
											else if ( $grade == 'grade15' ) echo 'Junior in College <br />';
											else if ( $grade == 'grade16' ) echo 'Senior in College <br />';
											
											
											
						  				}
						  				
									?>
									
								</td>

								<?php

								echo '</tr>';

								$i++;

								// Wrap.
								if ( $i == 2 )
									$i = 0;

							}

						?>

					</table>

					<?php

				}

			?>
		</div>
	</body>
</html>