<h1>View Workshop Registrant</h1>

<ul class="commands">
 
  <li><a href="<?php echo SITE_URL . '/admin/workshops/view/' . $registrant->get( 'workshop_id' ); ?>">Back to Workshop</a></li>
	
</ul>

<table cellspacing="0" class="information_table">	
	<tr>
		<td>Name:</td>
		<td><?php echo $registrant->get( 'first_name' ) . ' ' . $registrant->get( 'last_name' ); ?></td>
	</tr>
	<tr>
		<td>Email Address:</td>
		<td><?php echo $registrant->get( 'email_address' ); ?></td>
	</tr>
	<tr>
		<td>Phone Number:</td>
		<td><?php echo $registrant->get( 'phone_number' ); ?></td>
	</tr>
	<tr>
		<td>Guests:</td>
		<td>
		
			<?php
			
				$guests = $registrant->get( 'guests' );
				if ( !is_array( $guests ) ) $guests = array( $guests );
				
                $n = 0;
  				foreach( $guests as $guest )
  				{
  					
					if ( $n != 0 ) echo '<br />';
					echo $guest;
					
					$n++;
					
  				}
  				
			?>
		
		</td>
	</tr>
	<tr>
		<td>Grades:</td>
		<td>
		
			<?php
									
  				$grades = $registrant->get( 'grades' );
  				if ( !is_array( $grades ) ) $grades = array( $grades );
  				
				$n = 0;
  				foreach( $grades as $grade )
  				{
  					
					if      ( $grade == 'grade1' ) echo 'Grade 1 <br />';
					else if ( $grade == 'grade2' ) echo 'Grade 2 <br />';
					else if ( $grade == 'grade3' ) echo 'Grade 3 <br />';
					else if ( $grade == 'grade4' ) echo 'Grade 4 <br />';
					else if ( $grade == 'grade5' ) echo 'Grade 5 <br />';
					else if ( $grade == 'grade6' ) echo 'Grade 6 <br />';
					else if ( $grade == 'grade7' ) echo 'Grade 7 <br />';
					else if ( $grade == 'grade8' ) echo 'Grade 8 <br />';
					else if ( $grade == 'grade9' ) echo 'Grade 9 <br />';
					else if ( $grade == 'grade10' ) echo 'Grade 10 <br />';
					else if ( $grade == 'grade11' ) echo 'Grade 11 <br />';
					else if ( $grade == 'grade12' ) echo 'Grade 12 <br />';
					else if ( $grade == 'grade13' ) echo 'Freshman in College <br />';
					else if ( $grade == 'grade14' ) echo 'Sophomore in College <br />';
					else if ( $grade == 'grade15' ) echo 'Junior in College <br />';
					else if ( $grade == 'grade16' ) echo 'Senior in College <br />';
					
					
					
  				}
  				
			?>
		
		</td>
	</tr>
</table>