<div id="member_best_college_decision">

	<h1>Make the Best College Decision</h1>
	
	<h3>Middle School</h3>
	
	<p>Take a quick quiz and find out in which careers that people most like you have found 
	success.  Explore campuses and careers via data and video.  Plan your High School courses 
	and start on a college portfolio.  Most importantly lets start working on your focus in 
	life.  This feature requires JavaScript to be enabled.</p>
	
	<p><a href="<?php echo SITE_URL . '/member/testgear_full/middle_school'; ?>">Click here to access this section.</a></p>
	
	<h3>High School</h3>
	
	<p>Take any or all of the 4 most comprehensive tests designed to align students with the 
	most fitting careers and schools. This includes an analysis of over 1200 careers and 
	6,000 schools. This feature requires JavaScript to be enabled.</p>
	
	<p><a href="<?php echo SITE_URL . '/member/testgear_full/high_school'; ?>">Click here to access this section.</a></p>
		
	<h3>Standardized Test Tutoring</h3>
	
	<p>Each section, PSAT, SAT, ACT includes</p>
	
	<ul>
	 
		<li>A 30-minute online proficiency test</li>
		<li>Over 50 hours of study specifically designed to maximize your score</li>
		<li>26 interactive lessons covering over 50 test taking strategies</li>
		<li>Over 35 interactive tutorials covering 160 content-specific skills</li>
		<li>Progress reports</li>
		<li>3000 + word vocabulary lab</li>
		<li>2 full-length and 16 practice tests</li>
		<li>Immediate scoring</li>
		
	</ul>
	
	<p><a href="<?php echo SITE_URL . '/member/testgear_full/testing'; ?>">Click here to access this section.</a></p>
	
</div>