<div id="member_high_school_timeline">

	<div id="sub_menu">
	
		<ul>
		
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_sophomore'; ?>">Sophomore Year</a></li>
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_junior'; ?>">Junior Year</a></li>
			<li class="last"><a href="<?php echo SITE_URL . '/member/hs_timeline_senior'; ?>">Senior Year</a></li>
		
		</ul>
		
	</div>

	<h1>High School Timeline</h1>
	
	<h3>Senior</h3>
	
	<p>Throughout your senior year, you will need to keep track of a series of steps, including:</p>
	
	<ul>
	
		<li>Registering for the appropriate tests: Scholastic Assessment Test (SAT), American College Test (ACT);</li> 
		<li>Submitting your applications for admission;</li>
		<li>Comparing acceptance offers from schools;</li>
		<li>finally, after you've accepted a school's final offer, having your high school send your final transcripts to that school.</li>
		<li>Don't forget that the process of applying for financial assistance to help you pay the costs of attending your school of choice is separate.</li>
	
	</ul>
	
	<h6>September</h6>
	
	<ul>
	
		<li>Meet with your guidance counselor as soon as you can to discuss your plans. Make sure you are on track to graduate and check your transcripts to make sure you have all the credits you need to get into the school(s) of your choice.</li>
		<li>Make sure that schools you've identified still meet your requirements. Change your list, if necessary.</li>
		<li>Contact those schools that have made your final cut to request information and applications for admission. Ask about admission requirements, application deadlines and any required fees, and financial aid. Ask if these schools will need official copies of your transcripts at the time you send in your application.</li>
		<li>Register for the October/November SAT, ACT, and SAT Subject Tests.</li>
		<li>If you are planning to apply for Early Action or Early Decision, you need to prepare and submit those applications now. &nbsp;Make sure you allow enough time to prepare any essays you will need to include in your application or to meet any audition or portfolio requirements.</li>
		<li>As you prepare these early applications, be sure to give any recommendation forms to appropriate teachers and counselors with stamped, college-addressed envelopes to be included with your application. Make sure your portions of the forms are filled out completely and accurately. Also, don't forget to request that your high school send your official transcripts to the school(s) to which you are applying. Also, schedule any required school interviews.</li>
		<li>Send for applications</li>
		<li>Begin a file for each college</li>
		<li>Photocopy applications and begin to fill out draft(s)</li>
		<li>Be sure you are taking the correct courses for the college(s) of your choice (if you have any questions, discuss with your counselor)</li>
		<li>Attend College Night for Seniors &amp; Their Parents at JS</li>
		<li>Get off to a good start academically</li>
	
	</ul>
	
	<h6>October</h6>
	
	<ul>
	
		<li>Take the SAT I or ACT</li>
		<li>For letters of recommendation, choose which teachers you will ask.</li>
		<li>Work on college essays - have an English teacher read your essay for grammar and content</li>
		<li>Check out college fairs</li>
		<li>Plan college visits</li>
		<li>Be sure all colleges you've applied to receive your official SAT and/or ACT score report (order additional score reports if you did not do this when you registered to take the exam)</li>
	
	</ul>
	
	<h6>November</h6>
	
	<ul>
	
		<li>Take the SAT I or SAT II</li>
		<li>Remember to get a certificate of mailing at the Post Office for all your applications</li>
		<li>Make copies of everything you mail to everyone! That includes all applications, financial aid info., etc.</li>
		<li>Most Early Action and Early Decision deadlines are this month</li>
		<li>Think about recommendation letters, and let your teachers and your counselor know what activities, etc., you have been involved in</li>
		<li>Watch for deadlines!</li>
	
	</ul>
	
	<h6>December</h6>
	
	<ul>
	
		<li>Last time to take the SAT I, ACT, or SAT II for</li>
		<li>Ask for recommendations politely - remember stamped, addressed envelopes</li>
		<li>Attend Financial Aid Night for Seniors</li>
		<li>Read any financial aid literature sent by the colleges you applied to</li>
		<li>Check deadlines for private school applications - most have deadlines ranging from December 15 to February 15 - be sure you've included everything (check or fee waiver, optional photo, essay, other supplementary information)</li>
	
	</ul>
	
	<h6>January</h6>
	
	<ul>
	
		<li>Give mid-year reports to your counselor to fill out</li>
		<li>Study hard!</li>
	
	</ul>
	
	<h6>February</h6>
	
	<ul>
	
		<li>Check that colleges have received all materials: application, test scores (sent by ETS and ACT), financial aid forms</li>
		<li>Carefully read all information from colleges</li>
		<li>Verify with your counselor that mid-year reports have been sent</li>
		<li>Notify colleges of any new information, including honors or accomplishments</li>
		<li>Men 18 years and older must register for the draft to receive federal financial aid; inquire at your local Post Office about how to receive proof of registration</li>
		<li>Continue to check for scholarships</li>
	
	</ul>
	
	<h6>March</h6>
	
	<ul>
	
		<li>If colleges request additional information, send it to them immediately</li>
		<li>Rank your top colleges by academic programs, location, etc. If you are accepted everywhere you applied, it helps in decision-making</li> 
	
	</ul>
	
	<h6>April</h6>
	
	<ul>
	
		<li>All colleges should respond to your application by this month (deadline to inform them of your decision is May 1)</li>
		<li>Decide where you wish to go</li>
		<li>Financial aid offers will begin to arrive</li>
		<li>If you are "wait-listed" write a letter of sincere interest and send any appeals/supporting material that you can</li>
		<li>FAFSA SAR (Student Aid Report) should arrive - look in the top right hand corner for your EFC (Expected Family Contribution)</li>
		<li>If possible, visit colleges to which you were accepted on Open House or Admitted Students day(s) - this will help in your final decision</li>
		<li>Make your final decision - send deposit and SIR (Statement of Intent to Register) by May 1</li>
	
	</ul>
	
	<h6>May</h6>
	
	<ul>
	
		<li>Congratulate yourself! You did it!</li>
		<li>Tell your counselor where you have decided to enroll</li>
		<li>Pay careful attention to deadlines concerning housing deposits, etc.</li>
		<li>Fill out housing forms</li>
		<li>Write "Thanks but no thanks" letters to colleges you will not attend</li>
		<li>Enjoy your graduation and begin your college journey!</li>
	
	</ul>
	
	<h6>June</h6>
	
	<ul>
	
		<li>Make sure you have responded to all requests from your college</li> 
	
	</ul>
	
</div>