<div id="member_high_school_timeline">

	<div id="sub_menu">
	
		<ul>
			
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_sophomore'; ?>">Sophomore Year</a></li>
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_junior'; ?>">Junior Year</a></li>
			<li class="last"><a href="<?php echo SITE_URL . '/member/hs_timeline_senior'; ?>">Senior Year</a></li>
		
		</ul>
		
	</div>

	<h1>High School Timeline</h1>
	
	<h3>Sophomore</h3>
	
	<h6>September</h6>
	
	<ul>
	
		<li>Ask your counselor and investigate if the PSAT test might be appropriate for you</li>
		<li>Start a calendar of important dates and deadlines</li>
		<li>Develop your time management skills - prioritizing your activities is critical for academic success.</li>
		
	</ul>
	
	<h6>October</h6>
	
	<ul>
	
		<li>Signup, if you have not already done so, for co-curricular activities that interests you. The level of involvement and accomplishment is most important, not the number of activities.</li>
		<li>Keep a record of your co-curricular involvement, volunteer work, and employment (all year).</li>
	
	</ul>
	
	<h6>November</h6>
	
	<ul>
	
		<li>Make sure you are "on top" of your academic work. If necessary, meet with your teacher for additional help.</li>
		<li>Save your best work in academic courses and the arts for your academic portfolio (all year).</li>
	
	</ul>
	
	<h6>December</h6>
	
	<ul>
	
		<li>Receive results of the PSAT. Read materials sent with your score report. Consult your guidance counselor to explore ways to improve on future standardized tests and courses to discuss which may be required or beneficial for your post-high school plans.</li>
	
	</ul>
	
	<h6>January</h6>
	
	<ul>
	
		<li>Keep Studying!</li>
		<li>Volunteer - a great way to identify your interests and to develop skills</li>
		<li>Find out about college firsthand from college friends who are home for the holidays.</li>

	</ul>
	
	<h6>April</h6>
	
	<ul>
	
		<li>When selecting junior year courses, be sure to continue to challenge yourself academically, but realistically.</li>
		<li>Register for the May/June SAT II: Subject Tests. These are one-hour exams testing you on academic subjects that you have already completed. (ex. World History, Biology, foreign languages, Math IC)</li>
		<li>Look into summer jobs or apply for special academic or enrichment programs.</li>
	
	</ul>
	
	<h6>May</h6>

	<ul>

		<li>Take the MCAS exams.</li>
		<li>Take the Advanced Placement and SAT II exams if appropriate.</li>
		<li>Plan now for wise use of your summer. Consider taking a summer course or participating in a special program at a local college or community college, working or volunteering.</li>

	</ul>

	<h6>June</h6>

	<ul>

		<li>Start a summer reading list. Ask your teachers to recommend books.</li>
		<li>Take the SAT II exams if appropriate.</li>
		<li>Finalize your summer plans.</li>

	</ul>

	<h6>July &amp; August</h6>
	
	<ul>
	
		<li>Make your summer productive. Continue reading to increase your vocabulary.</li>
	
	</ul>
	
</div>