<div id="<?php echo $page; ?>">
	
	<h1>Imperative Financial Aid Information</h1>
		
	<ol>
		
		<li>
		
			<h3>The no payments are due until after you graduate trap</h3>			
			<p>At its inception this thought process was a good one.  How can a student afford to pay back
			his or her student loan when attending college full time?  Over the years the ramifications have
			morphed dramatically, especially if you have borrowed from a private student loan company.  A
			difficult financial concept to explain is what is called capitalization.  Capitalization is the
			concept that if you don't make at least the interest payments on a loan the unpaid interest
			amount will be added to the principal amount and interest now accrues on the original principal
			plus the interest that you didn't pay.  For example, lets assume that you borrowed $100 and the
			interest rate is 6% so at the end of the year you owe $6 in interest.  If you pay the interest at
			the end of the next year you will owe another $6 in interest.  If however you don't make the
			interest payment the new principal balance is $106 and thus your new payment is $6.36.  Not a
			big deal, 36 cents right?  But what if the interest capitalized daily, (as is in the fine print
			of some student lenders documents.), and the principal balance is $20,000, and you make no
			payments until after you graduate.  Well the bad news is that at 8% interest, the $20,000 that
			you borrowed, now is $27,529!</p>
		
		</li>
		<li>
		
			<h3>Sorry you missed the deadline, all of the grant money and loan money is committed</h3>
			
			<p>This may or may not be true.  What is important is to KNOW YOUR SCHOOL AND STATE DEADLINES.
			These deadlines are often not the same.  The school will usually have several deadlines.  The
			first is for early admission, (see Number 4 below.).  The second is what is called a priority
			deadline.  This deadline is usually used by the schools to determine who should get the schools
			funds.  The third is your state deadline which is based on the state in which you reside, the
			purpose is so that the state knows to whom to give its grant money.  The final deadline is the
			Federal deadline which is June 30th of any give year.  KNOW YOUR DEADLINES, most often if you
			miss the deadline you are out of luck, not always but most time.  One other point, don't feel
			too bad if you made a mistake, changing the error is quite easy, call your financial aid office
			and someone there will walk you through it.</p>
			
		</li>
		<li>
		
			<h3>Sorry, your error delayed the process so long that you missed the deadline</h3>
			
			<p>First, when completing either the Fafsa or CSS Profile, never leave any numerical input
			line blank, always but in a 0 if you have nothing to report.  If you use our database fields
			and if we file the forms for you we will audit the forms for you before submitting.  The your
			error your problem scenario is quite valid.  Several ex-executives of the FAFSA processing
			department have stated that over 65% of submitted forms have errors that were caught.  No
			one knows how many times someone committed an error that was overlooked and dramatically
			reduced that student's financial aid package.</p>
			
		</li>
		<li>
		
			<h3>We charge less so we give less financial aid</h3>
			
			<p>It is important to understand that around the turn of the century many schools increased
			their fees dramatically.  What the schools learned was that if they kept their prices low
			and their financial aid rewards low they obtained less applicants.  When they increased their
			fees by roughly 50% and gave that money back in financial aid their applications more than
			doubled.  Additionally, there is always a subset of families who do not ask for aid, they
			are a gold mine for colleges.  Ask us and we can get for you the information on how much
			aid the average student received in both gift aid and loan aid.  A most recent practice is
			that some colleges now state that they "meet 100%" of need.  Any college can state that by
			filling up need with loans, which is exactly what many of these schools are doing.  To be
			fair another group of well endowed colleges are offering a free education based on income,
			they are truly letting your child go to school for free.  Do not think that the competition
			for these positions is not intense.  It is not easy to obtain acceptance to these school,
			but if you can this is the best financial package in college.</p>
			
		</li>
		<li>
		
			<h3>Early decisions are a school's marketing dream</h3>
			
			<p>Early decision sounds great.  The student applies early and is accepted, thus no more
			"sweating it out".  There are two caveats to this practice that you need to be aware of.
			First, if accepted under early acceptance you are required to attend this school.  As an
			analogy this process is similar to ordering a car before it has been built, you guarantee
			to purchase the car when it is delivered.  The problem is in both scenarios there is no
			incentive for the seller of services to help you out, you are purchasing the product before
			the general public has even seen it.  In the school's mind you are so committed to them
			there is virtually no need to help you out financially...and in most cases they will not.</p>
			
		</li>
		<li>
		
			<h3>Extra Fees Trap</h3>
			
			<p>It is not uncommon for a school to add fees to your bills after you have agreed to attend
			the school.  When you receive your original awards letter it easily might state that the
			bill for the next year is X, your financial aid award package is Y, and then say something
			like, plus miscellaneous fees.  A recent article from the New York Times showed how the
			"miscellaneous fees" can add up to over $4,000.  One client at a state school, none the
			less, is being charged $1,200 a year for health insurance, even though he is covered under
			his parent's policy.  Athletic, library, etc, fees are all very common and not disclosed
			until the decision to go elsewhere is too late.  As one parent stated, "I have never been
			in a situation where I agreed to purchase a product at a particular price, then when I went
			to obtain the product the price had dramatically jumped and I had no choice but to pay the
			higher price."</p>
			
		</li>
		<li>
		
			<h3>How to look less wealthy</h3>
			
			<p>Now is not the time to show great pride in the value of your assets or your anticipated
			income.  Talk to us about this, there are many ways that we can do with your assets which
			can save you thousands of dollars in financial aid.  First we will get as much money as
			possible out of the students' name.  Secondly, if prudent, we can move your assets into other
			asset categories that will lower your family's cost of college.  There are legal ways to
			do this and some not so legal, please do not do anything without contacting us.  The
			penalties for making the wrong move include several penalties and jail time, take this
			seriously, by statute 30% of financial aid applications are audited.  As a matter of
			perspective, less than 2% of tax returns are audited by the Internal Revenue Service.</p>
			
		</li>
		<li>
		
			<h3>Increasing your debt will not help you obtain financial aid</h3>
			
			<p>For whatever the reason is, a group of people think that increasing debt will minimize
			cash flow and asset base and thus increase financial aid.  This could not be further from
			the truth.  In all but roughly 200 of the most elite colleges around the country, (most
			in the North East), parental assets have little to do with the financial aid formula.
			More importantly the debt secured by those assets is not reviewed.  What is looked at is
			parental and student income, size of family, age of the parents, and the number of family
			members attending college in that year.  If the student is attending one of the 200 schools
			mentioned above the story quickly changes.  At this point home equity in the families
			real estate holdings are reviewed as well as any type of non-retirement account.  In
			either situation please contact us so that we can assist you through this time, it is what
			we specialize in, and we can save you a significant amount of funds.</p>
			
		</li>
		<li>
		
			<h3>The financial aid office will not stop you from paying more than what you can afford</h3>
			
			<p>Sorry but this is true.  One of the problems with paying for college is there is no
			cost variance based on your expected income post-graduation.  For example if two students
			go to the same college, one a pre-medical major, the other a social science major, the
			cost is the same.  The pain is not too bad at local public schools, unfortunately it is not
			uncommon to see students borrowing over $40,000 a year to attend their school of choice
			only to graduate and make less than $30,000 a year.  A recent study evidenced that the
			average education major in the state of Maine could not teach post graduation because
			their student loan debts were too high to live off of a teacher's salary.  Please use our
			career assessment piece of this website, when you do so it will assist you in making
			sound expense and income decisions in relation to your major.  To compound this fact many
			lenders will send or have sent you applications for loans that the schools are not aware
			of, please take the credit counseling course on this website to further assist you in your
			student loan decision making process.</p>
			
		</li>
		<li>
		
			<h3>Colleges LOVE when you get outside, (as in not through the school), scholarships</h3>
			
			<p>To understand this section, it is important to understand the financial aid formulas.
			In a nutshell there is the overall cost of attending a particular school.  How to pay
			that cost is broken down into two sections, one is called your Expected Family
			Contribution, this is the amount that the family is expected to pay before the family
			obtains any grants or federally backed student loans.  When you obtain an outside
			scholarship, parents tend to think that this will lower the amount that the family is
			expected to pay.  The federal regulations however are written such that an outside
			scholarship reduces the amount of grant and loan money you will receive, the amount that
			your family is to contribute will not change.  That being said, if your family was not
			expecting any financial aid, go for as many scholarships as you can as your cost of
			attendance will decrease.</p>
			
		</li>
		<li>
		
			<h3>By default colleges never "Negotiate"</h3>
			
			<p>Always remember the old adage, Honey catches more flies than vinegar.  This is
			especially true in the financial aid process.  When you receive your financial aid award
			notice review it carefully, 1 out of 10 families find this a good day.  Typically, students
			apply to several colleges and the temptation to pick up the phone and call the school of
			choice and ask why they did not offer you as much as another school is great, do not fall
			into this trap.  First schools are not fond of the terms, negotiate, bargain, review and
			the like.  What schools are accustomed to however is what is called an appeal process.  
			You might be thinking that it is the same thing, it is, just a different attitude, the
			school wants you to approach them in a subservient manner, do you have to?, no, but if
			you want more financial aid you have to.  For you to appeal an awards package you have
			to have a legitimate reason.  Call us and we can help you determine if you have a legitimate
			appeal, in most cases the answer is no, however there are certainly times when familial
			circumstances that do not show up on the financial aid forms have obtained families a
			larger award package.</p>
			
		</li>
		<li>
		
			<h3>Senior Year is always more expensive than Freshman Year</h3>
			
			<p>Lets do the simple math.  The cost of college increases on average 6% a year. So if
			your freshmen year would cost you $100 your senior year would cost you $126 dollars, more
			than a 25% increase.  To compound the problem any merit-based aid that you receive is
			typically the same amount per year.  It is exceedingly rare that the merit-based grants
			grow at the same percentage as does the cost of the school.  This scenario is so rare in
			fact that we have never heard of it other than in a case of a "full ride" where the student
			goes to school at no cost to the student.</p>
			
		</li>
		
	</ol>

</div>