<div id="member_letters_of_recommendation">

	<h1>Letters of Recommendation</h1>
	
	<p>Usually, several letters of recommendation are required when applying for admission to a school. It is recommended that at least one of these letters come from your guidance counselor and that at least one come from a teacher/educator in your high school.</p>
	
	<h3>Key Points for Securing a Letter of Recommendation</h3>
	
	<ol>
	
		<li>Develop a relationship with the educator/faculty member writing the letter of recommendation over the longest   period of time possible. (S)he should be aware of your strengths, character, and communication skills.</li>
		<li>
			<p>Determine the best person to write the letter. Ask that person to write the letter at least 6-8 weeks in advance of the letter's due date. Take into account the educator's schedule/time of year when approaching him/her. No one writing a letter of recommendation wants to feel rushed, and any student applying to undergraduate school does not want a rushed letter of recommendation in their application file. In addition, clearly identify your intent  (business school, nursing school, four year liberal arts college, etc.) to the recommender.</p>
			<em>Note:  Never beg or try to force anyone to write a letter of recommendation for you.  If someone needs to be begged, (s)he is unlikely to write the kind of letter you want in your file.</em>
		</li>
		<li>Create a list of your personal and academic achievements that can be given to the recommender and used when writing the letter. Include specific examples of success and overcoming of hurdles in high school or at work. A recommender may be able to explain a poor score on your transcript that you did not have the opportunity to explain in the essay portion of your application. If the educator recommended taking a difficult class with a hard teacher, this may help explain a poor grade on a transcript.</li>
		<li>Set up a contact system between the recommender and yourself using e-mail addresses or telephone numbers in case any clarification re: the letter of recommendation is needed.  Also, identify the date your application will be turned in so that the recommender can send the letter of recommendation near the same time.</li>
		<li>Give your recommender's telephone number on your final application in case the academic reviewer has any questions. Be sure about how many copies are required and exactly where the finished letter should be sent. Provide an addressed and pre-stamped envelope with each letter request. Provide the full name, title, and complete mailing address of the person to whom the letter is to be written.</li>
		<li>Do NOT use references from relatives, family members or people that don't know you well.</li>
		<li>Waive your right to review the letters whenever possible. A sealed letter will have more merit than a letter you have seen during a review process.</li>
		<li>If you are asked to write a rough draft of the letter of recommendation, graciously accept.</li>
	
	</ol>
	
	<h6>Click here to see a <a href="<?php echo SITE_URL; ?>/member/sample_recommendation_letter">sample letter</a> of recommendation.</h6>
	
</div>