<div id="<?php echo $page; ?>">

	<h1>Appealing the Offered Aid Package</h1>

	<ol>

		<li>

			<h3>Seeing the process from the Colleges’ point of view</h3>

			<p>We spent the time getting advice on this subject from many student financial aid professionals, those that sit behind the desks that send out the financial aid packages.  Additionally, we received advice from many individuals working in the Bursar’s office.  The Bursar’s office at a college is the equivalent of the accounting department in most organizations.</p>

			<p>We will start by looking at what goes on behind the scenes.  Colleges are encouraged by their peers to start with the end in mind.  In other words have a written policy describing the parameters as to how financial aid will be distributed. This usually begins by determining the total amount of aid available outside of the standard government grants and insured student loans.  There are wild cards that do come into play, for example, first generation students are usually given more consideration, as are those whose parent or parents attended the institution, and especially to those whose families have donated funds to the institution.</p>

			<p>Secondly, rarely does a college attempt to low ball a student hoping for no appeal.  The issuance of financial aid is always done under what is called the Common Manual.  The Common Manual is in essence the Bible of student loan lending.  The Manual is over 700 pages of IRS style prose.  However, as opposed to the IRS process which is mostly Black and White when applied to 2 similar situations, all financial aid is metered out under the umbrella of Professional Judgment.  Professional Judgment allows the financial aid officer to deviate from the standard if under their “professional judgment” the student is due more or less than the standard.</p>

			<p>Next, understand that negotiating is considered well beneath what is acceptable in higher education.  “Negotiating is what you do when you buy a car, not when you are attempting to attain further education.”  Colleges detest, repeat detest when parents or students put them into a battle over pricing.</p>

			<p>Finally for this section, student retention is a large concern in the college arena.  The industry assumes that for each child that does not come back for a following year, the college losses in the range of $30,000 - $50,000.  Multiply that by 100 students and you are talking millions.  Thus if one comes across as a negotiator it is not uncommon for the financial aid office to become silent.</p>

			<p>Keep in mind that a standard college practice is to track statistical results based on the parameters of those that appeal.  What that means is that if historically a student with GPA of X, class standing as of Y, and ACT / SAT scores of Z and has wanted to negotiate, typically leaves after 3 semesters, then that category of student will not be viewed very highly when awards are appealed.</p>

		</li>

		<li>

			<h3>Practices that are not considered acceptable</h3>

			<p>First stretching the truth or even lying will always come back to hurt you.  Keep in mind that the Department of Education requires that each financial aid officer audit a specific amount of financial aid requests, in some cases over 30% of applicants.  If you are found to have intentionally lied to obtain aid, you will be prosecuted for fraud, and suffer large fines and potential jail time.  The more out of the norm your claim, the greater the chances of a mandated audit.</p>

			<p>State the facts clearly.  Sometimes bad things happen to good people.  Now is not the time to have pride.  If your spouse left the family, if you lost your job, had any out of the ordinary life event, feel free to discuss the situation with the financial aid office, this is the perfect situation for Professional Judgment to come into play.  As the old saying goes, you can have ego or cash which do you want?</p>

			<p>The parent and student should mutually apply for the appeal.  Using us, your account, attorney, or other professional sends two negative messages.  First is shows the college that you can afford to pay for someone else to appeal, so why the appeal, why not just put those funds toward the college bill?  Secondly, it shows a sense of animosity instantly putting the financial aid officer on the defensive, and then he or she will typically handle your case purely “by the book” to avoid any possible negative consequences.</p>

			<p>Do not expect the college to pay for what you are not.  A handful of colleges out of thousands offering full grants and the like, odds are if you are reading this your child is not.  There is only so much money available for grants, period.  Stories about, “our second home isn't selling fast enough”, “our other child went to college x and we paid for all of that”, “our daughter’s wedding cost x” and the like, simply are not acceptable.  The basic premise is that it is between the parents and student to fund college, grants and the like are considered bonuses, not entitlement funds.</p>

			<p>Do not try to pull tricks, we have heard of scam divorces, bankruptcy filing and the like.  We highly advise against this, facing a United States Attorney in a courtroom is not a pleasant experience.</p>

		</li>

		<li>

			<h3>What is encouraged and considered fair to all involved parties</h3>

			<p>The basics are paramount.  On a monthly basis you receive from us updates to stay on track for college, use those updates.  Know your deadlines and adhere to each and every one, there is never a penalty for filing early; doing so shows that you are serious.  Keep copies of everything that you send, keep notes on ever phone conversation with the school, including name, date, and time of the call.  Complete the FASFA, according to a very recent survey, a full 60% of students did not obtain financial aid because the failed to complete the FASFA.  If your selected college is in the great minority of colleges that require additional financial aid forms, complete and submit them on time.  In essence show the financial aid officer that you care, are punctual and take this process seriously, it is his or her chosen profession by the way.</p>

			<p>Secondly, keep in mind that as a whole the financial aid officers are not near the top of the prestige totem pole in academia.  Having met with thousands of financial aid officers over the years, the easiest way to find the financial aid office on most campuses is to find the oldest building, and then head to the basement or similar.  Additionally, 9 out of 10 financial aid officers work incredibly long hours, are understaffed, and are underpaid.</p>

			<p>The vast majority of appeals are over the amount of the college’s discretionary grants.  Rarely if ever does one appeal over loans or work study as those are driven by simple formulas.  The financial aid office is budgeted a gross dollar amount for each semester, it is up to the financial aid office to determine who gets what.  (Trite)  Understanding the mind set of whom and what you are dealing with will allow you to prepare an appropriate response.</p>

			<p>Next, financial aid is based on the family’s financial situation in the year prior to applying.  This if the student will attend in the fall of year x, the financial aid package is based on the financial situation of the family in the year x-1 which ended 9 months prior to attendance.  The point is that many situations can change over 9 months; do not hesitate to contact the college in relation to financial instability that occurred during that period.</p>

			<p>Filing an appeal is similar to filing for a government grant.  One of the largest problems is a basic one, appealing without knowing the parameters.  Pick up the phone, call the financial aid office and request information as to the process, again showing that you care.  As important is timing.  If the college, for example, has $100 to give out and $75 has already been offered, the total pool left is $25.  If however you would have been the first appeal letter the pool would have been the original amount.</p>

			<p>When you file for an appeal you have to have a reason.  Before you take this step, go to the college search section under the College Major and Career Assessment section of this site, look up the college and look at their standard applicants versus standard aid package.  If what you received is better than the standard you might want to not appeal except for extreme scenarios.  If you received the standard package make sure that the appeal is a quantifiable event or events.  If you received a substandard appeal, you can base your appeal on that fact.</p>

			<p>Once you have been able to isolate a specific event or events, or why your family has circumstances out of the ordinary then you are ready to start.   Stay on the point, this is not the time to be emotional or try to connive, do not forget that the financial aid office has seen thousands of these letters.  For example, if a family breadwinner had extraordinary medical expenses, state specific times, dates, issue etc.  If a job was lost list date, show evidence of attempting to obtain new employment and the like.  Using direct,  simple to the point facts with documentation will yield a higher chance of success upon appeal.</p>

			<p>The appeal as alluded to before has to be filed by the parent or student requesting professional judgment.  Follow up a week or so after filing to verify that the office received your appeal, and request a reasonable time from for a response.</p>

		</li>

	</ol>

</div>