<div id="member_test_out">
	
	<h1>Testing Out of Classes</h1>
	
	<p>Many college students just out of high school have fresh material about chemistry, physics, and foreign languages on the brain. To speed up the progression through required coursework, a student may want to test out of basic subjects that they do well with. Testing centers on campus often allow a student to pay a minimal fee and sit for exams in almost all subjects. If a college student passes these tests, (s)he will receive the credit hours but not a grade for the course. In other words, the class will not count towards your overall gradepoint average, but it will allow you to graduate sooner if enough credits are achieved. </p>
	<p>Many college students wait too long to sit for these exams and forget the material they learned in high school. Before going and taking the test, purchase an overview of the topic to refresh your memory. An investment of $40 for a topical overview and a few hours of review can earn several college credit hours. Sometimes, the testing center will be able to provide these topical reviews free and the $40 can be saved. </p>
	<p>An investment of a few hours can save countless hours listening to dull lectures and conducting inconclusive experiments in labs. This technique may be used for 50-60 credit hours in most bachelor programs and can result in a <strong>huge savings of time and money.</strong></p>	
	<p>The downside of testing out of chemistry or physics is that it will allow advancement into an advanced chemistry or physics course that a student may not be ready for. Therefore, we recommend testing out of general education requirements and electives to allow greater concentration on a student's major. Music Appreciation, Algebra I, and American History are courses that many freshmen have a strong chance of testing out of due to exposure in high school. </p>	
	<p>Finally, testing out of a class may also be a good option if scheduling problems arise. The dean of a department determines which classes are offered when. Lecture classes and corresponding lab classes are scheduled together to allow increased understanding of the material. Occasionally, a student makes a scheduling error and registers for a lecture class that does not match the lab class. By the time (s)he tries to register for the correct lecture class, the class will often be full and will have to be taken the next semester, slowing the progression through course work. In this type of situation, testing out of the lecture class may permit a return to the normal progression of courses.</p>
		
	<h3>CLEP Tests</h3>
	
	<p>The tests that allow you to gain college credits without taking classes are typically developed by the College Board and together are referred to as the College Level Examination Program, or "CLEP tests" for short. Each test costs $77 and colleges can add up to a $15 administration fee. If you take a test and do not pass, you must wait 6 months before taking it again.</p>
	<p>Each college has its own policy regarding credits gained through CLEP tests, so check your school's policy to find out how many credits you are permitted to gain in this way before investing your time and money into this option.</p>
	<p>CLEP tests are offered in 5 subject areas.  Current test offerings are listed below.</p>
	
	<h3>Composition and Literature</h3>
	
	<ul>
	
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_al.html">American Literature</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ail.html">Analyzing and Interpreting Literature</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ec.html">English Composition</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_el.html">English Literature</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_fcc.html">Freshman College Composition</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_hum.html">Humanities</a></li>
	
	</ul>
	
	<h3>Foreign Languages</h3>
	
	<ul>
	
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_clf.html">French Language (Levels 1 and 2)</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_clg.html">German Language (Levels 1 and 2)</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_cls.html">Spanish Language (Levels 1 and 2)</a></li> 
	
	</ul>
	
	<h3>History and Social Sciences</h3>
	
	<ul>
	
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ag.html">American Government</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_hgd.html">Human Growth and Development</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_iep.html">Introduction to Educational Psychology</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ip.html">Introductory Psychology</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_is.html">Introductory Sociology</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_pmac.html">Principles of Macroeconomics</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_pmic.html">Principles of Microeconomics</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ssh.html">Social Sciences and History</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_us1.html">U.S. History I: Early Colonizations to 1877</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_us2.html">U.S. History II: 1865 to the Present</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_wc1.html">Western Civilization I: Ancient Near East to 1648</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_wc2.html">Western Civilization II: 1648 to the Present</a></li>
		
	</ul>
	
	<h3>Science and Mathematics</h3>
	
	<ul>
	
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_bio.html">Biology</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_calc.html">Calculus</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_chem.html">Chemistry</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ca.html">College Algebra</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_cm.html">College Mathematics</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ns.html">Natural Sciences</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_pcal.html">Precalculus</a></li>	
		
	</ul>
	
	<h3>Business</h3>
	
	<ul>
	
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_fa.html">Financial Accounting</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_ibl.html">Introductory Business Law</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_isca.html">Information Systems and Computer Applications</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_pman.html">Principles of Management</a></li>
		<li><a href="http://www.collegeboard.com/student/testing/clep/ex_pmark.html" >Principles of Marketing</a></li>
		
	</ul>
	
	<p><strong>More information about CLEP tests can be found at </strong><a href="http://www.collegeboard.com/student/testing/clep/about.html">http://www.collegeboard.com/student/testing/clep/about.html</a></li></p>

</div>