<div id="member_tutoring">

	<h1>Tutoring</h1>
	
	<p>Note: if you simply want to learn about the PSAT, ACT, and SAT and take some practice tests, <a href="<?php echo SITE_URL; ?>/member/test_prep">click here</a> to get an overview and see some sample tests.</p>
	
	<h3>Tutoring Options</h3>
	
	<p>We support your desire for success by offering the following options, feel free to use each option as you need it:</p>
	
	<ul>
		<li><a href="<?php echo SITE_URL . '/member/testgear_full/testing'; ?>">Standardized Test Tutoring</a> <em>(PSAT, SAT, ACT)</em></li>	
	</ul>

	<p>Each option includes the following:</p>
	
	<ul>
		<li>A 30-minute online proficiency test</li>
		<li>Over 50 hours of study specifically designed to maximize your score</li>
		<li>26 interactive lessons covering over 50 test taking strategies</li>
		<li>Over 35 interactive tutorials covering 160 content-specific skills</li>
		<li>Progress reports</li>
		<li>3000 + word vocabulary lab</li>
		<li>2 full-length and 16 practice tests</li>
		<li>Immediate scoring</li>
	</ul>

	<!--
	<h1>Tutoring</h1>
	
	<p>Note: if you simply want to learn about the PSAT, ACT, and SAT and take some practice tests, <a href="<?php echo SITE_URL; ?>/member/test_prep">click here</a> to get an overview and see some sample tests.</p>
	
	<h3>Tutoring Options:</h3>
	
	<p>Collegiate Advisors, LLC supports your desire for success by offering the following options:</p>

	<ol>
		<li>
			<p>Our tutoring service is the most expansive available. First the student takes a proficiency test. Your tutoring schedule is then customized based on your strengths and weaknesses. This customization helps you study most efficiently and effectively.</p>
			<ul>
				<li>To learn more about online PSAT tutoring <a href="#a_PSAT">click here</a></li>
				<li>To learn more about online SAT tutoring <a href="#a_SAT">click here</a></li>
			</ul>
		</li>
		<li>
			<p>Our one-on-one tutoring service is also the best in the business. The Collegiate Advisors, LLC personal service includes face-to-face student evaluations and tutoring. One-on-one tutoring is available for the following needs:</p>
			<ul>
				<li>Study Skills</li>
				<li>ACT Preparation</li>
				<li>PSAT Preparation</li>
				<li>SAT Preparation</li>
			</ul>
		</li>
	</ol>
	
	<p>To learn more about one-on-one Study Skills tutoring <a href="#a_oneoneT">click here</a></p>
	<p>To learn more about one-on-one ACT, PSAT and SAT tutoring <a href="#a_oneoneS">click here</a></p>
	
	<h3 id="a_PSAT">Online PSAT Tutoring Page</h3>
	
	<p>The online PSAT tutoring course offers:</p>

	<ul>
		<li>A 30-minute online proficiency test</li>
		<li>Over 55 hours of study specifically designed to maximize PSAT scores</li>
		<li>26 interactive lessons covering 57 test taking strategies</li>
		<li>39 interactive tutorials covering 160 content-specific skills</li>
		<li>Progress reports</li>
		<li>3000 + word vocabulary lab</li>
		<li>2 full-length and 16 practice tests</li>
		<li>Immediate scoring</li>
	</ul>
	
	<p><a href="https://access.bridges.com/auth/login.do?targetUri=%2Fportal%2FlandingPage.do">To start click here</a></p>
		
	<h3 id="a_SAT">Online SAT Tutoring Page</h3>
	
	<p>The online SAT tutoring course offers:</p>
	
	<ul>
		<li>A 30-minute online proficiency test</li>
		<li>Over 50 hours of study specifically designed to maximize SAT scores</li>
		<li>26 interactive lessons covering 56 test taking strategies</li>
		<li>34 interactive tutorials covering 145 content-specific skills</li>
		<li>Progress reports</li>
		<li>3000 + word vocabulary lab</li>
		<li>2 full-length and 16 practice tests</li>
		<li>Immediate scoring</li>
	</ul>
	
	<p><a href="https://access.bridges.com/auth/login.do?targetUri=%2Fportal%2FlandingPage.do" target="_blank" >To start click here</a></p>
	
	<h3 id="a_oneoneS">One-on-One ACT, PSAT, SAT Tutoring Page</h3>
	
	<p>At a cost of $895.00, roughly 1/2 the price of all national services group fees, this is an outstanding bargain. This fee includes all of the following:</p>
	
	<ul>
		<li>A face-to-face evaluation to determine proficiency</li>
		<li>20 hours of one-on-one personal standardized test preparation</li>
		<li>Materials</li>
		<li>Travel</li>
		<li>A professional tutor</li>
	</ul>
	
	<p>To be contacted <a href="./tutoring_notify.php?action=T">click here</a></p>
	
	<h3 id="a_oneoneT">One-on-One Study Skills Tutoring Page</h3>
	
	<p>Behind every good student are good study skills. Yet, study skills are not a subject taught in schools.  The first indicator Collegiate Advisors tutors look for in a struggling student is a lack of strong study skills. It is an area easily remedied once students apply certain strategies and tips taught by our tutors. Teaching good study skills will help establish good practices throughout a child's formal education. Parents will find it amazing how quickly their children will bounce back academically once they've established proper study skills. The first step is to have Collegiate Advisors determine if certain very important guidelines are established in the home and assess each child's study routine in five key areas:</p>

	<ul>
		<li>time management</li>
		<li>organization</li>
		<li>learning styles</li>
		<li>concentration and memory</li>
		<li>taking notes</li>
	</ul>
	
	<p>Collegiate Advisors will determine if good organizational habits are in place and provide specialized, one-on-one guidance. For instance, we always recommend that each student should have a consistent study area that is comfortable and quiet, away from distractions like televisions and radios. Settle on that one location and stay there. A regular time every night must be established for getting homework and studying done. Tell friends and family this time is dedicated to schoolwork.</p>
	<p>As part of Collegiate Advisors extensive study habits analysis, each student's individual learning style will be assessed.  Based on the results, Collegiate Advisors tutors will teach tips and strategies that will help students better comprehend and retain their lessons. &nbsp;For instance, visual learners will pick up words and definitions by reading them over and over again, and "seeing" the words in their heads. Auditory learners tend to recite words and definitions over and over again, or have the words and meanings taped so they can listen to them. Kinesthetic learners prefer to write out the words and definitions and draw pictures to remind them of the meanings. Knowing a student's particular learning style will greatly assist parents and Collegiate Advisors tutors to teach in a way that maximizes learning.</p>
	<p>There are many more study skills, concentration, memory, note and test taking tips Collegiate Advisors tutors will teach each student.</p>
	<p>This course will cost the parent $1,275 as we have to outsource it to a partner company.  This cost is dramatically less expensive than if the parent were to secure these services on his or her own.</p>
	<p>To find out more information about the Collegiate Advisors Study Skills program, <a href="./tutoring_notify.php?action=S">click here</a>.</p>
	-->
</div>