<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Attention:&nbsp; Lauriane VanVoorhees</p>
<p>&nbsp;</p>
<p>Have you employed a scientifically-designed college selection process?</p>
<ul>
<li>Have you maximized your standardized test scores through tutoring? </li>
<li>Have you had your admissions essay reviewed and edited by experts? </li>
<li>Have you analyzed the various financial aid and student loan options?</li>
</ul>
<p class="MsoNormal" style="text-align: left;"><span style="font-family: Tahoma;">If you answered "NO" to any <strong>one</strong> of these questions, then engaging Collegiate Advisors Group&nbsp;(CAG) is going to be one of the smartest and most cost-effective moves you've ever made.&nbsp; Please contact us today for a discussion of how we can help you and your family Save, Prepare and Achieve.</span></p>
<p style="text-align: left;">&nbsp;</p>