<p>
	Referrer Name: <?php echo $referrer_name; ?> <br>
	Referrer Address: <?php echo $referrer_address; ?> <br>
	Referrer City: <?php echo $referrer_city; ?> <br>
	Referrer State: <?php echo $referrer_state; ?> <br>
	Referrer Zip: <?php echo $referrer_zip; ?> <br>
	Referrer Email: <?php echo $referrer_email; ?> <br>
	Referrer Primary Phone: <?php echo $referrer_primary_phone; ?> <br>
	Referrer Secondary Phone: <?php echo $referrer_scondary_phone; ?>
</p>

<p>
	Referred Name: <?php echo $referred_name; ?> <br>
	Referred Address: <?php echo $referred_address; ?> <br>
	Referred City: <?php echo $referred_city; ?> <br>
	Referred State: <?php echo $referred_state; ?> <br>
	Referred Zip: <?php echo $referred_zip; ?> <br>
	Referred Email: <?php echo $referred_email; ?> <br>
	Referred Primary Phone: <?php echo $referred_primary_phone; ?> <br>
	Referred Secondary Phone: <?php echo $referred_scondary_phone; ?>
</p>