<p>
	Parent's Name: <?php echo $parent_name; ?> <br>
	Parent's Email Address: <?php echo $parent_email; ?> <br>
	Parent's Primary Phone: <?php echo $parent_primary_phone; ?> <br>
	Parent's Secondary Phone: <?php echo $parent_secondary_phone; ?> <br>
	Address: <?php echo $address; ?> <br>
	City: <?php echo $city; ?> <br>
	State: <?php echo $state; ?> <br>
	Zip: <?php echo $zip; ?> <br>
	Student's Name: <?php echo $student_name; ?> <br>
	Student's Email Address: <?php echo $student_email; ?> <br>
	Student's Phone: <?php echo $student_phone; ?>
</p>