<p>This is optional and fees may vary by individual need.&nbsp; Please see your planning spcialist for details. All information provided at workshops is free.&nbsp;</p>
<h1>NOTE:&nbsp; To register for the free workshop at West Regional Library in Cary, please visit the "Workshop and Seminar Registration" link on the left side of the home page.&nbsp;</h1>
<p>&nbsp;</p>
<p>
<script type="text/javascript"><!--
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27902258-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
// --></script>
</p>