<div id="member_admissions_index">
	
	<h1>Admissions Assistance</h1>
	
	<p>There are three parts to our admissions assistance:</p>
	
	<ol>
	
		<li>Advice on <a href="<?php echo SITE_URL; ?>/member/admissions/essay">how to write an admissions essay</a>.</li>
		<li><a href="<?php echo SITE_URL; ?>/member/admissions/upload">The opportunity to upload your essay.</a> One of our editors will read it and return it to you with comments. Of course these are only "recommended" changes, and you can accept or reject them at your discretion.</li>
		<li>Advice on preparing for the <a href="<?php echo SITE_URL; ?>/member/admissions/interview_prep">admissions interview</a>.</li>
	
	</ol>
	
</div>