<div id="sub_menu">

	<ul>
		
		<li><a href="<?php echo SITE_URL; ?>/member/admissions/assistance">Admissions Home</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/admissions/essay">Writing Your Essay</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/admissions/upload">Upload Essay to be Edited</a></li>
		<li class="last"><a href="<?php echo SITE_URL; ?>/member/admissions/interview_prep">Preparing for Your Interview</a></li>
	
	</ul>
	
</div>