<div id="member_admissions_upload">
	
	<h1>Upload Essay</h1>
	
	<h6>To have your essay reviewed by one of our editors:</h6>
	
	<ol>
		<li>Browse to your admissions essay stored on your computer.</li>
		<li>Include the essay question/prompt you were responding to at the top of page one of your essay.</li>
		<li>Click send.</li>
	</ol>
	
	<?php echo $form->output(); ?>
	
	<br />
	
	<p>One of our editors will read your essay and return it to your email address with comments. Of course these are only "recommended" changes, and you can accept or reject them at your discretion.</p>
		
	<h6>All of our editors are:</h6>
	
	<ul>
		<li>accomplished authors with published work</li>
		<li>graduates with advanced degrees (Master's or Ph.D.)</li>
		<li>experienced, talented editors</li>
	</ul> 
		
</div>