<p><strong>Paragon Collegiate Advisors </strong></p>
<p>Paragon Collegiate Advisors provides premier college advisement services.&nbsp; The driving force behind Paragon Collegiate Advisors is Gary Saitowitz who brings energy, expertise and personal dedication to each student family, helping them to plan and achieve their collegiate success.&nbsp;</p>
<p>Paragon Collegiate Advisors is focused on helping students and their families through the entire process. From the initial stages of selecting a career, choosing a college and assiting with admittance to discovering the most efficient way to fund the college expenses.</p>
<p>Gary is married and has four children. He enjoys spending time with the family, flying and golf.</p>
<p>&nbsp;</p>