<div id="member_elite_schools">
	
	<h1>Ten Ways To Get Noticed By The Elite Schools</h1>
	
	<p>Elite schools accept less than 30% of their applicants. Admissions counselors at these schools are looking for the following:</p>
	
	<ol>
		
		<li>
			<h3>High level of academic performance from freshman year on</h3>
			
			<p>Strong language, mathematics, and critical thinking skills demonstrated in challenging courses. Consistent improvement and classroom participation. The junior and senior years are particularly important.  (No symptoms of "senioritis" please.)</p>
		</li>
		<li>
			<h3>Strong standardized test results</h3>
			
			<ul>
			
				<li>On the SAT, this means at least a score of 2150.</li>
				<li>On the ACT, this means at least a score of 32.</li>
				<li>On SAT II tests, this means scores ranging from 680 to 800 in at least two, more often three, subjects.</li>
			
			</ul>
		</li>
		<li>
			<h3>All advanced placement classes</h3>
			
			<ul>
			
				<li>Applicants to elite schools are expected to have taken all available.</li>
				<li>Advanced Placement test scores should be at least 4, preferably 5.</li>
				<li>If the high school did not offer more than two AP classes, the student is expected to have taken advantage of "dual enrollment" at a local community or state college.</li>
			
			</ul>
		</li>
		<li>
			<h3>Meaningful extra-curricular activities</h3>
			
			<p>The key word here is "meaningful". A plethora of memberships in clubs,  required high school community service and membership in National Honor Society  do not impress the Admissions Counselor at an elite college. One or two activities such as sports or music that the student has pursued seriously help to round out the application of a student with strong academic credentials. Counselors are most interested in activities that show leadership, organizational skill, and/or creative talent. Ideal activities will show strong leadership, follow through and organizational and/or creative talent as well as purpose and breadth.</p>
		</li>
		<li>
			<h3>A well-written essay</h3>
			
			<p>On many applications the essay is called the "personal statement." That's because it is an opportunity for you to let the Admissions Counselor know something personal about yourself. &nbsp;This will not happen easily, but when work on essays begins at the end of the year and continues over the summer, the likelihood of a great essay is heightened.</p>
		</li>
		<li>
			<h3>Interesting interviews</h3>
			
			<p>Some elite schools will invite applicants to an interview in the fall of their senior year. The Admissions Counselor generally plays down the importance of these interviews in the final decision, but don't believe it. &nbsp;Go to the interview dressed appropriately.  Finally, have questions ready that relate to the area of study of most interest to you.</p>
		</li>
		<li>
			<h3>Flawless applications</h3>
			
			<p>How questions are answered in the application is crucial! Sometimes bright applicants in a rush to meet a deadline and "get through with it all" respond too hastily to important questions.  For example, Dartmouth may ask "What made you decide to apply?  A poor answer would be, "My uncle said I was a strong candidate and he was a member of the Class of 1964." Or you could be asked, "What other colleges have you applied to?"   An applicant to Madison WI responds: "Brown, Harvard, Yale, Princeton, Beloit, Reed and U of Minnesota."   Again, this would be a poor answer as it would show that the student does not understand the differences between these elite colleges. Do you? </p>
		</li>
		<li>
			<h3>Personal factors</h3>
			
			<p>Admissions Counselors attempt to construct a class that will have a particular geographic, ethnic, socio-economic, and talent mix.   Clues about what a school may be looking for may be found in the all important college catalog.</p>
		</li>
		<li>
			<h3>Demonstrated interest</h3>
			
			<p>Demonstrated interest can begin as early as the first half of the student's junior year. We encourage personal communication between the student (not mom) and the college as early as the last half of the junior year.    Other things will enable the serious student to show demonstrated interest, but they vary based on the school and student. Be careful here so as not to overdo it. Also, do not email questions that are easily answered at the college's web site.</p>
		</li>
		<li>
			<h3>A "Hook"</h3>
			
			<p>When all else fails, a hook could be an applicant's saving grace. A student might "hook" the college through an exceptional accomplishment, athletic skill, musical talent, or an influential connection/ benefactor.</p>
		</li>
		
	</ol>

</div>