<div id="member_fiscal_timeline">

	<h1>Financial Aid Time line</h1>

	<table>
		
		<tbody>
		
			<tr>
				<td class="side_heading">December</td>
				<td>Prepare preliminary FAFSA (free application for federal student aid)</td>
			</tr>
		
			<tr>
				<td class="side_heading">January 2nd</td>
				<td>Submit estimated FAFSA</td>
			</tr>
		
			<tr>
				<td class="side_heading">February 15th</td>
				<td>Edit and resubmit</td>
			</tr>
		
			<tr>
				<td class="side_heading">May 1st</td>
				<td>Receive Student Aid Report (SAR) from schools/United States Department of Education</td>
			</tr>
		
			<tr>
				<td class="side_heading">June 15th</td>
				<td>Complete financial decisions for the fall</td>
			</tr>
		
			<tr>
				<td class="side_heading">June 30th</td>
				<td>If needed, complete PLUS or private application</td>
			</tr>
		
			<tr>
				<td class="side_heading">September 5th</td>
				<td><span class="red">*</span> Half of the funds sent from lender to school</td>
			</tr>
		
			<tr>
				<td class="side_heading">January 5th</td>
				<td>Second half of funds sent from lender to school</td>
			</tr>
		
		</tbody>
		
	</table>
	
	<p><a href="<?php echo SITE_URL; ?>/member/student_loans">Back to Student Loan Charts</a></p>
	<p><span class="red">*</span> This applies if the school is on a traditional semester system.  If the school uses a trimester schedule, the funds will be sent 3 times in thirds, if a quarter system, 4 times in fourths, etc.</p>
	
</div>