<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>

	<head>
	
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	
		<title><?php echo $title . $GLOBALS['advisor']->get( 'business_name' ); ?></title>
		
	</head>
	
	<body>
	
		<div id="member_gapping">
			
			<p><strong>Gapping</strong> is the term used to explain what happens when a school does not meet 100% of need in the EFC formula. </p>
			
			<p><strong>Baiting and switching</strong> is the term used when colleges will offer an incoming freshman an impressive financial aid package, but in subsequent years reduce the amount of aid offered.</p>
			
			<p>This certainly is not an illegal process, however, after a child has committed to the school, it is considered an unfair process by some.</p>
			
		</div>
	
	</body>

</html>