<div id="member_high_school_timeline">

	<div id="sub_menu">
	
		<ul>
			
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_sophomore'; ?>">Sophomore Year</a></li>
			<li><a href="<?php echo SITE_URL . '/member/hs_timeline_junior'; ?>">Junior Year</a></li>
			<li class="last"><a href="<?php echo SITE_URL . '/member/hs_timeline_senior'; ?>">Senior Year</a></li>
		
		</ul>
		
	</div>

	<h1>High School Timeline</h1>
	
	<h3>Junior</h3>
	
	<p>Begin college selection process</p>
	
	<h6>September</h6>

	<ul>

		<li>Register for the PSAT which is administered in mid October</li>
		<li>Take the practice test in the PSAT/NMSQT Student Bulletin received at time of registration.</li>
		<li>Get more involved with your extracurricular activities and maintain a record all year.</li>

	</ul>

	<h6>October</h6>
	
	<ul>
	
		<li>Take the PSAT/NMSQT, which can qualify you to receive a National Merit Scholarship.</li>
		<li>Be sure you check "yes" for Student Search Service to hear from colleges and scholarships.</li>
		<li>Attend college fairs in your area. (Check out the Guidance bulletin board, local papers, or on-line for information.)</li>
	
	</ul>
	
	<h6>November -- Keep those grades up.</h6>
	
	<h6>December</h6>

	<ul>

		<li>Use your PSAT/NMSQT Score Report Plus for personalized feedback on your academic skills, and to help you get ready for college and for the SAT, which you will take in the spring.</li>
		<li>Find out about college first hand from college friends who are home for the holidays.</li>

	</ul>

	<h6>January</h6>

	<ul>

		<li>Organize a file of college brochures and information. Before you know it, they'll start pouring in.</li>
		<li>Search for scholarships online that match your skills and interests.</li>
		<li>Ask your parents for your Social Security number (required on many college applications).</li>

	</ul>

	<h6>February</h6>

	<ul>

		<li>ATTEND ALL SCHEDULED JUNIOR WORKSHOPS WITH YOUR COUNSELOR.</li>
		<li>Register for the March SAT I if you have completed the math courses covered on the SAT I AND you have done the proper preparation for the exam. If not, plan to take the SAT I in May or June.</li>
		<li>Talk to you counselor and teachers about taking the SAT II: Subject Tests this spring.</li>
		<li>Plan to visit colleges this spring while they're in session.</li>
		<li>Start to explore your college options.</li>
		<li>Think about which college characteristics are important to you.</li>
		<li>Have an interview with admissions officers when you visit campuses.</li>
		<li>Don't spend so much time trying to improve standardized test scores that grades and co-curricular involvement suffer. Strive to find a balance and maintain it.</li>

	</ul>
	
	<h6>March</h6>
	
	<ul>
	
		<li>Write, telephone, or use the Internet to request admissions, and financial aid information from the colleges on your list.</li>
		<li>There is no charge and no obligation to obtain general information about admission and financial aid.</li>
		<li>Ask your counselor and investigate if the ACT test might be appropriate for you.</li>
	
	</ul>
	
	<h6>April</h6>
	
	<ul>
	
		<li>When selecting senior year courses, be sure to continue to challenge yourself academically, but realistically.</li>
		<li>Register for the May/June SAT I and/or the May/June SAT II Subject Tests.</li>
		<li>Look into summer jobs or apply for special academic or enrichment programs.</li>
		<li>Take the ACT if appropriate.</li>
		<li>Attend local college fairs.</li>
	
	</ul>
	
	<h6>May</h6>
	
	<ul>
	
		<li>Take the AP, ACT, SAT I, and SAT II exams if appropriate.</li>
	
	</ul>
	
	<h6>June</h6>
	
	<ul>
	
		<li>Talk to teachers about writing letters of recommendation for you.</li>
		<li>Take the ACT, SAT I and SAT II exams if appropriate.</li>
		<li>Finalize your summer plans.</li>
	
	</ul>
	
	<h6>July &amp; August</h6>

	<ul>

		<li>Start thinking about college majors related to your interests and career goals</li>
		<li>Request applications, brochures, and financial aid information from your colleges.</li>
		<li>Visit colleges, take tours, and have interviews</li>
		<li>Continue to refine your list of schools.</li>
		<li>Contact coaches if applicable.</li>
		<li>Begin preparing for the actual application process. (ex. Start a draft of a college essay)</li> 

	</ul>
	
</div>