<div id="member_sample_recommendation_letter">

	<h1>Sample Letter</h1>
	
	<p>January 1, <?php echo date( 'Y' ); ?></p>
	
	<p>
	Admissions Office<br />
	Ohio Business College<br />
	1907 North Ridge Road<br />
	Lorain, OH 44055<br />
	</p>
	
	<p>Subject: Letter of Recommendation for Sarah Hoover</p>
	
	<p>To Whom It May Concern:</p>

	<p>It is with enthusiasm and enjoyment that I am writing to support Sarah Hoover's application to the Ohio Business College. For over 30 years, I have been a faculty member at Howard Johnson High School in the business department. In addition, I have supervised many research laboratories and counseled many students seeking professional advancement. I hope my opinion of Sarah Hoover will be beneficial to the Ohio Business College admissions committee as you evaluate this exceptional candidate.</p>
	<p>I first came in contact with Sarah during the spring semester of 1997 when she entered my office needing advice regarding class scheduling. During the course of our discussion, she spoke of her desire to major in business and to study at Ohio Business College. It was apparent at that time that she was highly motivated to achieve this goal and would be an exceptionally strong student.</p>
	<p>During the time I have known Sarah, she has shown enthusiasm for learning and openness to new ideas. Sarah was a student in my Marketing and Accounting classes. She exhibited an eagerness for knowledge and an understanding of the principles of the class. She scored at the top of her class on all verbal and written examinations during this time. </p>
	<p>Sarah was asked to participate on the Business Honor Student Review Committee, which develops relationships between our school and businesses in the community. It was considered an honor for a sophomore student to be on the committee at the time. She proved herself a leader among her peers and was responsible for hosting prospective companies at Howard Johnson High School. Her skills were apparent to all; even our principal mentioned her in an annual faculty review of students at the end of the semester. </p>
	<p>I know Sarah is highly motivated and interested in practicing business. Sarah is a kind and compassionate individual who is committed to helping people through business opportunities. She is surpassing the requirements  for graduation from Howard Johnson High School with exceptional scores and is enhancing the business program at HJHS with her participation on the Business Student Review Committee. I have the highest admiration for her achievements.</p>
	<p>I advise you to thoughtfully consider Sarah Hoover's application. I look forward to seeing her succeed in the business field.</p>
	
	<p>Sincerely,</p>
	
	<p>
		Mary Stevenson<br />
		Faculty Member, HJHS<br />
		Business Teacher<br />
		Faculty Advisor, Business Student Review Committee
	</p>
	
	<h6>Back to <a href="<?php echo SITE_URL; ?>/member/letters_of_recommendation">Letters of Recommendation</a> page</h6>

</div>