<div id="member_student_loans">

	<h1>Student Loans</h1>

	<p>Please do not respond to any direct mail pieces, direct emails, or advertisements for student loans!!
	It is not that the advertisers are not good companies.  However, we will be able to get you a better rate
	and/or fees than if you respond to the advertisements.</p>

	<p><?php echo $GLOBALS['advisor']->get( 'business_name' ); ?> does everything possible to
	eliminate, or at least minimize, the amount of student loans that your family will need.  That being
	said, quite often loans are required as the most cost effective way of paying for college.  Part of our
	job is to to assist you in the student loan process. The following information will give
	you useful general knowledge of student loans.</p>

	<p>Below are two lists of FAQ's. The first is a list of questions and answers presented by students to
	Financial Aid Officers. The second is a list of questions and answers from financial aid officers at a
	recent symposium.</p>

	<ul>
		<li><a href="<?php echo SITE_URL . '/member/private_file/financial_aid_officers_qa1'; ?>">Financial Aid Officers Q&amp;A #1</a></li>
		<li><a href="<?php echo SITE_URL . '/member/private_file/financial_aid_officers_qa2'; ?>">Financial Aid Officers Q&amp;A #2</a></li>
	</ul>

	<p>Additionally we have provided the following chart of the loan types available, from the most cost
	effective to the most expensive. The Federal Perkins Loans are awarded to the lowest income bracket
	of college bound students; so many students will not qualify for this type of loan.</p>

	<p>Finally, to see a student loan time line <a href="<?php echo SITE_URL; ?>/member/fiscal_timeline">click here</a>.</p>

	



<p>
The undergraduate loan processes is pretty simple and straight forward. Each and every family has to complete the    <a target="_blank" href="http://www.fafsa.ed.gov/"> FAFSA</a>, (Free Application for Federal Student Aid). It is a very simple form to complete. If you happen to attend
    this <a target="_blank" href="http://professionals.collegeboard.com/profdownload/PROFILE_Student_Guide.pdf">small subset of schools</a> then you are in a different
    ballgame and will be obligated to complete the CSS Profile.
</p>
<p>
    Regardless of whether you need to complete one form or two the following is available in relation to loans. For the sake of this conversation we are not
    going to discuss grants. If the student is eligible for federal grants they will be extended to the student by default. The loans are a matter of choice.
</p>
<p>
    This list is not designed to be exhaustive, but is meant to and does cover over 99% of undergraduate students. For the actual definitions of each of the
    terms below simply go to the <a target="_blank" href="http://studentaid.ed.gov/glossary/">Student Aid Glossary</a>.
</p>
<p>
    Finally it is important to understand that by completing the FAFSA form you are automatically completing the Application for all Federal Student Aid,
    including Work Study.
</p>
<p>
    <strong>Perkins</strong>
</p>
<p>
    The Perkins loan is unique in the federal loan program in that the school is the actual lender. Only 1,800 colleges offer the Perkins loans. The Perkins
    loan program is for the most financially disadvantaged applicants. Perkins loans carry a 5% interest rate, are amortized over a term of 10 years and their
    payments do not begin until 9 months after graduation. Below are the current loan limits.
</p>
<table border="0" cellspacing="0" cellpadding="0" width="577">
    <tbody>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p>
                    Year in College
                </p>
            </td>
            <td width="470" nowrap="" colspan="2" valign="bottom">
                <p>
                    Maximum Loan Amount
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    Dependent
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    Independent
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    1
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    2
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    3
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    4
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    5
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p>
                    Maximum
                </p>
            </td>
            <td width="188" nowrap="" valign="bottom">
                <p>
                    $ 27,500
                </p>
            </td>
            <td width="282" nowrap="" valign="bottom">
                <p>
                    $ 27,500
                </p>
            </td>
        </tr>
    </tbody>
</table>
<p>
    <strong>Stafford </strong>
</p>
<p>
    First; to qualify the student has to be enrolled at least half time.
</p>
<p>
    Stafford Loans come in several variables, subsidized and unsubsidized. Subsidized loans do not accrue interest until the student begins repayment; the
    current rate is 3.4%. Unsubsidized loans accrue interest from the date college begins; the current rate is 6.8%. A student is offered a subsidized Stafford
    loan depending on the results of the completion of the FAFSA. There are no income or credit requirements for the unsubsidized Stafford Loan.
</p>
<p>
    Another variation is whether or not the student is determined to be a Dependent student or Independent Student. The defining characteristics are quite
    black and white and can be seen <a target="_blank" href="/member/private_file/dependentindependent">here</a>
</p>
<p>
    <strong>IMPORTANT NOTE:</strong>
    If the parent is denied for a PLUS loan, which does have credit underwriting, the Dependent loan limits are the same as the higher Independent loan limits.
</p>
<table border="0" cellspacing="0" cellpadding="0" >
    <tbody>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p>
                    Year in College
                </p>
            </td>
            <td nowrap="" colspan="4" valign="bottom">
                <p>
                    Maximum Loan Amount
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    Dependent
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    Independent
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    Total
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    Subsidized
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    Total
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    Subsidized
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    1
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 3,500
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 9,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 3,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    2
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 6,500
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 4,500
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 10,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 4,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    3
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 7,500
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 12,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    4
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 7,500
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 12,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 5,500
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p align="center">
                    5
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 4,000
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 4,000
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 12,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 4,000
                </p>
            </td>
        </tr>
        <tr>
            <td width="107" nowrap="" valign="bottom">
                <p>
                    Maximum
                </p>
            </td>
            <td width="100" nowrap="" valign="bottom">
                <p>
                    $ 31,000
                </p>
            </td>
            <td width="123" nowrap="" valign="bottom">
                <p>
                    $ 23,000
                </p>
            </td>            
            <td width="114" nowrap="" valign="bottom">
                <p>
                    $ 57,500
                </p>
            </td>
            <td width="108" nowrap="" valign="bottom">
                <p>
                    $ 23,000
                </p>
            </td>
        </tr>
    </tbody>
</table>
<p>
    <strong>PLUS, (Parent Loan for Undergraduate Student)</strong>
</p>
<p>
    First; to qualify the student has to be a dependent student and be enrolled at least half time.
</p>
<p>
    This loan is quite simple. It is in the parents name only; the child has no legal responsibility in relation to repayment. The parent borrows the loan on
    behalf of the child up to the maximum amount the child needs to attend college. There are no income requirements to obtain a PLUS loan. However there are
    credit requirements. Think of it is the 5 year rule, no bankruptcies, even starting of a foreclosure, charge-off, or repossession in that time period.
    Additionally, the student can have no adverse credit. The interest rate is 7.9%. The repayment period varies based on the amount of the loan and will be
    discussed during the application process, that said the maximum repayment period is 20 years.
</p>
<p>
    Finally: IF THE PARENT IS TURNED DOWN FOR A PLUS LOAN, the dependent student is automatically qualify for the higher independent maximum Stafford loans
    limits.
</p>
<p>
    <strong>Private Loans</strong>
</p>
<p>
    Private student loans are an entirely different ball of wax. To start with keep in mind that the Credit Card industry is more tightly regulated that the
    Private Student Loan Industry. Additionally, the default rates on these types of loans are quite high and thus they are quite expensive. If however, the
    parent has good credit, private loans offer a very quick and easy way to obtain funds to pay for college. Most lenders have pulled out of the Private
    student loan market. However, there are several large lenders that do still offer the loans; a simple internet search will allow the parent to decide if
    such options are in his or her best interest.
</p>






<!--<table>

		<thead>

			<tr>
				<th>Loan Program</th>
				<th>Eligibility</th>
				<th>Award Amounts</th>
				<th>Interest Rate</th>
				<th>Lender/Length of Repayment</th>
			</tr>

		</thead>

		<tbody>

			<tr>
				<td class="side_heading">Federal Perkins Loans</td>
				<td>Undergraduate and graduate students; do not have to be enrolled at least 1/2 time</td>
				<td>
					<p>Undergraduate-up to $4,000 a year (maximum of $20,000 as an undergraduate)</p>
					<p>Graduate-up to $6,000 a year (maximum of $40,000, including undergraduate loans)</p>
					<p>Amount actually received depends on financial need, amount of other aid, availability of funds at school</p>
				</td>
				<td>4.5 percent</td>
				<td>
					<p>Lender is your school</p>
					<p>Repay your school or its agent</p>
					<p>Up to 10 years to repay, depending on the amount owed</p>
				</td>
			</tr>

			<tr>
				<td class="side_heading">Stafford/Direct Loans</td>
				<td>Undergraduate and graduate students; must be enrolled at least 1/2 time</td>
				<td>
					<p>Depends on grade level in school and dependency status <a href="#depStat">(see chart)</a></p>
					<p>Financial need not necessary</p>
				</td>
				<td>
					<p>Changes yearly; for 2010-2011 the interest rate is 4.5%</p>
					<p>For those with financial need, government pays interest during school and certain other periods</p>
				</td>
				<td>
					<p>Lender is a the Department of Education</p>
					<p>Repay the loan holder or its agent</p>
					<p>Between 10 and 25 years to repay, depending on amount owed and type of repayment plan selected</p>
				</td>
			</tr>

			<tr>
				<td class="side_heading"> PLUS/Direct Loans</td>
				<td>
					<p>Parents of dependent undergraduate students enrolled at least half time; parents must not have bad credit history</p>
				</td>
				<td>
					<p>cost of attendance minus other aid received = maximum loan amount</p>
				</td>
				<td>Changes yearly; for 2010-2011 the rate is capped at 7.9% for loans in repayment; government does not pay interest</td>
				<td>Same as for  Stafford/Direct Loans above</td>
			</tr>

		</tbody>

	</table>

	<h3>Maximum Stafford Loan Amounts for 2010-2011</h3>

	<a name="depStat"></a>

	<table>

		<thead>

			<tr>
				<th>Dependency Status</th>
				<th>Dependent Undergraduate Student</th>
				<th>Independent Undergraduate Student</th>
				<th>Graduate or Professional Student</th>
			</tr>

		</thead>

		<tbody>

			<tr>
				<td class="side_heading">1st Year</td>
				<td>$5,500</td>
				<td>$9,500-No more than $3,500 of this amount may be in subsidized loans.</td>
				<td rowspan="3">$25,500 for each year of study-No more than $8,500 of the annual amount may be in subsidized loans.</td>
			</tr>

			<tr>
				<td class="side_heading">2nd Year</td>
				<td>$6,500</td>
				<td>$10,500-No more than $4,500 of this amount may be in subsidized loans.</td>
			</tr>

			<tr>
				<td class="side_heading">3rd and 4th Years (each)</td>
				<td>$7,500</td>
				<td>$11,500-No more than $5,500 of this amount may be in subsidized loans.</td>
			</tr>

			<tr>
				<td class="side_heading">Maximum Total Debt from Stafford Loans When You Graduate</td>
				<td>$31,500</td>
				<td>$75,500-No more than $31,500 of this amount may be in subsidized loans.</td>
				<td>
					<p>$138,500-No more than $65,500 of this amount may be in subsidized loans.</p>
					<p>The graduate debt limit includes Stafford Loans received for undergraduate study.</p>
				</td>
			</tr>

		</tbody>

	</table>

	<p>Private loans are the most expensive as the federal government does not subsidize the interest in anyway. It is for this reason that they are called private, or alternative, loans. They are an alternative to the federally insured loans.</p>
	<p>There are literally hundreds of private loans on the market. Like any other product, what works for one family might not fit the next ten. Fortunately, our founder has developed over 100 loan programs for a wide variety of banks and student loan lenders. We will work our hardest to match you with the best program for your family.</p>-->

</div>