<div id="member_test_prep">

	<h1>PSAT, ACT and SAT Preparation</h1>
	
	<p>Hats off to you for working this hard to acheive collegiate success!</p>
	<p>The 6 links allow you to take 2 PSAT preparation tests, 2 SAT practice tests, and 2 ACT practice tests.</p>
	
	<p>Get Adobe Reader here <a href="http://www.adobe.com/products/acrobat/readstep2.html"><img src="<?php echo SITE_URL; ?>/images/adobe-reader.gif" /></a> (You will need Adobe Reader to view these preparation tests.)</p>
	
	<ul class="pdf_list">
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/psat_practice_test1">PSAT Practice One</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/sat_practice_test1">SAT Practice One</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/act_practice_test1">ACT Practice One</a></li>
	</ul>
	
	<ul class="pdf_list">
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/psat_practice_test2">PSAT Practice Two</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/sat_practice_test2">SAT Practice Two</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/private_file/act_practice_test2">ACT Practice Two</a></li>
	</ul>
	
	<h3>About Standardized Tests</h3>
	
	<p>The Scholastic Aptitude Test (SAT) is required for admission to most undergraduate programs in the United States. By design, the SAT provides a standardized measure of academic performance for all examinees under equivalent conditions. The new SAT includes three sections:</p>

	<ol>
		<li>
			<p>Critical Reasoning: 70 minutes/ 67 total questions</p>
			<ul>
				<li>Sentence Completion, 19 questions</li>
				<li>Passage-Based Reading, 48 questions</li>
			</ul>
		</li>
		<li>
			<p>Mathematics: 70 minutes/ 54 total questions</p>
			<ul>
				<li>Multiple Choice/ Problem Solving, 44 questions</li>
				<li>Student-Produced Response (Grid-Ins), 10 questions</li>
			</ul>
		</li>
		<li>
			<p>Writing: 60 minutes/ 49 total questions plus essay</p>
			<ul>
				<li>Identifying Sentence Errors, 18 questions</li>
				<li>Improving Sentences, 25 questions</li>
				<li>Improving Paragraphs, 6 questions</li>
				<li>Essay Writing, 1 essay</li>
			</ul>
		</li>
	</ol>
	
	<table class="no_border">
		<tr>
			<td class="side_heading no_wrap">The bad news:</td>
			<td>From our experience, very few applicants do well on this exam without serious preparation.</td>
		</tr>
		<tr>
			<td class="side_heading no_wrap">The good news:</td>
			<td>By design, the SAT is a standardized test that is relatively easy to master. A score on the June 1990 exam must mean the same thing as the same score on the December 2006 exam. Therefore, the content of the test remains the same over time to allow fair and accurate comparison of scores from year to year. That's what makes preparation so easy and worthwhile: every exam tests the same set of skills.</td>
		</tr>
	</table>
	
	<h3>Scoring</h3>
	
	<p>The SAT produces individual scores for each section of the test and an overall composite score that ranges from 200 - 800. Your scaled score also corresponds to a percentile ranking, which shows how your score compared to that of the entire applicant pool.</p>
	<p>What is a good score? Perception varies among schools, depending on the characteristics. Many state universities with excellent programs consider a score in the low 600s to be highly competitive, while a more selective program would consider a composite score of 650 to be quite low. To determine your odds of success, check the stats for accepted applicants at each school that interests you. Your goal should be to exceed that number by a comfortable margin.</p>
	<p>Also investigate how each school handles the scores once they receive them. If you take the SAT more than once, most schools will use the highest of your test scores to make their admission decision. Yet some schools simply average the scores and are suspicious of a wide variation in an applicant's performance. Our advice: study and prepare well and take the test once. Do your best the FIRST time.</p>
	
	<h3>How Colleges &amp; Universities Use Standardized Tests</h3>
	
	<p>From our experience, highly selective universities place extraordinary emphasis on the SAT. With hundreds of candidates competing for each seat in the class, schools use standardized test scores as a quick comparative benchmark. At many highly selective schools, your SAT scores are more critical than your GPA in determining your admission chances. We can't stress enough how imperative it is to do well on this test.</p>
	<p>Why the importance? High schools differ in academic rigor and in the information they provide about students, making comparisons difficult. Some rank students, while others do not. Some report a % ranking, such as in the "top 10%", but don't specify whether you are the top 1% or 9%. How do you compare a top-ranked student from a class of 300 students vs a class of 3000? The student in the larger class faced more intense competition, but that doesn't justify punishing the student from the smaller school.</p>
	<p>To level the playing field, universities consider your SAT scores as an indicator of your performance in comparison to other applicants throughout the world. To become proficient at the SAT, you must practice, practice, practice. Know the material well before the test. Learn the test instructions by heart. Take several practice tests under controlled test conditions. Familiarity will breed comfort with the process and increase your likelihood of a good score.</p>
	
	
	<h3>General Strategies for Standardized Tests</h3>

	<ol>
		<li>Be familiar with the types of questions in each section. Refresh your skills in basic grammar and mathematics. Practice on our test questions and sample exams until you are comfortable with every question type.</li>
		<li>Know how long you have to complete each section and budget your time accordingly.</li>
		<li>Don't waste time reading the instructions on the test day. We include the specific instructions for each question type on this site. Read them thoroughly here and make sure you understand them. This will save you several minutes on the actual test day.</li>
		<li>Develop a strategy to attack the questions in each section according to their level of difficulty. Remember, each question (regardless of its difficulty) is worth one point. Learn to recognize and seek out the types of questions you are good at. Answer as many "easy" ones first, returning later to tackle more difficult, time-consuming math problems and reading passages.</li>
		<li>Answer every question, even if you are clueless about how to approach it. In many cases, you are better off guessing than wasting a ton of time on a problem you aren't able to solve. The test questions will vary widely in their level of difficulty. Some questions will be extremely difficult for all students and should not consume a disproportionate amount of your time.</li>
		<li>Keep track of time as you work on each section of the test. We will teach you many strategies for how to approach different types of test questions. Yet you must effectively manage your time during the test to get a chance to apply those strategies correctly to as many questions as possible. Practice, practice, practice! Take the sample exam under timed test conditions. Give yourself one full minute at the end of each section to quickly fill in answers for questions you didn't get to.</li>
		<li>Be extremely careful with your answer grid. Make sure you record your answers properly and skip spaces properly if you jump around during the test. We recommend that you circle the correct answer to each question in your test booklet, in addition to recording it on your answer grid. Circle questions that you are skipping, so that you can find them easily later when you return to them. Take a minute at the end of each section to verify that you have recorded all of your answers properly.</li>
		<li>Don't try to cram a lot of studying into the last few days before the test. Your best bet is to prepare a few hours a day for several weeks before the exam and to relax (or try to relax) the day or so before the actual test.</li>
		<li>Arrive at the test center a few minutes early with all of your essential supplies (photo ID card, admission ticket, sharpened #2 pencils, watch, comfortable clothing, snack). Avoid chatting about the test during the breaks: this usually just increases your self-doubt and your test-taking anxiety.</li>
		<li>Few applicants know how they did on the test when they leave the test center. Most feel badly, but this is usually just burnout from the stress of the long day. Don't panic and cancel your score unless you were seriously ill on the test day (and it affected your performance), or you were seriously unprepared and plan to remedy that before taking the test again.</li>
	</ol>

</div>