<h1>HOW MUCH WILL IT&nbsp;COST TO SEND MY&nbsp;CHILD TO COLLEGE?</h1>
<p>For most Americans educating their children will probably be one of the biggest financial challenges they will face in their lifetime. In 2011, the tuition and fees to attend a private college averaged about $28,000 a year. &nbsp;A public four year institution had average tuition and fees of about $8,000 a year and may not not include the cost of room and board, books, travel, and other expenses.&nbsp;</p>
<p><strong>How can a College Planner / Financial Aid Strategist help?</strong></p>
<p>A College Planner is a professional who is trained to provide the family with the best possible solution to thier financial aid problems. I can suggest methods to minimize your family's EFC so that your child can qualify for the maximum amount of financial aid. With rising cost of college outpacing inflation, utlilizing a professional's knowledge and resources will be vital to the over all of reducing college expense. &nbsp;Whatever your income and assets currently are, I can show you how to make either a private or public college affordable.</p>
<p><strong>What if my child is already in college could you help me get more financial aid?</strong></p>
<p>The simple answer is "maybe". Only by doing an assesment of your financial situation could there be possiblities of qualifing for more financial aid. &nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>