<h1>Family Case Studies</h1>
<p>These case studies are just a few examples of the services that we provide.  We have helped hundreds of families throughout the years and no two families have ever been the same!  Please note that you should not attempt any of these strategies without consulting a professional.  We are always here to answer any questions you may have.</p>
<h3>Case Study A</h3>
<p><em>John and Linda of East Syracuse</em></p>
<p><strong>Family Situation</strong></p>
<p>John owns a retail business where Linda works part-time.  Their oldest son Michael is going to college next year.  He is interested in getting all of the scholarship money available to him.</p>
<p><strong>Family Income, Assets, &amp; Debts</strong></p>
<ul>
<li>Yearly Net Income of Approx. $225,000</li>
<li>Retirement Assets of Approx. $185,000</li>
<li>Non-Retirement Assets of Approx. $205,000</li>
<li>Home Value Assessed at $328,000 (they owe nothing on the house)</li>
<li>Home Equity Line of Credit of $100,000 ($25,000 used)</li>
</ul>
<p><strong>Assessment</strong></p>
<p>Since John and Linda will not qualify for any need-based financial aid, we needed to maximize their tax benefits available for college and reduce their income taxes to free-up additional funds.  We also needed to complete a scholarship search for Michael and enroll him in SAT prep to better his chances of getting accepted in his choice of schools and getting more merit aid.</p>
<p><strong>Plan Implemented</strong></p>
<p>We implemented a Health Savings Account for the business, established a Section 127 Education Assistance Plan, made use of the IRS Gift and Leaseback Program, and hired Michael (their child) to maximize deductions, including the deduction of Michael’s car, and restructured their retirement plan.  Michael used our Scholarship Search Tool to look for available scholarships and also used our SAT Prep software to increase his SAT score.</p>
<p><strong>Results</strong></p>
<p>The implemented plan <strong>saved John and Linda over $20,000 per year</strong> in taxes and even increased retirement savings by <strong>$11,000 per year</strong>.  Michael has identified about $1,250 in scholarships he is eligible for and increased his SAT score by about 200 points, which may put him in a top bracket for scholarship and grant money at his top 2 college choices.</p>
<p><em>(PLEASE NOTE: THESE STRATEGIES SHOULD ONLY BE DONE BY A QUALIFIED PROFESSIONAL WHEN DEEMED APPROPRIATE.  DO NOT ATTEMPT ANY TAX STRATEGY WITHOUT CONSULTING A PROFESSIONAL)</em></p>
<h3>Case Study B</h3>
<p><em>Ralph and Marlene of Fayetteville</em></p>
<p><strong>Family Situation</strong></p>
<p>Ralph is a college professor and Marlene works an as administrative assistant.  Their daughter Sarah is beginning her junior year of high school.  Sarah was not sure what she wanted to do in college or where she might even want to go.</p>
<p><strong>Family Income &amp; Assets</strong></p>
<ul>
<li>Yearly Net Income of Approx. $110,000</li>
<li>Retirement Assets of Approx. $105,000</li>
<li>Non-Retirement Assets of Approx. $80,000</li>
<li>Account for Sarah (UGMA) Approx. $12,000</li>
<li>Home Value Assessed at $203,000 (they owe about $140,000)</li>
<li>Two Car Loans Totaling Approx $30,000</li>
<li>Credit Card Debt Totaling Approx $6,000</li>
</ul>
<p><strong>Assessment</strong></p>
<p>Ralph and Marlene may qualify for Financial Aid; therefore we needed to maximize their ability to receive funding.  They were also interested in minimizing their expenses and increasing their cash flow.  Sarah should complete career planning to find what majors and careers she might be interested in, and what colleges offer those majors.</p>
<p><strong>Plan Implemented</strong></p>
<p>We first repositioned some of their assets more effectively for college planning.  We then showed them how to get a $2,400 tax credit using New York State’s 529 Plan, which also was more tax efficient for college.  We completed a consolidation loan to increase cash flow while also reducing the time to pay off their mortgage. We completed a thorough review of all of their insurance products to minimize unnecessary expenses.  Sarah used our Career Planning tool to help her better understand what fields she would be interested and where a good college fit would be.  We also worked with an estate attorney to create their wills, health care proxy’s and powers of attorney since they had not done that yet.  All parents should have these documents, especially with children going to college!</p>
<p><strong>Results</strong></p>
<p>By more effectively repositioning their assets earmarked for college, we increased Sarah’s Financial Aid Eligibility by <strong>over $2,500 per year</strong>.  Using New York State’s 529 Plan, they are <strong>saving about $600</strong> per year in New York State Taxes and reducing their Federal and State tax liability.  Their consolidation loan saved them about <strong>$350 per month</strong> and reduced their mortgage payment by about 8 years!  We were also able to free up about <strong>$110 per month</strong> on all their insurance costs, while even increasing their coverage.  Sarah is enjoying using the Career Planning Tool and has narrowed her majors down to 3 areas and is interested in attending 7 different schools.  Ralph and Marlene are sleeping a little easier at night having completed their wills, health care proxy’s, and powers of attorney.</p>
<p><em>(PLEASE NOTE: THESE STRATEGIES SHOULD ONLY BE DONE BY A QUALIFIED PROFESSIONAL WHEN DEEMED APPROPRIATE.  DO NOT ATTEMPT ANY TAX STRATEGY WITHOUT CONSULTING A PROFESSIONAL)</em></p>