<p>In 2006 Private Foundation by the name of Collegiate Access Group&nbsp;was formed. &nbsp;This foundation originated on the thought that all students and families should have access to the best educational resources available.</p>
<p>Its first offering was this site, collegefundingfoundation.org.</p>
<p>Below is a recently received unsolicited reference.</p>
<p><em>This is good stuff! I checked out the site a couple of times today and I am very impressed with the comprehensiveness. After I would sign out, I would think of another feature that would be cool, then sign back in to find out that it is already there. Very impressive. This could almost eliminate guidance counselors and college counselors.</em><br /> - Michael R.<br />&nbsp; Assistant Principal / Director of Guidance</p>
<p>In an attempt to keep our costs at a minimum we do not offer live support.&nbsp; By sending an email your questions and comments are returned 7 days a week.&nbsp; That said, the process is so intuitive that we rarely receive more than 1 question a month.</p>
<p>Please feel free to <a title="\&quot;\\&quot;\\\\\\&quot;\&quot;" href="\">contact us</a> at any time to add your members or students as members.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>