<li>Check that colleges have received all materials: application, test scores (sent by ETS and ACT), financial aid forms</li>
<li>Carefully read all information from colleges</li>
<li>Verify with your counselor that mid-year reports have been sent</li>
<li>Notify colleges of any new information, including honors or accomplishments</li>
<li>Men 18 years and older must register for the draft to receive federal financial aid; inquire at your local Post Office about how to receive proof of registration</li>
<li>Continue to check for scholarships</li>