<li>All colleges should respond to your application by this month (deadline to inform them of your decision is May 1)</li>
<li>Decide where you wish to go</li>
<li>Financial aid offers will begin to arrive</li>
<li>If you are "wait-listed" write a letter of sincere interest and send any appeals/supporting material that you can</li>
<li>FAFSA SAR (Student Aid Report) should arrive - look in the top right hand corner for your EFC (Expected Family Contribution)</li>
<li>If possible, visit colleges to which you were accepted on Open House or Admitted Students day(s) - this will help in your final decision</li>
<li>Make your final decision - send deposit and SIR (Statement of Intent to Register) by May 1</li>