<div id="member_tax_hope">

	<h1>The American Opportunity Tax Credit</h1>

	<p>Keep in mind that a tax credit is not financial aid.  No check gets cut from anyone to the student, parents, or school.  A tax credit is a direct reduction of the amount of tax money you owe the IRS.  A tax credit is different than a tax deduction.  With deductions, the amount of income the IRS may tax is reduced.  </p>

	<h3>Who Qualifies for this Tax Credit?</h3>

	<p>Because a tax credit is a direct reduction of the amount you owe the IRS, one needs to owe taxes to qualify for a tax credit such as the Hope Scholarship Tax Credit.  If you owe no taxes, then you have no eligibility for this tax credit.  If you owe less in taxes than the total amount of the credit, the credit will reduce your liability to the IRS to zero dollars.  </p>
	<p>The Hope Scholarship Tax Credit is only good for the first 2 years of a student's post-secondary education.</p>
	<p>This benefit is available to parents and any or all dependents.  To qualify, the student must:</p>

	<ul>

		<li>Be in a degree seeking program (taking miscellaneous classes at a local college does not qualify)
		<li>Be at least a half-time student for at least one semester
		<li>Have no drug convictions by the end of the year
		<li>Be within his/her first 2 years of post-secondary education

	</ul>

	<h3>Qualifying Income Amounts</h3>

	<table>

		<thead>

			<tr>

				<th>Taxpayer's Status</th>
				<th>Maximum Income</th>
				<th>Maximum Income With Phase-Out</th>

			</tr>

		</thead>

		<tbody>

			<tr>

				<td class="side_heading">Single</td>
				<td>$48,000</td>
				<td>$58,000</td>

			</tr>

			<tr>

				<td class="side_heading">Married Filing Jointly</td>
				<td>$96,000</td>
				<td>$116,000</td>

			</tr>
			</tr>

		</tbody>

	</table>

	<p>The <em>Maximum Income</em> column above shows the maximum income you may earn and still obtain the full tax credit amount.  The amount of credit for those above the maximum income level decreases in phases until one reaches the <em>Maximum Income with Phase-Out</em> amount.  At this income level and higher, no credit is available to the taxpayer. </p>

	<p>This credit cannot be claimed by those who are married and file separately.  Nor can the Hope Scholarship Tax Credit and the Lifetime Learning Tax Credit be used in the same year for the same individual.</p>

	<h3>Calculating Your Tax Credit</h3>

	<p>This credit applies only for tuition and fees at accredited colleges that are approved by the Department of Education.  If the school offers FFELP loans, it is an accredited college approved by the Department of Education.  Cost of books, supplies, and equipment may be included only if they must be paid to the school in order to enroll.  Room and board, transportation, and living expenses may not be included in the credit you claim.  If a student receives a scholarship for full tuition, this credit cannot be used.</p>

	<p>The credit is a maximum of $1,800 per year <em>per student</em>. (Thus a family with 2 children in college can use the Hope Scholarship Tax Credit twice.) The first $1,200 of qualified expenses is covered at 100%.</p>

	<table>

		<thead>

			<tr>
				<th></th>
				<th>Sibling A</th>
				<th>Sibling B</th>
			</tr>

		</thead>

		<tbody>

			<tr>
				<td>Total Qualified Expenses</td>
				<td>$2,000</td>
				<td>$1,200</td>
			</tr>

			<tr>
				<td>100% of the first $1000 covered</td>
				<td>$,1000</td>
				<td>$1,000</td>
			</tr>

			<tr>
				<td>50% of all other qualified expenses covered to a maximum of $500</td>
				<td>$500  (50% of $1000)</td>
				<td>$100  (50% of the $200)</td>
			</tr>

			<tr>
				<td class="side_heading">Total Tax Credit</td>
				<td>$1,500</td>
				<td>$1,100</td>
			</tr>

		</tbody>

	</table>

	<p>To use this credit, the taxpayer must file a 1098T, which schools are mandated to supply by January 31st, and file <a href="<?php echo SITE_URL . '/member/private_file/2008_8863'; ?>">form 8863</a>.</p>

</div>