<div id="member_tax_index">

	<h1>Tax Credits and Deductions<!--2005 Hope Tax Credit, Lifetime Tax Credit, and Tuition and Fees Deduction//--></h1>

	<p>The following tax credits and deduction are relevant to the vast majority of households:</p>

	<ul>

		<li><a href="<?php echo SITE_URL; ?>/member/tax/opportunity">The American Opportunity Tax Credit</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/tax/lifetime_learning">The Lifetime Learning Tax Credit</a></li>
		<li><a href="<?php echo SITE_URL; ?>/member/tax/tuition_fees">The Tuition and Fees Tax Deduction</a></li>

	</ul>

	<p>To understand these tax laws, read over the explanations and use the IRS websites.  If you do not feel comfortable with the tax law, please print it out and take it to your accountant.  Please be advised that, in our experience, many accountants do not understand these credits and deduction well.  If you would like our help, please call us while you are with your accountant.</p>

	<p>Students attending a college in the Midwestern Disaster Area which include select counties in the states of Arkansas, Illinois, Indiana, Iowa, Missouri, Nebraska, or Wisconsin we strongly advise you to consult a Tax Preparer as credits for these students are substantially higher than those shown on the following pages.  If you wish to not do so please at least read Chapter 3 of IRS Publication 970.</p>

	<h6>Download</h6>

	<p><a href="<?php echo SITE_URL; ?>/member/private_file/2012_8863">Form 8863</a> - to file for your taxes, you will need adobe acrobat and can fill the form out online and print.</p>
	<p><a href="<?php echo SITE_URL; ?>/member/private_file/2012_970">Publication 970</a> - the IRS publication explaining the tax code in adobe acrobat format.</p>

</div>