<div id="member_tax_lifetime_learning">

	<h1>Lifetime Learning Tax Credit</h1>
	
	<p>Keep in mind that a tax credit is not financial aid.  No check gets cut from anyone to the student, parents, or school.  A tax credit is a direct reduction of the amount of tax money you owe the IRS.  A tax credit is different than a tax deduction.  With deductions, the amount of income the IRS may tax is reduced.</p>
	
	<h3>Who Qualifies for this Tax Credit?</h3>
	
	<p>Because a tax credit is a direct reduction of the amount you owe the IRS, one needs to owe taxes to qualify for a tax credit such as the Lifetime Learning Tax Credit.  If you owe no taxes, then you have no eligibility for this tax credit.  If you owe less in taxes than the total amount of the credit, the credit will reduce your liability to the IRS to zero dollars.</p>
	<p>This benefit is available to parents and any or all dependents. There is no requirement for the student to be at least 1/2-time or be in a degree seeking program as with the Lifetime Learning Tax Credit.  Nor does the drug conviction rule apply.</p>
	






<p><strong>Maximum credit </strong></p>
<p>Up to $2,000 credit per return</p>

<p><strong>Limit on modified adjusted gross income (MAGI)</strong></p>
<p>$124,000 if married filing jointly; $62,000 if single, head of household, or qualifying widow(er)</p>

<p><strong>Credit Limit</strong></p>
<p>To the amount of tax you must pay on your taxable income</p>

<p><strong>Period of Eligibility </strong></p>
<p>Available for all years of postsecondary education and for courses to acquire or improve job skills</p>

<p><strong>Term of Eligibility</strong></p>
<p>Available for an unlimited number of years</p>

<p><strong>Term of when the payments were made </strong></p>
<p>The tax year in question and 3 months into the next tax year.</p>

<p><strong>Type of program required </strong></p>
<p>Student does not need to be pursuing a program leading to a degree or other recognized education credential</p>

<p><strong>Required Enrollment </strong></p>
<p>Available for one or more courses</p>

<p><strong>Qualified expenses </strong></p>
<p>Tuition and fees required for enrollment or attendance (including amounts required to be paid to the institution for course-related books, supplies, and equipment)</p>

<p><strong>Felony drug conviction </strong></p>
<p>Felony drug convictions do not make the student ineligible</p>












<!--<p>There is no requirement for the student to be at least 1/2 or be on a degree seeking path as with the Hope Scholarship. Nor does the drug conviction rule apply.</p>
	
	<h3>Qualifying Income Amounts</h3>
	
	<table>
		
		<thead>
		
			<tr>
			
				<th>Taxpayer's Status</th>
				<th>Maximum Income</th>
				<th>Maximum Income With Phase-Out</th>
			
			</tr>
		
		</thead>
		
		<tbody>
		
			<tr>
		
				<td class="side_heading">Single</td>
				<td>$48,000</td>
				<td>$58,000</td>
		
			</tr>
		
			<tr>
		
				<td class="side_heading">Married Filing Jointly</td>
				<td>$96,000</td>
				<td>$116,000</td>
		
			</tr>
			
		</tbody>
		
	</table>
	
	<p>The <em>Maximum Income</em> column above shows the maximum income you may earn and still obtain the full tax credit amount.  The amount of credit for those above the maximum income level decreases in phases until one reaches the Maximum Income with Phase-Out amount.  At this income level and higher, no credit is available to the taxpayer.</p>
	
	<h3>Calculating Your Credit</h3>
	
	<p>This credit applies only for tuition and fees at accredited colleges that are approved by the Department of Education.  In other words, if the school offers FFELP loans, it is an accredited college approved by the Department of Education.  Cost of books, supplies, and equipment may be included only if they must be paid to the school in order to enroll.</p>
	<p>Room and board, transportation, and living expenses may not be included in the credit you claim.  If a student receives a scholarship for full tuition, this credit cannot be used.</p>
	<p>A family can claim a total Lifetime Learning Tax Credit of $2000 per year.  In technical terms, the Lifetime Learning Tax Credit is available for 20% of the first $10,000 of qualified educational expense.  An advantage of this credit over the Hope Scholarship Tax Credit is that there is no limit on the number of years that the Lifetime Learning Tax Credit can be used.</p>
	<p>Keep in mind that a student cannot use both tax credits in the same year.  Also, you cannot claim a Lifetime Learning Tax Credit in the same year that you are claiming a Tuition and Fees Deduction for the same student.  A tax professional should determine which is in the best interest of the taxpayer.</p>
-->




	<p>To use this credit, the taxpayer must file a 1098T, which schools are mandated to supply by January 31st, and file <a href="<?php echo SITE_URL . '/member/private_file/2012_8863'; ?>">form 8863</a>.</p>

</div>