<div id="member_tax_tuition_fees">

	<h1>Tuition and Fees Tax Deduction</h1>
	
	<p>Keep in mind that a tax deduction is different than a tax credit. Tax credits directly reduce the amount of your tax you owe.  A tax deduction reduces the amount of your income that the IRS may tax. The Tuition and Fees Tax Deduction is similar to deducting charitable contributions or mortgage interest to lower your taxable income.  The deduction can be used even if you do not itemize your taxes on a 1040 Schedule A.</p>
		
	<h3>Who Qualifies for this Deduction?</h3>
	
	<p>This deduction may only be taken by students at accredited colleges that are approved by the Department of Education.  In other words, if the school offers FFELP loans, it is an accredited college approved by the Department of Education.</p>	
	<p>A taxpayer can take the Tuition and Fees Deduction if the student is the taxpayer, taxpayer's spouse, or the taxpayer's dependent and if the student is enrolled at least on a 1/2 -time basis.</p>
	
	<h3>Income Amounts</h3>

	<table>
		
		<thead>
		
			<tr>
			
				<th>Deduction Amount</th>
				<th>Taxpayer's Status</th>
				<th>Maximum Income</th>
				<th>Max. Income With Phaseout</th>
			
			</tr>
			
		</thead>
		
		<tbody>
		
			<tr>
			
				<td>$4,000</td>
				<td>Single</td>
				<td>$65,000</td>
				<td>N/A</td>
			
			</tr>
			
			<tr>
			
				<td></td>
				<td>Married Filing Jointly</td>
				<td>$130,000</td>
				<td>N/A</td>
			
			</tr>
			
			<tr>
			
				<td>$2,000</td>
				<td>Single</td>
				<td>$65,000</td>
				<td>$80,000</td>
			
			</tr>
			
			<tr>
			
				<td></td>
				<td>Married Filing Jointly</td>
				<td>$130,000</td>
				<td>$160,000</td>
			
			</tr>
			
		</tbody>
			
	</table>
	
	<p>The Maximum Income column above shows the maximum income you may earn and still claim the tax deduction amount.  The amount of deduction allowed for those above the maximum income level decreases in phases until one reaches the Maximum Income with Phase-Out amount.  At this income level and higher, no deduction may be taken by the taxpayer.</p>
	
	<h3>Calculating Your Tax Deduction</h3>
	
	<p>The Tuition and Fees Deduction can be used for any mandatory education-related expenses, such as tuition, room and board, student loan interest, books, education-related travel, etc.  Be aware that the IRS is somewhat picky about room and board expense.  The amount deducted for room and board has to be actual cost of a college's on-campus or off-campus housing, whichever is less.  Also be aware that origination fees and capitalized interest of student loans may both be included in the amount you deduct.</p>
	<p>A taxpayer can count interest paid as a part of his/her education-related expenses if (s)he meets the following criteria:</p>
	
	<ul>
	
		<li>The taxpayer's IRS filing status is anything other than married filing separately.</li>
		<li>The taxpayer is not used as an exemption on anyone else's tax return.</li>
		<li>The taxpayer paid the interest on a qualified student loan.</li>
		<li>The taxpayer is legally obligated to pay the interest on the loan.</li>
	
	</ul>
	
	<p>To use this deduction, the taxpayer must file a 1098E, which the lender is mandated to supply by January 31st, and report the deduction on line 33 of Form 1040 or line 18 of Form 1040A.</p>

</div>