<div id="admin_styles_view">

	<h1>View Style <?php echo $style->get( 'id' ); ?></h1>

	<table cellspacing="0" class="information_table">
		<tr>
			<td>Background Color:</td>
			<td><?php echo $style->get( 'background_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'background_color' ); ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
		</tr>
		<tr>
			<td>Menu Color:</td>
			<td><?php echo $style->get( 'menu_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'menu_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Menu Font Color:</td>
			<td><?php echo $style->get( 'menu_font_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'menu_font_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Content Color:</td>
			<td><?php echo $style->get( 'content_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'content_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Font Color:</td>
			<td><?php echo $style->get( 'font_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'font_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Accent Color:</td>
			<td><?php echo $style->get( 'accent_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'accent_color' ); ?>">&nbsp;</td>
		</tr>		
		<tr>
			<td>Heading Color:</td>
			<td><?php echo $style->get( 'heading_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'heading_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Link Color:</td>
			<td><?php echo $style->get( 'link_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'link_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Footer Color:</td>
			<td><?php echo $style->get( 'footer_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'footer_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Footer Font Color:</td>
			<td><?php echo $style->get( 'footer_font_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'footer_font_color' ); ?>">&nbsp;</td>
		</tr>
		<tr>
			<td>Border Color:</td>
			<td><?php echo $style->get( 'border_color' ); ?></td>
			<td style="background-color: #<?php echo $style->get( 'border_color' ); ?>">&nbsp;</td>
		</tr>
	</table>

</div>