<p><strong>ABOUT SCHOLASTIC RESOURCES</strong></p>
<p><strong>___________________________________________________________________</strong></p>
<p>James Navarra&nbsp;has helped the parents of college bound high school students through the college financial aid process for over 15 years.</p>
<p>Scholastic Resources website, to the best of our knowledge, is the only place that parents and students can come to when they need to&nbsp;hear what it takes to successfully prepare for and finance college.</p>
<p>Scholastic Resources is a leader in providing college financial planning solutions to parents of college-bound students, helping them solve their college funding dilemma.&nbsp; Thus, Scholastic Resources exists to create every advantage for our members and their parents, helping them make smart, strategic decisions as they prepare for and finance college.</p>
<p>Our goal is simply to offer you a valuable service that helps you to make excellent college planning and college funding decisions.&nbsp; The benefit of these decisions will be savings on your college costs.</p>
<p>We are proud of all the excellent services we offer, but our "company heartbeat" is to make college financially possible by:</p>
<p>(1) Making sure that the student's career choice aligns with the student's abilities, desires, ethics, and desired financial rewards and is unlikely to change.</p>
<p>(2) Working with parents and students to position them for the optimum financial aid package.</p>
<p>FOR MORE DETAILED INFORMATION, PLEASE GO TO <span style="text-decoration: underline;">MEMBER SERVICES OR COLLEGE&nbsp;PLANNING INFORMATION</span>&nbsp;ON HOME PAGE AND THEN TAKE A <span style="text-decoration: underline;">FREE TOUR</span>.</p>