<script type="text/javascript" src="<?php echo SITE_URL . '/js/tiny_mce/tiny_mce_gzip.js'; ?>"></script>

<script type="text/javascript">

	tinyMCE_GZ.init({
		themes: "advanced",
		languages: "en",
		disk_cache: true,
		debug: false
	});
	
</script>

<script type="text/javascript">

	tinyMCE.init({
		mode: "exact",
		elements: "news",
		theme: "advanced",
		skin: "o2k7",
		skin_variant: "black",
		theme_advanced_buttons1: "bold,italic,underline,link,unlink,undo,redo",
		theme_advanced_buttons2: "",
		theme_advanced_buttons3: ""
	});

</script>

<?php echo $form->output(); ?>