<h1>Case Studies - College Funding Coaches is a Winning Solution!</h1>
<p>The following real life stories demonstrate how we&rsquo;ve coached a variety of families through the college funding process and helped them achieve a better overall outcome based on their unique objectives.</p>
<ul>
<li><a href="single_parent" target="_self">Single Parent Takes On Too Much Debt</a></li>
<li><a href="dual_income" target="_self">The Trappings of a Dual Income Household</a></li>
<li><a href="success_penalties" target="_self">The Success Penalties of a Professional</a></li>
</ul>