<h1>Consultations and Programs</h1>
<p>College Funding Coaches offers a variety of interactive programs and services designed to reduce the out-of-pocket costs for college. All of our coaching is designed to address the challenges and issues facing families with college-bound students. We customize a series of programs to fit the needs of any family&rsquo;s unique circumstances and goals.</p>
<p>&nbsp;</p>
<h3>College Concierge&trade;</h3>
<p>We will coach your family through the entire process of positioning both the student and the parents for optimal results in the college admissions and funding process.</p>
<p>For the student, we will guide you through&nbsp;very specific modules of activities <strong>designed to increase your probability of finding the right school at the right price</strong>.&nbsp; We do not take anything for granted and will direct your towards the tools and techniques that have a proven track record for delivering results.</p>
<p>For the parents, we will <strong>create a comprehensive financial plan with college funding and retirement as the core objectives</strong>. We will identify tax-efficient methods for reducing the out-of-pocket expenses related to paying for college and redirect savings into retirement plans.</p>
<p><a href="http://www.collegefundingcoaches.com/index.php?option=com_facileforms&amp;Itemid=51" target="_blank">Click here to schedule a NO COST, NO OBLIGATION consultation.</a></p>
<p>&nbsp;</p>
<h3>College Cash Flow&trade;</h3>
<p>We will teach the parents of college-bound students how to maintain their current lifestyle, continue to fund their own retirement, and pay for college&hellip;all at the same time.</p>
<p>We are experts at discovering hidden cash flow and easily accessible &ldquo;tax scholarships&rdquo; to create the funding necessary for a first-rate education.</p>
<p><a href="http://www.collegefundingcoaches.com/index.php?option=com_facileforms&amp;Itemid=51" target="_blank">Click here to schedule a NO COST, NO OBLIGATION consultation.</a></p>
<p>&nbsp;</p>
<h3>Student-Athlete RX Program&nbsp;</h3>
<p>We will teach student-athletes how to market themselves to colleges and universities that offer athletic scholarships and/or academic scholarships to athletes. This proven method of marketing and communication with collegiate coaches will improve the likelihood of reducing the out-of-pocket expenses associated with the college through scholarship dollars allocated to athletic departments.</p>
<p><a href="http://www.collegefundingcoaches.com/index.php?option=com_facileforms&amp;Itemid=51" target="_blank">Click here to schedule a NO COST, NO OBLIGATION consultation.</a></p>