<h1>How We Work</h1>
<p><strong>We are on a mission to develop a more educated culture, totally self-reliant citizens and a less dependent society</strong>. We believe in the philosophy that no undertaking is too great to be successfully accomplished!</p>
<h3>Guiding Principles</h3>
<ul>
<li>We are your partner in prosperity.</li>
<li>We never forget that we work for you.</li>
<li>The only way we are successful is if you are successful.</li>
</ul>
<p>To that end, if you could take a stroll around our minds, you&rsquo;d hear us constantly asking ourselves this question: <strong>&ldquo;Is that something I would do?&rdquo;</strong> It&rsquo;s a simple test, but a very powerful one&mdash;because by putting ourselves in&nbsp;your shoes, we&rsquo;re that much closer to feeling confident that our every recommendation is feasible. If we&rsquo;re able to answer our question with a yes, the recommendation is clear. If the answer is no&hellip;we won't even suggest it!</p>
<p><strong>Referrals are the number one way we meet new families with college-bound students and we take the trust and confidence our clients place in us very, very seriously.</strong></p>
<h3>Expected Results</h3>
<h4>First, you can expect to have clarity, composure and confidence.</h4>
<p>If you could learn the little-known strategies and techniques that would guarantee your children would go to the right school for the right price and you could maintain your current lifestyle and still meet your retirement goals, what would that mean in terms of your level of stress and your peace of mind?</p>
<p>Like they say in the credit card commercial, it&rsquo;s priceless. Like we tell our clients, it&rsquo;s our mission.</p>
<p><strong>We will explain the who, what, when and where involved in finding and funding an outstanding college education. We will then offer a variety of alternatives as to the how.</strong></p>
<p>If you&rsquo;ve been through all this before (perhaps with an older child), you can expect to spend significantly fewer hours and substantially fewer dollars with our help.</p>
<h4>Second, we teach you a mindset for success.</h4>
<p>Have you ever noticed that many &ldquo;experts&rdquo; suffer from tunnel vision as to how they approach problem-solving? They use the same strategies, programs and networks that have been in place for years&mdash;always getting the same results and wondering why they haven&rsquo;t seen any improvement.</p>
<p>The exact same material is presented on &ldquo;Scholarship Night&rdquo; or &ldquo;Financial Aid Night&rdquo; or &ldquo;College Prep Night&rdquo;&hellip;the only difference is that you are directed to the Internet versus the library.</p>
<p><strong>Albert Einstein once said,<em> &ldquo;The current problems we face cannot be solved at the same level of thinking with which they were created.&rdquo;</em></strong></p>
<p>My team and I are constantly seeking new resources, alliances and technologies that will help us solve our clients&rsquo; problems in the most successful ways. We are proud to say we are great synthesizers of knowledge and big believers in integration.</p>
<p>We are not afraid of adopting new strategies and tools that pass muster. We invest a huge amount of time and money in our own continuing education so we can continuously bring to our clients the most innovative solutions for funding a first-class college education.</p>
<p>If you practice what we preach, you will be delighted with the outcome. It will provide for a more meaningful college experience, create a successful launching pad for &ldquo;real world&rdquo; success and translate to more dollars in the family&rsquo;s pocketbook. We guarantee at least a 25% savings in the overall cost of a college education and an improvement in current cash flow.</p>
<h4>Third, we teach you innovative, high-impact strategies.</h4>
<p>Our coaching method focuses on practical strategies that minimize your time and money to maximize results. Your risk is virtually eliminated because we teach proven methods for improving the probability that your child will be accepted at the right school for the right price.</p>
<p>How many college educations will you fund?????</p>
<p>Our network of experts helps thousands of students every year go to the school of their choice without going broke. We are highly confident that we know what works and how to get the job done right.</p>
<p>Most importantly, we understand that college funding and retirement are more closely tied than most parents know. Parents simply don&rsquo;t realize they are paying for college with after-tax dollars, robbing their retirement nest egg of years of compound growth, and adding unnecessary years to their time of employment due to unnecessary debt.</p>
<p>A college student can get a scholarship, grant, or loan for their education; parents don&rsquo;t qualify for any of those things in retirement! We begin with the end in mind and work in reverse so that all of our clients stay on track for retirement.</p>
<h4>Fourth, what we teach you creates lifelong affluence.</h4>
<p>Like the ancient proverb says, &ldquo;Give a man a fish and you feed him for a day. Teach him to fish and you feed him for a lifetime.&rdquo;</p>
<p>The life skills that the student will get from our special brand of coaching, our college selection process and the guidance involved in everything under the &ldquo;admissions&rdquo; umbrella will teach them lessons they will use forever. It will provide them with the systematic thinking required to tackle any goal they set out to achieve, and instill the confidence to conquer the tasks necessary for success.</p>
<p>The financial foundation resulting from this process allows parents to understand their current financial standing, learn how to build their bridge to retirement and what it will take to manage their income and assets in the future.</p>
<p>We stand by our ability to offer dual benefits. As your child receives a terrific college education, you will receive a comprehensive financial blueprint and obtain all the strategies and tactics that will enable you to demonstrate the most savvy financial management skills.</p>
<h4>Fifth, you get never-ending support from our world-class coaching team.&nbsp;</h4>
<p>As college cash flow experts, we understand the three biggest investments most parents make:</p>
<ul>
<li>Their home</li>
<li>Their children&rsquo;s education</li>
<li>Their own retirement</li>
</ul>
<p>As experts in the field, we are confident in our assessment. We are also confident in our belief that because we can solve the college funding dilemma, we can help parents solve the retirement dilemma.</p>
<p>We became College Funding Coaches because we recognize the need for guidance, feedback, accountability and a jumpstart on the learning curve. We are pleased to offer great advice about what to do and how to do it, and help families to realize their full potential without making expensive and unnecessary mistakes.</p>
<h3>Our Approach</h3>
<p>Fundamentals and formulas work, but&hellip;&nbsp; above average grades, combined with above average test scores, combined with above average marketing and planning&hellip;&nbsp; produce above average results. Sounds simple, right?</p>
<p>We'll be the first to admit that simple does not mean easy.</p>
<p>&nbsp;We respect the fact that different clients need different things, just as one size does not fit all. For this, we approach each family&rsquo;s situation with the same intention: to create the best possible result with the family&rsquo;s objectives driving the solutions.</p>
<p>We spend the necessary time required to understand what is important to you, so we can develop a game plan uniquely suited to your priorities.</p>
<p>We have checklists for our checklists to make sure nothing is left to chance.</p>
<p>For those activities that are the same no matter the family&rsquo;s circumstances (such as reporting financial data, filing forms, identifying appropriate schools, etc.), we have created tracking systems that allow us to make sure the details won&rsquo;t fall through the cracks. Part of what you&rsquo;re paying us to do is alleviate the predictable errors.</p>
<p>For those activities that are unique to the student and/or family (such as scholarship applications, admissions essays, campus visits, financial award appeals, etc.), we have manuals, guidelines and samples, and will provide any amount of consultation time necessary for you to feel you are always putting forth your best effort.</p>
<p>Get it right the first time. College cash flow planning requires that we plan for every child&rsquo;s education at the inception of the oldest child&rsquo;s college funding experience. Since it is not uncommon for us to meet with families that are planning to send several children to college, we recognize that different children will have different interests, strengths and educational needs. We anticipate the timelines and cash flow requirements for all family members that are considered college-bound and reflect that in our analysis and recommendations.</p>
<h3>Why We&rsquo;re Different</h3>
<p>We stand by our credentials and our experience. As Certified College Planning Specialists, we are trained in the intricacies of the financial aid system, education tax credits, income tax strategies that relate specifically to funding college, tuition discount strategies used by private universities, the tax considerations related to scholarships, debt consolidation evaluation and analysis, the financial award appeal process and creative cash flow and borrowing strategies that benefit families focused on funding college.</p>
<p>We are licensed to give advice, sell securities and sell insurance.</p>
<p>We can assure you that we&rsquo;ve done this for a lot of families. (We wouldn&rsquo;t want to be the first patient of a brain surgeon fresh out of med school, either!) We support our promise that we are not practicing &ldquo;on-the-job training&rdquo; with your family&rsquo;s future.</p>
<p>Members of our coaching staff have helped hundreds of families realize their educational and retirement goals in an affordable fashion. Our collective experience totals more than 350 years of serving families with college-bound kids!</p>
<p><a href="http://collegefundingcoaches.collegiate-advisor.com/ext/38/client_profile" target="_blank">Click here to find examples of real families and their real results</a>.</p>