<li>Take the SAT I or ACT</li>
<li>For letters of recommendation, choose which teachers you will ask.</li>
<li>Work on college essays - have an English teacher read your essay for grammar and content</li>
<li>Check out college fairs</li>
<li>Plan college visits</li>
<li>Be sure all colleges you've applied to receive your official SAT and/or ACT score report (order additional score reports if you did not do this when you registered to take the exam)</li>