<li>Last time to take the SAT I, ACT, or SAT II for</li>
<li>Ask for recommendations politely - remember stamped, addressed envelopes</li>
<li>Attend Financial Aid Night for Seniors</li>
<li>Read any financial aid literature sent by the colleges you applied to</li>
<li>Check deadlines for private school applications - most have deadlines ranging from December 15 to February 15 - be sure you've included everything (check or fee waiver, optional photo, essay, other supplementary information)</li>