<li>ATTEND ALL SCHEDULED JUNIOR WORKSHOPS WITH YOUR COUNSELOR.</li>
<li>Register for the March SAT I if you have completed the math courses covered on the SAT I AND you have done the proper preparation for the exam. If not, plan to take the SAT I in May or June.</li>
<li>Talk to you counselor and teachers about taking the SAT II: Subject Tests this spring.</li>
<li>Plan to visit colleges this spring while they're in session.</li>
<li>Start to explore your college options.</li>
<li>Think about which college characteristics are important to you.</li>
<li>Have an interview with admissions officers when you visit campuses.</li>
<li>Don't spend so much time trying to improve standardized test scores that grades and co-curricular involvement suffer. Strive to find a balance and maintain it.</li>