<li>Start thinking about college majors related to your interests and career goals</li>
<li>Request applications, brochures, and financial aid information from your colleges.</li>
<li>Visit colleges, take tours, and have interviews</li>
<li>Continue to refine your list of schools.</li>
<li>Contact coaches if applicable.</li>
<li>Begin preparing for the actual application process. (ex. Start a draft of a college essay)</li>