<li>Meet with your guidance counselor as soon as you can to discuss your plans. Make sure you are on track to graduate and check your transcripts to make sure you have all the credits you need to get into the school(s) of your choice.</li>
<li>Make sure that schools you've identified still meet your requirements. Change your list, if necessary.</li>
<li>Contact those schools that have made your final cut to request information and applications for admission. Ask about admission requirements, application deadlines and any required fees, and financial aid. Ask if these schools will need official copies of your transcripts at the time you send in your application.</li>
<li>Register for the October/November SAT, ACT, and SAT Subject Tests.</li>
<li>If you are planning to apply for Early Action or Early Decision, you need to prepare and submit those applications now.  Make sure you allow enough time to prepare any essays you will need to include in your application or to meet any audition or portfolio requirements.</li>
<li>As you prepare these early applications, be sure to give any recommendation forms to appropriate teachers and counselors with stamped, college-addressed envelopes to be included with your application. Make sure your portions of the forms are filled out completely and accurately. Also, don't forget to request that your high school send your official transcripts to the school(s) to which you are applying. Also, schedule any required school interviews.</li>
<li>Send for applications</li>
<li>Begin a file for each college</li>
<li>Photocopy applications and begin to fill out draft(s)</li>
<li>Be sure you are taking the correct courses for the college(s) of your choice (if you have any questions, discuss with your counselor)</li>
<li>Attend College Night for Seniors &amp; Their Parents at JS</li>
<li>Get off to a good start academically</li>