<p style="text-align: center;"><strong><em>"Helping Students Pursue Their Educational Goals"</em></strong></p>
<p style="text-align: center;">&nbsp;</p>
<p class="MsoNormal">Our founder, Steven Rasure, is a Certified College Planning Specialist.&nbsp; College planning is a little known, but very important niche in the financial world.&nbsp; When it comes to a family's financial future, paying for college can play a very large role. So there is a need for legitimate information on how to actually pay for college without spending your life savings.</p>
<p class="MsoNormal">Check Steven out on <a title="National Institute of Certified College Planners" href="http://parents.niccp.com/search.asp" target="_blank">www.niccp.com</a></p>
<p>&nbsp;</p>
<div style="width: 35%; margin-left: 50px; line-height: 70px; background-image: url(http://photos-f.ak.fbcdn.net/hphotos-ak-snc1/hs264.snc1/9125_782837714940_15913739_44224941_4621739_n.jpg);">
<p style="margin-left:10px;"><a class="lftCat" href="http://photos-f.ak.fbcdn.net/hphotos-ak-snc1/hs264.snc1/9125_782837714940_15913739_44224941_4621739_n.jpg">.</a></p>
</div>
<p>&nbsp;</p>
<p>While academic and college-related entities attempt to present an unbiased explanation of a successful transition into college payments, inevitably their biases come to the front.  Steven decided that parents and students need a break from "the spin" and deserve to hear the truth about what it takes to successfully prepare for and finance college.</p>
<p>&nbsp;</p>
<p>Unfortunately, the real truth of the cost of a college education is very difficult to find.  Key Bank research released on April 27, 2006 says:</p>
<p class="MsoNormal" style="margin-left: 0.5in;">Sixty-nine percent of students who live away from home and sixty-six percent of parents are surprised by how much money is eaten up by ancillary expenses like books, utilities, groceries, entertainment, cell phones, computer software, transportation and travel... Thirty percent of students and twenty-five percent of parents said they had no idea textbooks would cost as much as they do.</p>
<p class="MsoNormal" style="margin-left: 0.5in;">&nbsp;</p>
<p>Thus, Education Outlook, LLC exists to create every advantage for our members and their parents, helping them make smart, strategic decisions as they prepare for and finance college.  We are proud of all the excellent services we offer, but our "company heartbeat" is to make college financially possible by:</p>
<ol type="1">
<li class="MsoNormal" style="margin-bottom: 12pt;">Making sure that the      student's career choice aligns with the student's abilities, desires,      ethics, and desired financial rewards and is unlikely to change.</li>
<li class="MsoNormal">Working with parents and      students to position them for the optimal financial aid package.</li>
</ol>
<p>&nbsp;</p>
<p><a href="http://www.collegiateadvisors.com/services.php"> </a></p>