<p style="text-align: center;"><span style="text-decoration: underline;"><strong>MEMBER SIGN-UP</strong></span></p>
<p>Signing up to receive Education Outlook's services is quite easy and can be done online, over the phone, or at one of our free workshops.</p>
<p>Naturally you'll have some questions and we'll be happy to take time with you to answer them. If you decide to sign up with Education Outlook after that conversation, you will get your own Education Outlook account. You will receive a username and password which will give you access to the private section of the Education Outlook website. You will be able to use the many aids to college success that we have collected for you.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p style="text-align: center;">For questions about membership simply send an email to <span style="text-decoration: underline;">info@educationoutlookllc.com</span></p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>