<div id="retirement_iras">

	<h1>Traditional vs. Roth IRA's</h1>
	
	<table>
		<thead>
			<tr>
				<th colspan="2">Contribution Limits for all IRAs Owned</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Individual Contribution Limit</td>
				<td>Additional Contribution allowed for those 50 or older who have not maximized their contributions to date</td>
			</tr>
			<tr>
				<td>The lesser of earned income or $5,000</td>
				<td>$1,000</td>
			</tr>
			<tr>
				<td colspan="2">For married couples the amount of contribution is double. A married couple can contribute up to $10,000 per annum and have additional contributions of $2,000</td>
			</tr>
		</tbody>
	</table>
	
	<table>
		<thead>
			<tr>
				<th colspan="2">Traditional IRA</th><th colspan="2">Roth IRA</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td colspan="4"><em>Eligibility to Contribute</em></td>
			</tr>
			<tr>
				<td colspan="2" rowspan="4">If either you or your spouse is younger than 70.5 years old, you can contribute up to the maximum amount.</td>
				<td colspan="2">There is no maximum age for contributing to a Roth IRA.  The amount that you are allowed to contribute on an annual basis is based on what is called your Modified Adjusted Gross Income.</td> 
			</tr>
			<tr>
				<td>Single</td>
				<td>MAGI less than $99,000 for a full contribution or $99,000 - 114,000 for a partial contribution</td>
			</tr>
			<tr>
				<td>Married Filing Jointly</td>
				<td>MAGI less than $156,000 for a full contribution or $156,000 - 166,000 for a partial contribution</td>
			</tr>
			<tr>
				<td>Married Filing Separately</td>
				<td>MAGI $0 - 10,000 for a partial contribution; MAGI greater than $10,000, a contribution is not allowed</td>
			</tr>
			<tr>
				<td colspan="4"><em>Treatment Upon Distribution</em></td>
			</tr>
			<tr>
				<td colspan="2">
					<ul>
						<li>Distributions will be taxed at the tax rate that you are subject to on the year of distribution</li>
						<li>Whatever amount is withdrawn prior to 59.5 will also be subject to a 10% penalty.</li>
					</ul>
				</td>
				<td colspan="2">
					<ul>
						<li>There are no regular income tax or penalties on a Roth IRA distribution if the distribution is five years from the date of contribution assuming the following;
							<ul>
								<li>The distribution is for a first-time home purchase</li>
								<li>The distribution is due to the contributor being disabled</li>
								<li>The recipient is over 59.5 years old</li>
								<li>The recipient is the beneficiary of an estate</li>
							</ul>
						</li>
						<li>The earnings are taxed at the owner's rate and subject to a 10% penalty if said distributions occur within 5 years of the contribution and the contributor is 59.5 or less</li>
					</ul>
				</td>
			</tr>
			<tr>
				<td colspan="4"><em>Required Minimum Distributions (RMDs)</em></td>
			</tr>
			<tr>
				<td colspan="2">Required Minimum Distributions begin when the owner of the IRA is 70.5. If the RMD's are not made the tax penalty can be quite dramatic.</td>
				<td colspan="2">There is no penalty for never taking any distributions prior to death. Typically, except in the case of a spouse, beneficiaries are required to start distributions within a year of the death of the contributor.</td>
			</tr>
		</tbody>
	</table>
	
	<h3>Thinking of converting your Traditional IRA to a Roth IRA?</h3>
	
	<p>You can certainly convert from a traditional IRA to a Roth IRA. Please understand two issues:</p>
	
	<ol>
	
		<li>You will have to pay income taxes on the distribution</li>
		<li>This is a very complicated scenario: Please call <?php echo $business_name; ?> Financial Services before you make this decision so we can prevent the possible loss of funds to taxes or penalties.</li>
		
	</ol>
	
	<p>Below are some scenarios</p>
	
	<table>
		<thead>
			<tr>
				<th>Converting:</th>
				<th>Not Converting:</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>The IRA itself can pay for the taxes required</td>
				<td>You need to liquidate other assets to pay the taxes caused by the conversion</td>
			</tr>
			<tr>
				<td>Your MAGI is equal to or less than $100,000</td>
				<td>Your MAGI exceeds $100,000</td>
			</tr>
			<tr>
				<td>You tax bracket will NOT decrease post-retirement</td>
				<td>Your tax bracket WILL decrease post retirement.</td>
			</tr>
		</tbody>
	</table>
	
	<h3>Mutual Funds</h3>
	
	<p>A mutual fund is nothing more than a group of individuals joining together to purchase investments. Mutual Funds generally allow for lower risk as the risk of a loss is transferred to everyone in the group. Conversely, mutual funds often have lower returns that high flying stocks because the return on those stocks is also transferred to everyone in the group. From this perspective, the easiest way to view a mutual fund is that if the total fund has $100 in it, and you have invested $10 into the fund, you will take 10% of the losses of the fund and also reap 10% of the profits of the fund. In reality, mutual funds range from small funds of a size in the millions of dollars range, to large, multi-billion dollar funds.</p> 
	<p>All mutual funds have at least one Portfolio Manager. The Portfolio Manager's job is to maximize the group's investment return while staying within the guidelines (called a Prospectus) of the mutual fund. For example, one mutual fund might invest solely in Asian telephone companies; another might focus on start-up technologies, etc. <?php echo $business_name; ?> Financial Services works with its clients to accommodate their investment desires as well as maximize their return on investments.</p>
	<p>For the average investor, <?php echo $business_name; ?> Financial Services believes strongly in investing in mutual funds vs. individual stocks and for several reasons:</p>
	<p><em>Risk Mitigation</em> - Mutual Funds spread risk over a very large pool of stocks as opposed to being subjected to the volatility of any one stock. </p>
	<p><em>Professional Portfolio Management</em> - At least one professional Portfolio Manager looks at over 50 stocks - all day long - as opposed to your risk of owning a handful of stocks that you might not have time to follow. </p>
	<p><em>Liquidity</em> - There is never a concern about selling out of your mutual fund as mutual funds are much easier to buy and sell than are individual stocks.  [A negative of Mutual Funds is that redemptions can force fund managers to sell stocks they might not want to in order to raise money to pay the investors who redeemed] When determining which fund to purchase, <?php echo $business_name; ?> Financial Services can on your behalf be quite picky. If you haven't read our <a href="<?php echo SITE_URL; ?>/retirement">Investing Values</a> section please do so. <?php echo $business_name; ?> Financial Services works very closely with you to make sure that we are investing in the areas that you desire. We can develop a lengthy list of funds that might look impressive. We feel however, that a more impressive tack is for us to develop for you a short list of mutual funds that best suits your particular needs.</p>

</div>