<p><em>No Membership Required</em></p>

<p>From time to time Collegiate Advisors holds Webinars explaining our services to a variety of potential clients.  Our clients range from High schools, guidance counselors, education consultants, CPA firms, tax preparers, financial planners, student loan companies, websites, insurance agents etc. In our webinars we discuss the opportunity that you have to use our private branded product as well as our web development services.</p>
<p><em>You can register for a workshop/webinar by clicking on the corresponding radio button next to the workshop/webinar and fill out the form at the bottom or click on the register link within the workshop/webinar information.</em></p>
<p style="text-align:center;">All times listed below are in Eastern Time.</p>