<p style="text-align: center;"><span style="text-decoration: underline;"><strong>Summit College Plannning</strong></span></p>
<p style="text-align: center;"><strong>Lafayette</strong></p>
<p style="text-align: center;">4050 Britt Farm Dr</p>
<p style="text-align: center;">Suite C</p>
<p style="text-align: center;">Lafayette, Indiana&nbsp; 47905</p>
<p style="text-align: center;">800-848-0274</p>
<p style="text-align: center;">jmccardle@summitbrokerage.com</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><strong>Indianapolis</strong></p>
<p style="text-align: center;">10401 N. Meridian Street</p>
<p style="text-align: center;">Indianapolis, Indiana&nbsp; 46234</p>
<p style="text-align: center;">800-848-0274</p>
<p style="text-align: center;">jmccardle@summitbrokerage.com</p>
<p style="text-align: center;"><strong>For Additional Information &amp; Updates please visit us on <a title="Summit's College Planning Twitter Page" href="http://www.twitter.com/summitcp" target="_blank">Twitter</a>, <a title="Summit's YouTube Videos" href="http://www.youtube.com/user/summitcp" target="_blank">YouTube</a> &amp; <a title="Summit's College Planning Blog" href="http://www.summitcollegeplanningblog.blogspot.com" target="_blank">Our Blog</a></strong></p>