<p style="text-align: left;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Helping You Find The Right School &amp; Spend Less</strong></p>
<p>
<p style="text-align: left;"><br />College For Less, Inc. is a professional college planning service for high school students and their families. We help students select the right college, pay less for it, and complete their studies in four years, instead of five or six.&nbsp; Those extra years can increase the cost of college by 25% to 50%.</p>
<p style="text-align: left;"><br />Unlike other companies that may offer college planning assistance in addition to their insurance or financial planning business, College For Less, Inc. specializes in helping students and families realize their college dreams.&nbsp;&nbsp; We offer a number of services that can help you meet the challenges of college selection and funding.&nbsp; Our services include:</p>
<p style="text-align: left;"><br />●&nbsp;&nbsp;&nbsp; <strong>COLLEGE PLANNING WORKSHOPS &amp; WEBINARS</strong>:&nbsp; These sessions will answer many of the most important questions parents and students ask.</p>
<p style="text-align: left;"><br />●&nbsp;&nbsp; <strong>PROFESSIONAL PLANNING PROGRAM</strong>:&nbsp; A College For Less professional will work with you to create and implement a comprehensive program to match your student with a &ldquo;best fit&rdquo; school and create a financial plan to greatly reduce the costs of college.</p>
<p style="text-align: left;"><br /><strong>Providing these services is a unique team of experienced professionals:<br />&nbsp;</strong></p>
</p>
<table style="border: none;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td style="border: none;"><img src="../../../advisor_files/32/mike.jpg" alt="" /></td>
<td style="border: none;">
<p><strong><span style="text-decoration: underline;">G. Mike Crawford, CFP, CCPS</span></strong>, CEO of <em>College For Less</em>, is a graduate of Texas A&amp;M University. He is co-founder and CEO Emeritus of LifePlan Financial Group in Dayton, OH. A Certified Financial Planner (CFP<sup>&reg;</sup>) and Certified College Planning Specialist (CCPS), Mr. Crawford was recognized in <em>Worth</em> magazine&rsquo;s list of the Top 250 Best Financial Advisers in America. He and his wife, Jean, are the parents of two sons and a daughter and have been residents of Centerville, OH, since 1978.</p>
</td>
</tr>
<tr>
<td style="border: none;"><img src="../../../advisor_files/32/allen.jpg" alt="" /></td>
<td style="border: none;">
<p><strong><span style="text-decoration: underline;">Allen E. Hye, Ph.D.</span></strong>, is a graduate of Franklin &amp; Marshall College, Middlebury College, and the University of Connecticut. He also studied in Mainz, Germany, and Copenhagen, Denmark. Professor Emeritus at Wright State University, Dr. Hye is the author of books on German language, modern drama, and American baseball fiction, and editor of a German cultural reader. He and his wife, Roberta, have lived in the Dayton, OH area since 1978, and they have two grown children.</p>
</td>
</tr>
<tr>
<td style="border: none;"><img src="../../../advisor_files/32/craig.jpg" alt="" /></td>
<td style="border: none;">
<p><strong><span style="text-decoration: underline;">Craig Rider, M.S.</span>,</strong> co-founder of The Rider Group, is a graduate of Long Island University. He founded and directed Wright State University&rsquo;s Career Planning &amp; Placement and Cooperative Education Departments and has been facilitating professional growth experiences for more than 30 years.&nbsp; Mr. Rider has achieved significant results by applying a variety of time-proven assessment tools and processes for both individuals and teams.&nbsp; Craig and his wife and business partner, Pat, have three grown children and reside in Kettering, OH.</p>
<p>&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>