<p>
<p>Students sometime need dedicated test prep help. When parents want to get test help for high school students, it is important to choose the right test prep service. Video explanation increases retention up to 70 percent. E-prep is an inexpensive option to guarantee ACT scores improve 2 or 3 points and SAT scores 100, 200 or even 300 points.</p>
<p>E-prep can improve subject tests math level 1 and math level 2 by 100 points each.</p>
<p>All programs include a vocabulary help.</p>
</p>