<div id="member_admissions_essay">

	<h1>How to Write an Admissions Essay</h1>

	<h3>Background Information</h3>
	
	<p>Typically, colleges will provide one or more topics for the admissions essay. The student can choose which one to write on.  There is no right or wrong choice.  The college is simply hoping to see how the student thinks, his/her ability to communicate those thoughts in writing, and what is important to him/her.  The student is hoping to increase his/her chances of an admissions interview by submitting an excellent essay.</p>
	<p>The essay is scored on how successfully the student supports/defends the main idea expressed or the position taken and on how logically the student presents his/her main ideas.  Also, grammar, spelling and punctuation can hurt or help your essay score.</p>
	<p>Important Note:  If a college requires more than one essay, both essays should be dynamic and captivating to the reader.  An admissions advisor can easily catch a student who took time on one essay and rushed the other.</p>
	
	<h3>Begin With Thinking</h3>
	
	<p>The importance of this step cannot be overstated!  A student has unlimited time to write an admissions essay, so (s)he should set aside a generous amount of time to ponder the essay topic in a relaxed mode and then to decide exactly what point (s)he wants to make.</p>
	<p>In this thinking stage, write down all ideas on the topic that occur to you.  It will be easier to cut ideas later in the process than to come up with additional points.  If you have trouble getting your ideas flowing, you may want to ask a parent or friend to discuss the topic with you for a bit and then begin putting ideas on paper.  Play around with the sequence of your ideas, jotting down brief possible outlines.</p>
	<p>Think thoroughly about the topic.  Essay reviewers can easily spot writing that was not preceded by the necessary thinking!  Taking time to think thoroughly will enable you to write with depth on a descriptive topic and to demonstrate awareness of multiple viewpoints in a persuasive essay. For example, if you are taking a position on a rule change in a sport, you will need to consider the impact of the change on players, managers, trainers, coaches, officials, fans, etc.  Also, search your memory bank for life experiences (your own or those of someone you know) which relate to your topic and plan to include them in your essay.</p>
	
	<h3>Create An Outline</h3>
	
	<p>Once the thinking phase has been completed, choose your main idea or viewpoint.  (Remember "thesis statement" in English class?)  Choose the main idea from your thinking time that you find the most compelling.  This is the idea that you will be able to write about most easily and convincingly.</p>
	<p>Decide which ideas support your main point.  Discard the rest.  Create an outline that orders your main points in a logical and/or convincing fashion.  Include the details that you will use to support those main points. Decide how you will transition from one main point to the next so that your essay has a sense of cohesion and pleasant flow.</p>
	
	<h3>Write a Rough Draft</h3>
	
	<p>Using your outline, write the first draft of your essay.  Balance the paragraphs as much as possible.  If writing descriptively, this will show that you gave real thought to each of your main points.  If writing persuasively, remember that it shows lack of critical thinking to write only one sentence on the ideas you disagree with and then write four paragraphs explaining your position. When finished, walk away and forget about your essay for at least 24 hours.</p>
	
	<h3>Edit Your Rough Draft </h3>
	
	<p>When you return to your essay, it's time to turn on your critical eye and be an editor. At this point, concentrate on content only.  You can take care of spelling and grammar when you proofread.</p>
	
	<h6>Evaluate your introductory paragraph:</h6>
	
	<ul>
	
		<li>Did you present 2-3 sentences of background to your main idea or viewpoint?</li>
		<li>Did you clearly state your main idea or viewpoint?</li>
		<li>Did you introduce the main ideas that will follow in the body of the essay?</li>
		<li>By the end of your first paragraph, your reader should know your thesis and have a clear idea of how you plan to support it.</li>
	
	</ul>
	
	<h6>Next, evaluate the body of the essay.</h6>
	
	<ul>
	
		<li>Did you maintain the focus presented in your introductory paragraph throughout the essay?</li>
		<li>Does each paragraph have one main idea?</li>
		<li>Are those ideas presented in a clear and logical sequence?  If not, now's the time to cut and paste.</li>
		<li>Did you provide transitions to help the reader see how your ideas hang together?</li>
		<li>Is the main idea of each paragraph adequately supported with details (facts, experiences, observations)?</li>
	
	</ul>
	
	<h6>Finally, check your summary paragraph.</h6>
	
	<ul>
	
		<li>Did you wrap up the ideas contained in the body?</li>
		<li>Did you use one or two fresh key phrases such as an attorney might use in his/her closing arguments?</li>
		<li>Did you show your reader that your main idea is logical and compelling?</li>
		<li>Regarding the length of your essay, it is better to have a shorter paper that is well written and well organized than a longer paper that is poorly written and poorly organized. Don't keep writing just to lengthen your essay, and certainly don't start repeating yourself.</li>
	
	</ul>
	
	<h3>Proofread Your Essay</h3>
	
	<p>Now it's time to read your essay again to clean up spelling, punctuation, capitalization, and grammar.  As you proofread, make sure there aren't any fragments or run-ons. A fragment is often rather short and is only a phrase rather than a sentence.  A sentence must have both a subject and a verb.  A run-on is two or more sentences written as though they were one sentence.  You can often spot them by their unusual length.</p>	
	<p>Check any "big" words you may have used. It's good to use advanced vocabulary, but only if you are confident that you are using a word correctly. Your paper has to be correct; it doesn't have to be fancy. You're not trying to impress anyone with your vocabulary but with your ability to express and develop ideas. </p>
	<p>Read your essay aloud to hear how it sounds.  This helps you to identify and correct awkward phrasing and sections of your essay that sound too formal or informal compared to the rest of your essay.</p>
	
	<h3>Have Others Review Your Essay</h3>

	<p>After editing and proofreading your admissions essay, ask 3-5 individuals to review it. These individuals should have knowledge of the field you are pursuing and strong writing skills. Ask for their help early enough so that they have plenty of time to read and give constructive criticism on your essay and you have adequate time to incorporate their suggestions into your final draft.</p>
	<p>You may want to include a copy of your application and a brief explanation of your intentions with the rough draft when you give it to your reviewers.  This helps them to see your "big picture."</p>
	
	<h3>Timed Essay Writing on Campus</h3>
	
	<p>Some schools will require a brief essay before or after your interview if you are selected to visit the campus. If you didn't complete your own work on the initial essay sent in with your application, the admissions committee will certainly notice the discrepancy between the two essays. The essay at the school is generally timed.</p>
	
	<h6>Remember and follow the steps explained above:</h6>

	<ul>
	
		<li>Think. Generate ideas about the topic. DO NOT skip this step to save time.</li>
		<li>Choose a main idea or viewpoint as the focus of your essay.</li>
		<li>Pick out the ideas that best support your main idea or viewpoint.</li>
		<li>Create an outline.</li>
		<li>Write a rough draft.  Begin with an introductory paragraph, use body paragraphs to expand your main idea or viewpoint, and conclude with a summary paragraph that wraps things up.</li>
		<li>Edit the content.</li>
		<li>Proofread to find and correct mechanical errors.</li>
		<li>Finally, be proud of your effort!</li>
	
	</ul>
	
	<p>If you are asked to write an essay that is basically an advertisement for yourself as a prospective student at the school, ask yourself the following questions when you review the content of your essay:</p>
	
	<ul>
	
		<li>Did I express a clear goal of study/desire for academic excellence?</li>
		<li>Did I include specific examples of life challenges/experiences that make me likely to succeed in this field of study at this school?</li>
		<li>Did I clarify the course of study and work experiences that have prepared me for college?</li>
		<li>Did I clarify what personal qualities make me stand out?</li>
		<li>Did I give specific examples or is this essay too abstract and dreamy?</li>
	
	</ul>
	
</div>