<div id="member_admissions_interview_prep">
	
	<h1>Admissions Interview</h1>

	<p>Machiavelli once suggested that the way to succeed in any endeavor is to rely only on those resources over which you have control and not to count on those over which you don't have control. The admissions interview is a process over which you have control. It is your greatest opportunity to prove yourself to a college and show that you are the right person for the school.</p>
	<p>The admissions interview is a crucial step in the college selection process and gives the highest return on investment. The time you spend in a successful interview has a greater chance of landing you a place at the school of your choice than any other step in the college selection process. It is your moment to shine, and you will want to be well-polished.</p>

	<h3>Preparing for the Interview</h3>

	<p>Some undergraduate school selection strategies recommend doing exhaustive research on schools, finding the one that you think would be your dream school. After spending countless hours doing the necessary research and finally understanding more about your top-choice school than most of the faculty members, you are told to go and seek an interview. Once in the interview, you would clearly be able to impress an interviewer with your knowledge of the school and would theoretically be a great student selection.</p>
	<p>However, the best approach is the direct opposite. The research is critical, and the interview is critical, but you should reverse the order in which you do them. Schedule an interview before spending hours researching a school.  The reason is simple. Why do research and potentially waste your time if you are not able to get the interview?</p>
	<p>A great source of information in your research is the internet. First, go to the school website. Review posted events such as guest speakers, workshops, athletic events, theater, and other major activities to get a sense of life at that school. Then go to a local newspaper site and read any recent news or articles on the school. Check out recent school reports, and read the message boards where students exchange information on the school. If you have any questions, it might be worthwhile posting a question to see if you get any responses. You will be able to find out a lot of background information on the school's internal culture. Finally, conduct some random searches using a search engine such as www.google.com and see if you can find anything interesting about the school on the internet. If you can't find something specific about the school, then find out what you can about the surrounding area.</p>
	<p>Don't be intimidated by the word "research."  Simply taking the time to visit the types of websites explained above will yield a wealth of information about the school you are researching.</p>

	<h3>Expected Interview Questions</h3>

	<ol>

		<li>What about yourself do you want the admissions team to most remember?</li>
		<li>Describe a typical day in your life.</li>
		<li>Who was your favorite high school teacher and why?</li>
		<li>What is the most recent book that you read?</li>
		<li>What attracts you to our institution?</li>
		<li>What have you done in your school or community that you are most proud of?</li>
		<li>During your free time, what are you most likely to do?</li>
		<li>Where do you see yourself in 10 years?</li>
		<li>If you could do high school over again, what would you change and what wouldn't you change?</li>
	
	</ol>
	
</div>