<p><em>No Membership Required</em></p>

<p>Attend one of our workshops/webinars to learn the answers to some of the following questions:</p>
<ul>

<li>How do we choose the correct college for our student?</li>
<li>Are ACT and SAT preparation courses really that important?</li>
<li>How important are the admissions essay and interview?</li>
<li>How can we minimize the cost of college?</li>
<li>Is the scholarship search worth the time?</li>
<li>How can we maximize financial aid?</li>

</ul>

<p><em>You can register for a workshop/webinar by clicking on the corresponding radio button next to the workshop/webinar and fill out the form at the bottom or click on the register link within the workshop/webinar information.</em></p>
<p style="text-align:center;">All times listed below are in Eastern Time.</p>