<li>Registering for the appropriate tests: Scholastic Assessment Test (SAT), American College Test (ACT);</li>
<li>Submitting your applications for admission;</li>
<li>Comparing acceptance offers from schools;</li>
<li>finally, after you've accepted a school's final offer, having your high school send your final transcripts to that school.</li>
<li>Don't forget that the process of applying for financial assistance to help you pay the costs of attending your school of choice is separate.</li>