<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">The American Education Funding is a&nbsp;New Jersey&nbsp;non-profit organization that, conducts the free college-funding program- "The Financial Aid Awareness Program" to students, parents, and guidance personnel throughout the New York tri-state area.</span></p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">The American Education Group understands that preparing and paying for college can be a very stressful time.&nbsp; We know how important it is for you to have answers you can depend on.<br />&nbsp;</span></p>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">The American Education Group's Program provides workshops detailing:</span></p>
<ul>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">How to plan and manage college cost</span></p>
</li>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">Type of Financial Aid available</span></p>
</li>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">"Professional Judgment" and who has the final say on what you receive.</span></p>
</li>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">Avoiding scams</span></p>
</li>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">Scholarship Searches</span></p>
</li>
<li>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">The financial Aid Process (FAFSA &amp; CSS Profile)</span></p>
</li>
</ul>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">Over 50% of all college students are forced to drop out - many die to the lack of money ... they didn't plan to fail, they simply failed to plan!</span></p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;">We have become an important resource for high school guidance personnel assisting in the dissemination of important information to their students and families providing vital, and often timely, information.<br /><br /></span></p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left">&nbsp;</p>
<p style="margin: 5px 5px 2px 4px;" align="left"><span style="font-size: x-small; font-family: Verdana, Arial, Helvetica, sans-serif;"><em>Please note that these workshops are purely informational only.&nbsp; No selling or any kind or promotion of any product will take place.</em></span></p>