<p class="MsoNoSpacing" style="margin: 0in 0in 0pt;"><span style="font-size: 8pt;"><span style="font-family: Calibri;">&nbsp;&nbsp;</span></span>&nbsp;</p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><strong><span style="text-decoration: underline;"><span style="font-size: 8pt; color: black;">Solutions for your family's Educational Goals</span></span></strong><span style="font-size: 8pt; color: black;"> </span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">&nbsp;In today's economic times the need to explore all of your strategic options is a necessity.&nbsp; Other than purchasing a home, paying for a college education may just be a family's single largest expenditure.&nbsp; There is no one blanket strategy for college planning success.&nbsp; Let us help your family develop a unique plan built just for your situation.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">We can help you avoid some of the many pitfalls of poor college planning.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">&nbsp;<em>- Did you know that 56% of students that start college never finish?</em></span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><em><span style="font-size: 8pt; color: black;">- Of those who do finish, they take an average of 5 1/2 years to complete their undergraduate degree?</span></em></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><em><span style="font-size: 8pt; color: black;">- The cost of college becomes staggering for a family of two, three, or more children.&nbsp; Unfortunately, less than 4% of all families have set aside more than $5,000 for their children's education.</span></em></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">&nbsp;Your First Step is to call Next Step at 631.271.2105 to develop your family's college funding plan.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0in 0in 10pt; line-height: normal; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto;"><span style="font-size: 8pt; color: black;">Call us at: <strong>631.271.2105</strong></span></p>
<p>
<script type="text/javascript"><!--
<br />var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");<br />document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));<br />
// --></script>
<br />
<script type="text/javascript"><!--
<br />var pageTracker = _gat._getTracker("UA-6555149-1");<br />pageTracker._trackPageview();<br />
// --></script>
</p>
<p class="MsoNoSpacing" style="margin: 0in 0in 0pt;">&nbsp;</p>