<p>&nbsp;</p>
<p><strong><span style="font-size: small;">
<p align="center">Helping You Find The Right School &amp; Spend Less</p>
</span></strong><span style="font-size: x-small;">
<p align="center">&nbsp;</p>
</span><span style="font-size: small;">
<p>College For Less is a professional college planning advisory for high school students and their families. We help students select the right college, pay less for it, and complete their studies in four years, instead of five or six. Those extra years can easily increase the cost of their education by 25% to 50%.</p>
<p>Unlike other companies that may offer college planning assistance in addition to their insurance or financial planning business, College For Less specializes in helping students and families realize their college dreams and aspirations. We offer a number of services that can help you meet the challenges of college selection and funding. Our services include:</p>
<p>&nbsp;</p>
<p><strong>*&nbsp;&nbsp; COLLEGE PLANNING WORKSHOPS:&nbsp; </strong>These sessions will answer many of the most important questions parents and students ask.</p>
<p><strong>*&nbsp; &nbsp;PROFESSIONAL PLANNING PROGRAM: &nbsp;</strong>We will work with you to create and implement a comprehensive program to match your student with a "best fit" school and design a financial plan to greatly reduce the cost of your student's education.<span style="text-decoration: underline;"> </span></p>
<p>&nbsp;</p>
<p><strong><span style="text-decoration: underline;">Jay Faber, CFP&reg; CCPS</span></strong>,&nbsp;President of College For Less, graduated from Le Mars Community High School in 1978, and Iowa State University in 1982 with a BBA degree in Finance. He is a CERTIFIED FINANCIAL PLANNER PRACTITIONER&trade; (CFP&reg;), and Certified College Planning Specialist (CCPS).</p>
<p>Jay has firsthand experience with the admissions process for highly selective schools. His son, Steve, is an aspiring film director and has completed his first year of studies at Point Park University in Pittsburgh, PA, where he is majoring in Cinema and Digital Arts.</p>
</span></p>