<p><strong>With the average four-year cost of college approaching $100,000 for one child</strong>, like most parents, you're probably very concerned about paying for college. At the same time, you are even more concerned about saving for your retirement. Therein lies the dilemma:</p>
<blockquote>
<p>Will you need to sacrifice your <a href="../../../retirement/services">retirement</a> or savings in order to educate your children?</p>
</blockquote>
<p>Most parents think that "college planning" means "saving for college" - that they are identical. They see the two goals of saving for retirement and planning for college as mutually exclusive and so they continually defer planning for college costs. The result: Most parents - regardless of income - inefficiently prepare and pay for college, thus overpaying and needlessly diverting thousands of dollars from their retirement savings.</p>
<p><strong>The fact is that college planning is NOT just "saving for college."</strong> It's implementing appropriate college and financial planning strategies that help parents most efficiently and effectively prepare and pay for college, saving potentially thousands of dollars on their college bill. Savings is ONLY one aspect.</p>
<p>College Funding Services is a leader in providing college financial planning solutions to parents of college-bound children, helping them solve their college funding dilemma.</p>
<p><strong>The practical benefit can be significant savings on a family's overall college bill - dollars that could be reallocated for other, even more urgent purposes, like retirement savings. </strong></p>
<p>Whether your income is $50,000 or $500,000, our expertise is intended to help you in the following ways:</p>
<ul type="2">
<li><strong>save</strong> thousands of dollars on your college costs </li>
<li><strong>save</strong> untold hours of research and effort attempting to become an expert in college planning </li>
<li><strong>prepare and pay</strong> for college effectively and efficiently, without incurring suffocating debt or "robbing" your retirement accounts </li>
<li><strong>learn</strong> ways to increase your retirement contributions during the college years </li>
<li><strong>send</strong> your child to the college of your choice - not just the least expensive one. </li>
</ul>
<p>Read on to learn how College Funding Services can make a difference for you - today - including how you can receive a <a href="dataform_setup.php?ref=cfs">FREE REPORT.</a></p>
<p>&nbsp;</p>
<h1><span class="secondary_page_title">Why We're Unique</span></h1>
<ol type="1">
<li><strong>Objective</strong> - Our goal is simply to offer you a valuable service that helps you to make excellent college-planning and college-funding decisions.The benefit of these decisions will be savings on your college costs. </li>
<li><strong>Solution Focused</strong> - Information is plentiful. Solutions to your unique situation are not. We provide practical and concrete solutions tailored to your unique circumstances. </li>
<li><strong>Simple</strong> - All you need to do is complete our college planning questionnaire. We'll develop a plan tailored to your unique situation and during our follow-up meeting we'll share the results along with our proposed action plan. You can take action to start reducing the cost of college - IMMEDIATELY.</li>
</ol>
<p>&nbsp;</p>
<h1 class="secondary_page_title">Client Strategies</h1>
<p>As it relates to paying the high cost of college, families fall into one of two categories: those that will qualify for financial aid, and those that will not. Therefore, College Funding Services focuses on the following to help you arrive at a comprehensive college-funding solution and become an "informed buyer of a college education":</p>
<ol type="1">
<li><strong>Strategies for middle and upper-middle income families that will qualify for financial aid -</strong> College Funding Services applies its expertise and understanding of the extremely complex financial aid system to help you leverage the system to your benefit; to apply various "secrets" of the financial aid system to help you receive the maximum amount of financial aid possible, and to make sure you don't miss out on opportunities simply due to a lack of knowledge. College Funding Services offers specific college investment and funding strategies for the financial aid candidate. Investment and funding decisions for the financial aid candidate can be very complicated and the wrong decisions may end up costing you dearly! </li>
<li><strong>Strategies for high-income families that won't qualify for financial aid -</strong> If you're one of the many families that will not qualify for any financial aid and will be expected to fund the total cost of education, all is not lost! College Funding Services can show you, through a variety of investment, income, asset, education tax-credit and funding strategies how to develop an optimized plan for preparing and paying for college costs. The strategies contained within your plan are intended to help you prepare and pay for college costs in the most effective and efficient manner, and avoid depleting retirement savings or incurring significant debt. </li>
</ol>
<p><strong>It will likely cost you thousands of dollars on your college bill and may ruin your retirement savings if you fail to capitalize on the college planning and funding strategies available to you. </strong></p>