<p><strong>"We would have NEVER found out about Ohio Northern for Aaron.&nbsp; Thanks to Jon, We found an excellent school with good financial aid!"</strong>...<em>M. Osentoski (Kokomo, IN)</em></p>
<p><strong>"I cannot believe every parent is not lining up to come see you!"</strong>...<em>T. Selzo, Founder of Rainmakers (Indianapolis, IN)</em></p>
<p><strong>"I could not be happier in working with you Jon.&nbsp; You helped with our forms and getting out of debt!"</strong>...<em>A. Haley (Indianapolis, IN)</em></p>
<p><strong>"If we did not find you, we would have over paid for college!&nbsp; You have really saved us a lot of money.&nbsp; I like that you also do our forms too!"</strong>...<em>D. Lawson, Lawson Farms (Lebanon, IN)</em></p>
<p><strong>"Just being there for us everytime we call has been a blessing, I can't believe you take all that time with us!"</strong>...<em>L. Springer (Delphi, IN)</em></p>
<p><strong>"I am excited that my kids are wanting to work with you, it helps to have their buy-in."</strong>...<em>A. Arnoldy (Brownsburg, IN)</em></p>
<p><strong>"We are so glad you helped Will get his Full-Ride, we would have not known what to do!"</strong>...<em>S. Hubertz (Lafayette, IN)</em></p>
<p><strong>"If we wouldn't have found you, Carlton would not have been going to Anderson in the fall!&nbsp; He not only loves the school but he may also get to start linebacker as a freshman!!!"</strong>...<em>J. Summe (Sheridan, IN)</em></p>
<p><strong>"We were told by a person in Purdue's Financial Aid Office to come see your presentation, We are glad we did!"</strong>...<em> T. Jones (Lafayette, IN)</em></p>
<p><strong>"We thought we were offering a good presentation for College Night before you came to the school, now when you present, we know our parent's are seeing the best and most up to date info on college planning!"</strong>...<em>C. Price, Dir. of Guidance, Rossville HS (Rossville, IN)</em></p>
<p><strong>"I got to tell you, I have sit thru many a workshop in my day, I have NEVER taken 4 pages of notes like I did tonight!&nbsp; I am VERY glad I came!"</strong>...<em>D. Sutton (Indianapolis, IN)</em></p>
<p><strong>"Parent's really need to know something like this is out there, that's why we offered YOU are our college night!&nbsp; That's also why I chose to work with you for my kids as well."</strong>...<em>A. Ramaly, Asst. Superintendant, Kokomo Schools</em></p>
<p>&nbsp;</p>
<p>&nbsp;</p>