<p>Frank Smithson is the driving force behind Southern Georgia's fastest growing financial advisement group specifically aimed at helping students afford college.&nbsp; With college costs going through the roof, the Smithson Agency is ready to provide you with a plan that not only develops a strategy for affording college, but getting through school without credit card debt.</p>
<p>Just as an FYI this is an example of what you can change. As a client you can change anything in this space that you desire. If you want to talk about your business, your cool boat, your child you may do so.</p>
<p><span style="text-decoration: underline;">Adding text.</span></p>
<p>User can add text here</p>
<p style="text-align: center;">&nbsp;</p>