<h1>Get A Head Start On College With SMART START&trade;<br /></h1>
<p><br />You can earn college credits before you ever set foot on campus. How? By participating in the Smart Start College Essentials program that lets you study at home and test out of college courses.</p>
<p>Tenured, nationally recognized professors from well-respected, colleges and universities write the Smart Start&trade; Comprehensive Learning Modules. And personalized academic support is available 15 hours per day, Monday through Friday. By completing these courses and passing the equivalency examinations, you earn college credits that can give you a head start on your college career while dramatically reducing the cost of your education.</p>
<p>Best of all, Smart Start&trade; guarantees that each student will pass the equivalency exams, or, Smart Start&trade; will pay for a local tutor and subsequent testing fees until the student passes the exam. Certain restrictions apply, and you must purchase a minimum of four modules. Call College For Less at <strong>(937) 648-5783</strong> for details.</p>
<p><span style="text-decoration: underline;">College Credit Courses Currently Offered</span>:</p>
<p>Arts/Humanities</p>
<ul>
<li>Freshman Composition</li>
<li>American Literature</li>
</ul>
<p>Business</p>
<ul>
<li>Microeconomics</li>
<li>Business Law I</li>
<li>Marketing </li>
<li>Management</li>
</ul>
<p>Science/Math</p>
<ul>
<li>College Algebra</li>
<li>Biology</li>
<li>Chemistry</li>
<li>Natural Science</li>
</ul>
<p>Social Sciences</p>
<ul>
<li>American Government</li>
<li>American History I</li>
<li>Psychology</li>
<li>Western Civilization I</li>
</ul>