<h1 style="text-align: center;">Great Tools That Will Help Your Student Find A Best-Fit College &amp; Dramatically Reduce College Costs</h1>
<p>Every parent would love for their student to attend the college that best fits their students&rsquo; needs.&nbsp; But with college costs spiraling ever upwards, wouldn&rsquo;t it be great to pay wholesale instead of retail for your student&rsquo;s education? Well, now you can.</p>
<p><br /><em>College For Less, Inc.</em> provides&nbsp;helpful tools that can help you achieve these goals in the way that works best for you.</p>
<ol>
<li><strong><span style="text-decoration: underline;">College Planning Workshops &amp; Webinars</span>:</strong> These sessions will answer many of the most important questions parents and students ask, including:<br />
<ul>
<li>How do we choose the correct college for our student?</li>
<li>Are ACT and SAT preparation courses really that important?</li>
<li>How important are the admissions essay and interview?</li>
<li>How can we minimize the cost of college?</li>
<li>Is the scholarship search worth the time?</li>
<li>Can we maximize financial aid?</li>
</ul>
</li>
<li><strong><span style="text-decoration: underline;">Professional Planning Program:</span></strong> A College For Less Professional will work with you to create and implement a comprehensive program that will match your student with a &ldquo;best-fit&rdquo; school and create a financial plan to greatly reduce the costs of college. 
<ul>
<li>Identify, attend, and succeed at the college that best prepares them to attain their personal and career goals and to fulfill their life purpose.</li>
<li>Pay less for college by understanding the financial aid system, targeting college-based awards, developing a custom financial plan for the family, managing cash flow, and making legal use of the tax code.</li>
<li>Discover and develop their unique gifts and strengths and apply them to the choice of college majors and prospective careers.</li>
</ul>
</li>
</ol>
<p><strong><br />Call (937) 648-5783 today for more information about the Professional Planning Program and to schedule a personal meeting with a <em>College For Less</em> Professional.</strong></p>
<p>&nbsp;</p>
<p>Why Certified College Planning Specialists? Anyone can call themselves a &ldquo;college planner,&rdquo; but only those with the education and experience to be tested and certified by a national accreditation organization have earned the title Certified College Planning Specialist (CCPS). This designation, like CFP (Certified Financial Planner) or CPA (Certified Public Accountant), is your assurance that you are working with a trained, experienced professional held to nationally recognized ethical standards.</p>